### ISSUE TITLE
[CALIB2] highlight in red "No detector"

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#1016]
on first tab,  third frame.
like "No image"

Nota: if an image is provided, there is a second "No detector" in red but not in the proper section.

Maybe highlight "click here" on the detector side ?

**Comment by vallsv** [comment]
This zone is used to compute the binning. That is why this message is displayed, cause the binning can't be computed.

But we can try to restructure that in order to remove that misunderstand.
