### ISSUE TITLE
Test fail on test_split_bbox_2d 

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#1021]
On both my computer and the continuous integration.
```
======================================================================
FAIL: test_split_bbox_2d (pyFAI.test.test_split_pixel.TestSplitBBoxNg)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/test/test_split_pixel.py", line 190, in test_split_bbox_2d
    self.assertEqual(abs(count_legacy - count_ng).max(), 0, "count is the same")
AssertionError: 137.00920116440278 != 0 : count is the same
```

**Comment by kif** [comment]
On Wed, 28 Nov 2018 04:22:48 -0800
Valentin Valls <notifications@github.com> wrote:

> On both my computer and the continuous integration.
> ```
> ======================================================================
> FAIL: test_split_bbox_2d (pyFAI.test.test_split_pixel.TestSplitBBoxNg)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/test/test_split_pixel.py", line 190, in test_split_bbox_2d
>     self.assertEqual(abs(count_legacy - count_ng).max(), 0, "count is the same")
> AssertionError: 137.00920116440278 != 0 : count is the same
> ```

This is work ongoing, indeed I am still working on it ... when was it merged ?

**Comment by kif** [comment]
I did not manage to reproduce the bug on debian9... maybe it is related to a newer version of cython ?

**Comment by vallsv** [comment]
Did you execute it many times? Cause it happen sometimes only.

It could be a good idea to remove this test while it is a WIP.

**Comment by kif** [comment]
On Thu, 29 Nov 2018 04:21:31 -0800
Valentin Valls <notifications@github.com> wrote:

> Did you execute it many times? Cause it happen sometimes only.

OK then it is related to the random numbers...

-- 
Jérôme Kieffer
tel +33 476 882 445

**Comment by kif** [comment]
apparently the returned result is full of zeros once out of ~5
