### ISSUE TITLE
[integration] Define a structured object to replace integration method

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#1029]
The argument `method` is right now a string concatenating a lot of informations.

It would be nice to split it into (if i am not wrong)
- The algorithm for histograming (CSR, LUT...)
- The algorithm used for integration (Python, Cython, OpenCL)
- The pixel spliting mode (no, bbox, pixel)
- The OpenCL device target (if expected)

This could help to clean up the code, and to add more features

**Comment by kif** [comment]
already merged
