### ISSUE TITLE
[gui-integration] Support hdf5 path to read images

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#1044]

**Comment by kif** [comment]
I not  manage to integrate an HDF5 file, but neither a edf image

**Comment by vallsv** [comment]
It is not plan to the 0.17 release, then it is normal

**Comment by kif** [comment]
On Fri, 14 Dec 2018 16:09:59 +0000 (UTC)
Valentin Valls <notifications@github.com> wrote:

> It is not plan to the 0.17 release, then it is normal
but is it normal that it does not process edf files ?

**Comment by vallsv** [comment]
Oh... could it be?
So that's a big issue, the worker and writer was tested, but not enough then.

**Comment by vallsv** [comment]
It's not the right place to take about that then

**Comment by kif** [comment]
The GUI interaction is missing. Needs to be passed as command line argument.
