### ISSUE TITLE
[calib2] Take a look at wrong ring alignment

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#1055]
Ring location in the fit screen do not exactly match the acquisition image (feed back from ID15A).

If the problem is obvious, it could be nice to fix it.

**Comment by vallsv** [comment]
- `ModestImage` have nothing to do with it.
- There is, i guess half-pixel of wrong displacement
- + A very big unexplained delta (few pixels 5-6)

This make me think the values used to compute the rings was wrong.

**Comment by vallsv** [comment]
Well, with a better fit, it looks to be fine by fixing the half-pixel.

**Comment by kif** [comment]
On Fri, 14 Dec 2018 10:45:46 -0800
Valentin Valls <notifications@github.com> wrote:

> - `ModestImage` have nothing to do with it.
> - There is, i guess half-pixel of wrong displacement
> - + A very big unexplained delta (few pixels 5-6)
> 
> This make me think the values used to compute the rings was wrong.

The isocontour has been changed ... but also in pyFAI-calib ?!
