### ISSUE TITLE
[error] do_2d: 

### ISSUE THREAD

**Issue by alexmarie78** [silx-kit/pyFAI#1090]
While building pyFAI with the new command line for running tests, we get this error : 
```
ERROR:pyFAI.worker:error in integration do_2d: True
Exception
Out of memory
data.shape: (1,)
data.size: 1
ai:
<pyFAI.test.test_worker.AzimuthalIntegratorMocked object at 0x7fafec3830f0>
method:
csr
```

**Comment by vallsv** [comment]
Hi. Which command line do you use?

And which test fail?

You can use `-v` to display the tests one by one
```
./run_tests.py -v
```

**Comment by vallsv** [comment]
BTW, are you testing the master or a specific version?

**Comment by alexmarie78** [comment]
I am testing the master with the debian/control modified with this command line : 
$py -c "import pyFAI.test; pyFAI.test.run_tests()"
This error appears with every python version (python, python-dbg, python3.7 and python3.7-dbg)

**Comment by legrandp** [comment]
Here the full log

https://salsa.debian.org/science-team/pyfai/-/jobs/104733/raw

the version tested is the 0.17.0 version :)

**Comment by kif** [comment]
On Thu, 10 Jan 2019 07:08:12 -0800
alexmarie78 <notifications@github.com> wrote:

> I am testing the master with the debian/control modified with this command line : 
> $py -c "import pyFAI.test; pyFAI.test.run_tests()"
> This error appears with every python version (python, python-dbg, python3.7 and python3.7-dbg)

How much memory has this computer ?
Apparently it has 3GB ... it is not much but should be enough. I hardly
ever tested with less than 4G.

Would it  be possible to run:
$py run_tests.py -v -m --installed

If it is actually a memory error, "run_tests.py" has the "--low-mem"
option which may help you.

Cheers,

Jerome

**Comment by alexmarie78** [comment]
Hello,

This computer has 16Gb according to this commandline : 
less /proc/meminfo
With $py run_tests.py -v -m --installed, this error actually disappear !
Thanks  for helping.

**Comment by vallsv** [comment]
Let's close it then
