### ISSUE TITLE
Numpy 1.16 and seg-faults 

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#1094]
Tocheck: memory alignment of complex types (like lut dtype) have changed, investigate this !

**Comment by kif** [comment]
To be integrate in PR#1089

**Comment by kif** [comment]
Funny thing: tests passes in Python3.4 using numpy 1.16 while numpy 1.16 dropped python 3.4 !

**Comment by kif** [comment]
Thanks for the precision. 
We best continue on 
https://github.com/numpy/numpy/issues/12750

**Comment by kif** [comment]
This could be a bug on the Travis side as the 14.04 images (Trusty, gcc 4.8)  are crashing but not the 16.04 images (Xenial, gcc5.3). I suspect hence a compiler issue. We are patching especially against bugs in gcc4.1 used in manylinux ...

**Comment by vallsv** [comment]
Closed by #1096
