### ISSUE TITLE
[calib2] the X and Y axis are inverted in the gui

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#1108]
everythings in the title.

**Comment by vallsv** [comment]
I don't really see how. It would be good to create a screenshot.

For example a non-square detector like the WOS is well displayed. But as it is a HDF5 defined detector, maybe, that's somehow special.

**Comment by vallsv** [comment]
To be clear an horizontal rectangle detector should be display an horizontal rectangle image.
But the output of this detector could be mapped in different ways. The output image is already an abstraction, then maybe for some detector the rendering could be wrong.

**Comment by picca** [comment]
In the GUI, you can change the Y orientation, but, when you click on this, button this is X axis which is changed.

So for me the X and Y label are wrong.
Not the displayed values :)

Is it clearer... ?

**Comment by vallsv** [comment]
Yes, thanks.
