### ISSUE TITLE
[diffmap]  pybind exception while integrating with OpenCL on GPU

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#1131]
After few integrations (about 100) this exception is thrown.

Maybe a problem with my driver?

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  pybind11_object_dealloc(): Tried to deallocate unregistered instance!
Aborted
```

**Comment by kif** [comment]
Can you provide 
* the size of the image and 
* the type of intergration
* the version of pyopencl ?

**Comment by vallsv** [comment]
- OpenCL CSR bbox split
- Dim_1: 2048 
- Dim_2: 2048
- PyOpenCL 2018.2.1

**Comment by vallsv** [comment]
I try the 2018.2.2 with the same problem.
I will test on another machine anyway.

**Comment by vallsv** [comment]
I was using Python3.5, and i also tested `no split` with the same problem.

**Comment by kif** [comment]
The issue is related to pybind11 versions of pyopencl (2018.1 and newer) when using multiple threads ...

We are working on it with Gregor Thalhammer (@geggo). Please put him in the loop to share the info.

**Comment by kif** [comment]
This has been fixed upstream (pyopencl)
