### ISSUE TITLE
[integrate] Editable poni in pixels

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#1156]

**Comment by kif** [comment]
Poni coordinate are not directly translatable into pixels ... especially for HDF5 defined detectors. 
This implies a the search for the approximate pixel coordinate then a bilinear interpolation (in the case of a flat detector). For 3D  detector it is almost impossible.

This is equivalent to argmin(tth), i.e. search where 2th == 0.

**Comment by vallsv** [comment]
I make the Fit2D geometry editable on the geometry dialog, it could be useful sometime. Here we can edit the coord of the mean. But i have no idea if it will be useful for something.
