### ISSUE TITLE
AzimuthalIntegrator in QThread

### ISSUE THREAD

**Issue by zhujun98** [silx-kit/pyFAI#1163]
HI,

I am using pyFAI.AzimuthalIntegrator in a `QThread` and since version 0.16.0 I observed the following warning message:

```
QObject::connect: Cannot queue arguments of type 'QTextBlock'
(Make sure 'QTextBlock' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QTextCursor'
(Make sure 'QTextCursor' is registered using qRegisterMetaType().)
```
It indicates that the code is trying to access QtGui classes from a thread other than the main thread. It sometimes cause segmentation fault in my code. I did some research and the warning message appears after I instantiated an AzimuthalIntegrator object.

Do you have any idea how could this happen? Thanks a lot! 

Cheers,
Jun

**Comment by vallsv** [comment]
Hi.

Modules from `pyFAI` packages are not supposed to access to anything from `pyFAI.gui`. Then if you do not use `pyFAI.gui` you should not have access to Qt.

If you instantiate yourself an `AzimuthalIntegrator`, Qt will not be used.

We also no use any `QTextBlock` on pyFAI. Then i really have no idea of what's happening.

Did you also try the master branch?

**Comment by zhujun98** [comment]
Hi Valentin,

Thank you very much the quick response!

I just tried the master branch 0.18.0a1 and the warning is still there.

**Comment by vallsv** [comment]
I am pretty sure it is on your side.

If you don't know how to deal with Qt and threads, your `QThread` can emit signals to the main thread asynchronously (then the main thread can do the GUI part), or if your thread create `QObject` you maybe have to relocate these objects to the main thread using `setThread`. But that's general problem, i can't say much.

All i know is `AzimuthalIntegrator` do not use thread, AFAIK.

**Comment by zhujun98** [comment]
Thank you very much for the answer! My QThreads only communicate with the GUI part via signals and slots.The problem is strange and I will try to debug on my side.

As I  already said:

1. My code works find with version 0.15.0;
2. This warning message appears immediately after AzimuthalIntegrator is instantiated, i.e. if I terminate the code before the instantiation, no warning message appears. While when I terminate the code after the instantiation, the warning message appears.

I also think AzimuthalIntegrator does not need to access QtGui classes. Now you told me that it does not use thread. Maybe there is something weird happening on my side.

**Comment by vallsv** [comment]
@kif maybe have a better idea of changes since 0.15.

**Comment by zhujun98** [comment]
Indeed, the problem can be solved by replacing the following import in the QThread

```
from pyFAI import AzimuthalIntegrator
```
with
```
from pyFAI.azimuthalIntegrator import AzimuthalIntegrator
```

The reason is that in the new version of pyFAI, it has

```
@decorators.deprecated(replacement="pyFAI.azimuthalIntegrator.AzimuthalIntegrator", since_version="0.16")
def AzimuthalIntegrator(*args, **kwargs):
    from .azimuthalIntegrator import AzimuthalIntegrator
    return AzimuthalIntegrator(*args, **kwargs)
```

The secret is that the above decorator triggers logging.warning, which talks with my GUI logging window in the main thread. However, I cannot see the message in my logging window since I have the following lines in my logger file.

# disable DEBUG information from imported module pyFAI
logging.getLogger("pyFAI").setLevel(logging.CRITICAL)

**Comment by vallsv** [comment]
Interesting. Very easy to fall down there. And strange, if everything is filtered, i don't see how you could have any problem.

Could we close this issue then?

BTW, which kind of solution do you use to display logging in your GUI. I ask that cause, it could maybe fit my needs. By change is that MIT-like license?

**Comment by zhujun98** [comment]
I am using a very simple GUI logger in my code :) I should need a better one to avoid this kind of bug.

```
class GuiLogger(logging.Handler):
    def __init__(self, parent):
        super().__init__(level=logging.INFO)
        self.widget = QtGui.QPlainTextEdit(parent)

    def emit(self, record):
        self.widget.appendPlainText(self.format(record))
```
I will close this issue. Thanks!

**Comment by vallsv** [comment]
Oh, yes i expect something with more features :-)
Anyway, on silx we created `submitToQtMainThread` to do what you want.
You could write that (untested):

```
class GuiLogger(logging.Handler):
    def __init__(self, parent):
        super().__init__(level=logging.INFO)
        self.widget = QtGui.QPlainTextEdit(parent)

    def logOnTheGui(self, record):
        self.widget.appendPlainText(self.format(record))

    def emit(self, record):
        # Here, maybe record have to be cloned
        silx.gui.utils.concurrent.submitToQtMainThread(self.logOnTheGui, record)
```

Another solution is to inherite QObject from GuiLogger and use a signal. In this case it should do exactly the same thing.

**Comment by zhujun98** [comment]
Thanks a lot! :)
