### ISSUE TITLE
pyFAI-calib2 loading of poni files from command line

### ISSUE THREAD

**Issue by jangarrevoet** [silx-kit/pyFAI#1197]
Hi Valentin,
When I start it with --poni it starts but the settings do not get loaded.
When starting with -p I get the error below.
The used poni file has been created with the same version, minutes before, and is attached (changed extension to txt for github).
I compiled from master last Friday (0.18.0-dev1)
[scan_00016_lab6.txt](https://github.com/silx-kit/pyFAI/files/3073281/scan_00016_lab6.txt)

```
pyFAI-calib2 -p /gpfs/current/shared/pyFAI/scan_00016_lab6.poni 
INFO:pyFAI.method_registry:Degrading method from (pseudo,histogram,*) -> (bbox,histogram,*)
INFO:pyFAI.method_registry:Degrading method from (full,histogram,*) -> (pseudo,histogram,*)
ERROR:pyFAI-calib2:Error in reading pixel size_1
ERROR:pyFAI-calib2.UNCAUGHT:Not a valid pixel size
Traceback (most recent call last):
  File "/home/p06user/.local/bin/pyFAI-calib2", line 11, in <module>
    sys.exit(main())
  File "/home/p06user/.local/lib/python2.7/site-packages/pyFAI/app/calib2.py", line 565, in main
    setup_model(context.getCalibrationModel(), options)
  File "/home/p06user/.local/lib/python2.7/site-packages/pyFAI/app/calib2.py", line 366, in setup_model
    pixel_size = parse_pixel_size(options.pixel)
  File "/home/p06user/.local/lib/python2.7/site-packages/pyFAI/app/calib2.py", line 256, in parse_pixel_size
    raise ValueError("Not a valid pixel size")
ValueError: Not a valid pixel size
```

**Comment by vallsv** [comment]
Hi,

- `-p` is for `--pixel` that is why you receive `Not a valid pixel size`
- `--poni` is `-i`, but it is not supported right now.

What is your use case? What do you expect from the this option? Initialize the first geometry? Initialize the default wavelength? I am afraid it will have no relation with the peaks you will select.

I am working on an history of geometry, it could be part of it.

**Comment by jangarrevoet** [comment]
I should learn to read the help function :-)...
I forgot to save the mask during the calib procedure so I quickly wanted to load it with the poni since it already knows which detector,.... to save me some time. I guess others might use it when using 2 standards for calibration if they want to get 2 ranges and not having to fill out certain things.

Since I forgot to save the mask, maybe as a workflow optimisation, I assume most people will use the "next" button in the bottom right corner. Maybe at the very last step this can become a save button that prompts you to save all needed files.

**Comment by vallsv** [comment]
Yes you are right. The mask is an issue that can be fixed now.

I reopen this issue, as the poni can be read anyway.
