### ISSUE TITLE
`python setup.py build` fails (pyFAI 0.17)

### ISSUE THREAD

**Issue by deep-42-thought** [silx-kit/pyFAI#1205]
running `python setup.py build` fails with:
```compile options: '-IpyFAI/ext/src -I/usr/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c'
extra options: '-fopenmp -fvisibility=hidden -D'PyMODINIT_FUNC=__attribute__((visibility("default"))) void ' '
gcc: pyFAI/ext/_geometry.c
gcc: error: unrecognized visibility value ‘hidden -D'PyMODINIT_FUNC=__attribute__((visibility("default"))) void ' ’
gcc: note: valid arguments to ‘-fvisibility=’ are: default hidden internal protected
error: Command "gcc -pthread -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -D_FORTIFY_SOURCE=2 -fPIC -g -DNDEBUG -IpyFAI/ext/src -I/usr/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c pyFAI/ext/_geometry.c -o build/temp.linux-x86_64-2.7/pyFAI/ext/_geometry.o -fopenmp -fvisibility=hidden -D'PyMODINIT_FUNC=__attribute__((visibility("default"))) void ' " failed with exit status 1
```
This seems to work with python2, but fails with python3

Versions:
pyFAI: 0.17.0
python: 2.7.16 and 3.7.3

the exact commands:
```
  cp -r "${_pkgname}-${pkgver}" "py2-${_pkgname}-${pkgver}"
  mv "${_pkgname}-${pkgver}" "py-${_pkgname}-${pkgver}"
  cd "${srcdir}/py2-${_pkgname}-${pkgver}"
  python2 setup.py build
  cd "${srcdir}/py-${_pkgname}-${pkgver}"
  python setup.py build
```
note, that the first build succeeds, but the second one fails

**Comment by vallsv** [comment]
Hi,

I think it is about a change on `numpy.distutils`. I don't remember.

You could try to use a dev branch of pyFAI or use a numpy version < `1.16`

If you prefer to work with the tagged release 0.17, we could update the 0.17 branch. But we have to think about.

Here is the main change since: https://github.com/silx-kit/pyFAI/commit/650f4b66fc7ce519407874e836ab05d787fb2c61

**Comment by deep-42-thought** [comment]
I can confirm, that it compiles with 62a8cb838ef435302e454c2fe7f711abd5e1ba89 - I'm currently trying with the patch, you linked (I assume it will work, too) - then I will simply use the cherry-picked version :)
Thanks!

**Comment by kif** [comment]
I just released a new version of pyFAI ... it is on PyPI and on github. If this fixes your build procedure, I let you close the issue. Thanks for the contribution.

**Comment by deep-42-thought** [comment]
sry for the delay - I had some trouble applying the patch.
I just compiled 0.17.1 and it looks good.
Thank you!
