### ISSUE TITLE
Issue getting the correct 1D integration 

### ISSUE THREAD

**Issue by burkhb** [silx-kit/pyFAI#1271]
I have gone through the process with fit2d and came out with a plot that I believe is correct for my sample but the pyFAI is giving me a different plot. I have followed the directions here for version .18 with doing the setfit2d() and putting in the values for the calibration and that seemed to work fine as well as getting the file into jupyter. I am also not sure if I need the calibration CeO2 for this process or not. Would you be able to help me with where to try trouble shooting?

**Comment by kif** [comment]
Yes of course. Are you using a detector which is non regular (defined with a spline file?). This the only case where the results are expected to differ.

**Comment by burkhb** [comment]
I don’t believe so or at least I wasn’t given one, it’s a Perkin Elmer
defector.

**Comment by burkhb** [comment]
Also, is there a way to use the calibrate, such as CeO2, to automatically calibrate an image instead of getting the parameters from Fit2D?

**Comment by kif** [comment]
What do you mean by automatically ?
PyFAI features a nice calibration tool which should take <5mn for your first calibration (and less than 1 once you are used to the interface).
http://www.silx.org/doc/pyFAI/latest/usage/cookbook/calib-gui/index.html

Just change the detector name (the Perkin is parametrized), the calibrant (CeO2 is parametrized), the wavelength and it should be straight forwards as in the doc.

By any chance, is your file a tiff ? Because Fit2D does flip those files which would explain this difference of behavior.

**Comment by burkhb** [comment]
It is a tiff file but I just tried changing it to an .edf file and got the same results in Fit2D as previously and in my jupyter notebook as before (not the same between the two). When I said automatically I meant because in the tutorial for the jupyter notebook it has a section to input the parameters from Fit2D with setFit2D and I am wondering if there is a way in jupyter notebook to only put parameters such as the calibrate and distance to the detector and the code calibrates it . I tried the tool you sent and it gave me the same output as the Fit2D in a much easier way, thank you for that. My goal with this is to be able to run multiply files through a program with ease instead of using Fit2D and having to calibrate each image and then integrating them. I was hoping to do this with the jupyter notebook code but I am stuck on how since the integration is coming out incorrectly and making it easier than using the Fit2D or the calibrate tool you sent.

**Comment by kif** [comment]
Do you really need to recalibrate every single image ? I guess not, then the easiest it to follow this tutorial starting from the "poni-file" saved from the graphical interface.
http://www.silx.org/doc/pyFAI/latest/usage/cookbook/integration_with_python.html

If you really need to recalibrate every single image, it is possible but requires a more advanced knowledge of pyFAI. Look at the tutorials related to goniometer calibration where automatic ring extraction is usually done.

**Comment by burkhb** [comment]
Thank you very much! that helped alot

**Comment by kif** [comment]
PyFAI is designed to fit multiple rings.

For measuring the distance, you need to take points from at least 2 rings, The bare minimum is 5 points from one ring plus one from another ring.
It is common to work with 5 rings (dozens of points) and some people are working with hundreds of rings (thousands of points) when you wish to fit the distance and the wavelength simultaneously.
