### ISSUE TITLE
[pyCAI-calib2] --fix-poni1 does not work

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#1283]
Hello,

I am starting pyFAI-calib2 with this command line

./bootstrap.py pyFAI-calib2 -e 17.94 -c LaB6 -D Cirpad --dist 0.018975896312712265 --poni1  0.05465713891651463 --fix-poni1 --poni2 0.007615371228673724 --fix-poni2 --rot1 0 --fix-rot1 --rot2 0.1 --rot3 0 --fix-rot3 ../cirpad.edf 

Then I select a bunch of ring, and when I switch to the geometry fitting, the first automatic fit
change the value of poni1. It seems that poni1 is not really fixed during this fit.
Nevertheless, the graphical widget shows a fix poni1.

**Comment by picca** [comment]
I can reproduce the problem, when I switch from the Peak Peaking task to the geometry fit task

**Comment by kif** [comment]
This was fixed some time ago ... constrain were not honored.
