### ISSUE TITLE
[PyFAI-integrate] Unable to save propagated errors in HDF5

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#1286]
Occurs at least when using OpenCL integrator and Poisson statistics.

**Comment by rjkoch** [comment]
I'm noticing that 2d integration (`integrate2d`) does not return propagated errors in the result. Is this a known/related bug, or is it dependent on the integration method/arguments provided? 

I could provide an example if needed. The documentation suggests `integrate2d `should return propagated errors.

**Comment by kif** [comment]
On Fri, 08 Nov 2019 13:58:17 -0800
Robert J Koch <notifications@github.com> wrote:

> I'm noticing that 2d integration (`integrate2d`) does not return propagated errors in the result. Is this a known/related bug, or is it dependent on the integration method/arguments provided? 
> 
> I could provide an example if needed. The documentation suggests `integrate2d `should return propagated errors.

Could be that this is something I forgot to implement (i.e. it is a bug). I'll investigate a bit and comment.

Cheers

**Comment by rjkoch** [comment]
Nifty. Shall I make a separate issue?

Thanks for all you do! (PyFAI is great!)
Rob

**Comment by kif** [comment]
I had a quick look at the code and I can confirm you there "was" no error propagation in 2D integration, the legacy version. The options are there (for compatibility reasons) but they have no effect.
I did not implement them there as I was re-writting the whole zoo of integrators (there are dozens of them) using a different integration scheme which is more correct mathematically speaking (the difference is most of the time invisible). 

This new generation of integrators (i.e. ai._integrate2d_ng(...)) is in test for 1 year and should be part of the latest release, it is also available on the master  branch.
https://github.com/silx-kit/pyFAI/blob/master/pyFAI/azimuthalIntegrator.py#L2334

I plan to switch the default from  _legacy to _ng implementation soon, thus bug-report on the ng version are more then welcome.

**Comment by kif** [comment]
Since the new-generation integrator are now default for 2D integration (matrix only half complete!), this solves this issue.
