### ISSUE TITLE
separate

### ISSUE THREAD

**Issue by nils-blanc** [silx-kit/pyFAI#1292]
Hello,

Could it be possible to get the 1D integrated values of amorphous and cristal contributions as a separate output ? Could be optional

Best 

Nils

**Comment by kif** [comment]
Hi Nils,

Good idea. Separate is returning a "simple" tuple with brag and amorphous signal. Now in integrate?d we are returning a more complex tuple with some additional information like how this was calculated.
This is quite straight forwards.
