### ISSUE TITLE
support of mar1200

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#1295]
Hello Jerome, 

at IPANEMA, they have a mar345. When they select the 1200x1200 (180mm0 mode, the saved file have the mar1200 extension.
It would be nice to add this extension to the supported files

cheers

**Comment by kif** [comment]
On Thu, 28 Nov 2019 02:28:28 -0800
picca <notifications@github.com> wrote:

> Hello Jerome, 
> 
> at IPANEMA, they have a mar345. When they select the 1200x1200 (180mm0 mode, the saved file have the mar1200 extension.
> It would be nice to add this extension to the supported files

Hi Fred,

Is this on the fabio side or on the pyFAI side ? Apparently there is
support for a 1200pixel mode in Mar345 in pyFAI ... so for the library
it should be transparent: I don't understand your request.

Could you be more precise, thanks

Cheers,

Jerome

**Comment by picca** [comment]
Sorry,

this is just about the filter used when you open a file via pyFAI-calib2.
the .mar1200 extention is not recognise. We need to select All files in order to see this image file.
I think that marccd is ok but mar1200 is not.

Maybe a bunch of supported extension need to be added to the mar345.

I do not know how it works exactly :)

**Comment by kif** [comment]
On Thu, 28 Nov 2019 14:21:08 -0800
picca <notifications@github.com> wrote:

> I do not know how it works exactly :)

Me neither :)

grep "*.edf" pyFAI/*.py is probably a good starting point. It is likely
to be in the gui folder.

**Comment by vallsv** [comment]
You are talking about file extension? I guess it is just about adding `mar1200` in the list `DEFAULT_EXTENSIONS` from the `marccdimage.py` file.

**Comment by vallsv** [comment]
Or is that a specific format?

**Comment by picca** [comment]
Ok, I ask the guy from IPANEMA to give us all the files extensions :)

Thanks

Fred
________________________________________
De : Valentin Valls [notifications@github.com]
Envoyé : vendredi 29 novembre 2019 09:37
À : silx-kit/pyFAI
Cc : PICCA Frederic-Emmanuel; Author
Objet : Re: [silx-kit/pyFAI] support of mar1200 (#1295)

You are talking about file extension? I guess it is just about adding mar1200 in the list DEFAULT_EXTENSIONS from the marccdimage.py file.

**Comment by picca** [comment]
the format is ok, this is just the extension of the file wich is not recognize in the GUI.

**Comment by vallsv** [comment]
I ask cause `mar345` looks to be specific, there is a `mar345image.py` file.

**Comment by marouanebj** [comment]
Hi,
We have at IPANEMA a mar345 the 4 files extensions are
.mar1200 , .mar1600 , .mar2000 , .mar2300

When we open these files with pyFAI-calib2 the detector is not automatically set.
Maybe these extensions are to vague (=used for other detectors) to chose the detector.

When we chose the detector in the interface of pyFAI-calib2 it set the proper size in px.
But it does not set the pixel size:
 I do not know if it is somewhere in the scan.mar2300 file.
 Our mar345 have a resolution of 150micron but according to the documentation there is a mar345 with 100micron resolution.

Thanks,
Marouane

**Comment by kif** [comment]
I don't think the extension of the filename is used in pyFAI to guess the detector. 

One always has to provide the detector type/name then the binning (which is indeed not binning in the case of the Mar345) should be set automatically.

Mar345 have pixel size of 100 and 150µm depending on the image size as defined here:
https://github.com/silx-kit/pyFAI/blob/master/pyFAI/detectors/_rayonix.py#L498

But maybe there is an error in our code. Do you have the documentation of this detector ?

**Comment by kif** [comment]
Following Valentin's suggestion, I have added the other file extensions in FabIO. You will have to upgrade fabio after the PR is merged.

**Comment by marouanebj** [comment]
Hi Jerome,
Here after a screenshot of pyFAI-calib2 with a file with extension .mar2000.
 I selected the detector mar345 and the pixel size is not set. As I understood it should be set to 150 Microns but it is empty.

Thanks,Marouane

Docuumentation: 
The mar345 scanner is able to scan the plate using 2 pixel sizes (0.10 mm or 0.15 mm), each at 4 different radii can be chosen, so that in total 8 different image sizes can be produced:  
Pixelsize       Diameter        SIZE    File name extension 
[mm]    [mm]     
0.15    345.0   2300 * 2300     .mar2300 or .pck2300 
            300.0   2000 * 2000     .mar2000 or .pck2000 
            240.0   1600 * 1600     .mar1600 or .pck1600 
            180.0   1200 * 1200     .mar1200 or .pck1200 
0.10    345.0   3450 * 3450     .mar3450 or .pck3450 
            300.0   3000 * 3000     .mar3000 or .pck3000 
            240.0   2400 * 2400     .mar2400 or .pck2400 
            180.0   1800 * 1800     .mar1800 or .pck1800



    Le jeudi 5 décembre 2019 à 10:33:09 UTC+1, Jerome Kieffer <notifications@github.com> a écrit :  
 
 
Closed #1295.

**Comment by vallsv** [comment]
Hi,

No the change was not about feeding automatically the fields, but only to be able to load the image. Right now, if i am not wrong, if you don't use a pyFAI config file, we don't have anything to guess the pixel size from the image file.

**Comment by marouanebj** [comment]
OK thanks.

    Le mardi 10 décembre 2019 à 16:43:15 UTC+1, Valentin Valls <notifications@github.com> a écrit :  
 
 
Hi,

No the change was not about feeding automatically the fields, but only to be able to load the image. Right now, if i am not wrong, if you don't use a pyFAI config file, we don't have anything to guess the pixel size from the image file.

**Comment by kif** [comment]
Could you please tell me where you see an issue ? here are 2 images with size 1200² and 1800² and their pixel size got assigned properly.
![image](https://user-images.githubusercontent.com/1018880/70602149-09497280-1bf4-11ea-9aff-11374f48ad6c.png)
![image](https://user-images.githubusercontent.com/1018880/70602166-0fd7ea00-1bf4-11ea-878f-39a693b64a88.png)

**Comment by vallsv** [comment]
Cause you define manually the detector? Right? Or i don't remember that there is feature to guess the detector name from the filename.

**Comment by kif** [comment]
yes I do so. Mar 345 is not different from any other detector in this sense. In this example, the images were provided as numpy arrays.
