### ISSUE TITLE
massif Imin parameter accissible from the extract_cp method

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#1299]
Hello, I use extract_cp in order to extract rings from a moving detector.

If I look at the code of extract_cp, I can find this at the end

```
res = self.massif.peaks_from_area(mask2, Imin=0, keep=keep, dmin=dist_min, seed=seeds, ring=i)

```

It would help a lot if we could have acces to the Imin parameter of the peak_from_area method from extract_cp by adding an Imin parameter like this

```
    def extract_cp(self, max_rings=None, pts_per_deg=1.0, Imin=0):
        """Performs an automatic keypoint extraction and update the geometry refinement part
```

and then

```
res = self.massif.peaks_from_area(mask2, Imin=Imin, keep=keep, dmin=dist_min, seed=seeds, ring=i)

```

Cheers

Fred

**Comment by kif** [comment]
Hi Fred,

This is just wiring Imin from here:
https://github.com/silx-kit/pyFAI/blob/master/pyFAI/goniometer.py#L585
to:
https://github.com/silx-kit/pyFAI/blob/master/pyFAI/goniometer.py#L650

I see no objection. I am looking forward for your Pull-Request.

Cheers, J.

**Comment by kif** [comment]
done
