### ISSUE TITLE
[Calib2] MacOS hi-dpi issue with the widgets position and pointer position

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#1313]
While there is a work-around using the tab-navigation, this is far from intuitive.

**Comment by kif** [comment]
The marker precision is also much worse  than on other operating system (strange)

**Comment by vallsv** [comment]
Please take a screenshot. It make it much more easy to understand.

**Comment by kif** [comment]
![calib2](https://user-images.githubusercontent.com/1018880/73522398-9943b580-4408-11ea-91a0-73a71c5b6e3e.png)

**Comment by vallsv** [comment]
Looks like the screen is too small?

**Comment by kif** [comment]
I found a workaround:
[apple menu] -> [system preferences] -> [display] -> [resolution] -> scaled + more space

The issue about the position of the marker is also  related to the high-dpi of macos as for a same pixel marked, the marked position depend on the zoom level ! that's really strange

**Comment by vallsv** [comment]
It exists a `QScreen.devicePixelRatio`. This could be tested in order to fix the problem, and backport the fix to silx.

**Comment by kif** [comment]
thanks, I'll try

**Comment by kif** [comment]
Much better !
