### ISSUE TITLE
Error while running pyFAI-calib2

### ISSUE THREAD

**Issue by Mosharn82** [silx-kit/pyFAI#1327]
The module runs fine but when I try to choose a file, mask file or dark file, etc, it doesn't allow me to do so and it gives out this error in terminal 
```
ERROR:pyFAI-calib2.UNCAUGHT:Failed to disconnect signal selectionChanged(QItemSelection,QItemSelection).
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/silx/gui/dialog/AbstractDataFileDialog.py", line 1066, in __directoryLoaded
    self.__browser.setRootIndex(index, model=self.__fileModel)
  File "/opt/anaconda3/lib/python3.7/site-packages/silx/gui/dialog/AbstractDataFileDialog.py", line 362, in setRootIndex
    selectionModel.selectionChanged.disconnect()
RuntimeError: Failed to disconnect signal selectionChanged(QItemSelection,QItemSelection).
```
Am I missing something to run the module?

**Comment by vallsv** [comment]
Can you provide to use your environment?

qt version, silx version?

If you use anaconda, i guess you use PyQt5.

**Comment by vallsv** [comment]
BTW maybe we `conda list`, we could recreate on our side the same env and test.

**Comment by Mosharn82** [comment]
I am using PyQt5, PySide2 is also installed. Why wouldn't the module pyFAI-calib2 be able to open files from the computer?

**Comment by vallsv** [comment]
No idea if you do not provide enough information. Did you installed h5py? fabio? which version? better to type `conda list` to have all this dependencies.

**Comment by Mosharn82** [comment]
oh apologies, I have installed h5py, fabio and all other dependencies such as numpy, scipy, matplotlib, pyopencl, silx, numexpr. I have also upgraded them to the latest versions.

**Comment by vallsv** [comment]
What is the kind of files you want to open? `.edf`/`.h5`?

**Comment by vallsv** [comment]
BTW checking the silx code (a library we are using), there is some weird things.

**Comment by vallsv** [comment]
I create an issue in a side project. Still have to understand why it was working before. Maybe used an older PyQt can fix it, just a guess.

**Comment by Mosharn82** [comment]
> What is the kind of files you want to open? `.edf`/`.h5`?

So I am trying to use "pyFAI-calib2", in that module, I use calibrate an image ".tif" by the use of a mask ".edf" and a dark image ".tif". All of these need to be opened with the module.
Another module is "pyFAI-integrate" and other types of files need to be opened to carry out the integration.

**Comment by vallsv** [comment]
And what kind of operating system do you use?

**Comment by vallsv** [comment]
In fact that's maybe more about the kind of file system you use.

**Comment by Mosharn82** [comment]
> And what kind of operating system do you use?

I use MacOS. I run the modules from python on terminal.

**Comment by vallsv** [comment]
Which version of MacOS?

**Comment by Mosharn82** [comment]
Sierra 10.12.6

**Comment by vallsv** [comment]
I think there is 3 ways for you to set images without this problem
- You can type the path in the text input instead of using the dialog
- You can do a long press in the open icon. It should display to you other options, like using the default Qt file dialog
- Finally you can pass the path with command line options

At worst the last option works for sure.

Here you have the options https://github.com/silx-kit/pyFAI/blob/master/doc/source/man/pyFAI-calib2.rst

```
pyFAI-calib2 -d DARK_FILE -f FLAT_FILE -m MASK_FILE
```

**Comment by kif** [comment]
I suspect the case-sensitivity of the apple filesystem ...
Did Valentin's answer resolve your issues ?
