### ISSUE TITLE
New 1d integrator variance depends on binning

### ISSUE THREAD

**Issue by jbhopkins** [silx-kit/pyFAI#1333]
pyFAI: 0.18 (see #1331, 0.19 not working with new integrator)
python: 3.7.4
OS: MacOS 10.14.6
Installation method: conda (main channel and conda forge)

I've been running some variance tests based on the notebook and comments provided here:
http://www.silx.org/doc/pyFAI/latest/usage/tutorial/Variance/Variance.html

I don't know if this is an issue with the synthetic data or with the algorithm, but if you change the binning in the new pyFAI integrator the measured curve to curve chi^2 shifts slightly away from the expected distribution.

The plots below show the old and new integrator with different amounts of binning on the same data. You can see that larger bins (fewer points) flattens the measured distribution (blue) compared to the expected distribution (orange). This is with solid angle correction, but the same thing happens without the solid angle correction. This happens for both integrators. The center point seems to stay fixed in both cases.

![binning_test](https://user-images.githubusercontent.com/23534688/76651275-2adb3280-6532-11ea-87dc-fc0b9d48a578.png)

Full code to reproduce (or just change npts in the variance jupyter notebook) is below. I used 1000 points (what's in the notebook), as well as 500, and 1448 (essentially a 1 pixel bin size).

```python
import time

from scipy.stats import chi2 as chi2_dist
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
from pyFAI.detectors import Detector
from pyFAI.azimuthalIntegrator import AzimuthalIntegrator
from pyFAI.method_registry import IntegrationMethod

def chi2_curves(res1, res2):
    """Calculate the Chi2 value for a pair of integrated data"""
    I = res1.intensity
    J = res2.intensity
    l = len(I)
    assert len(J) == l
    sigma_I = res1.sigma
    sigma_J = res2.sigma
    return ((I-J)**2/(sigma_I**2+sigma_J**2)).sum()/(l-1)

def calc_distribution(ai, dataset, kwarg, integrator='new', variance='data'):
    ai.reset()
    results = []
    c2 = []
    if integrator == 'old':
        integrate = ai._integrate1d_legacy
    elif integrator == 'new':
        integrate = ai._integrate1d_ng
    elif integrator == 'default':
        integrate = ai.integrate1d
    for i in range(nimg):
        data = dataset[i, :, :]
        if variance == 'data':
            r = integrate(data, variance=data, **kwarg)
        else:
            r = integrate(data, error_model='poisson', **kwarg)
        results.append(r)
        for j in range(i):
            c2.append(chi2_curves(r, results[j]))
    c2 = np.array(c2)

    return c2


pix = 100e-6
shape = (1024, 1024)
nbins = 100
npt = 1000
nimg = 1000
wl = 1e-10
I0 = 1e4
Rg = 1.
kwarg = {"npt":npt,
         "correctSolidAngle":False,
         "polarization_factor":None,
         "safe":False}

detector = Detector(pix, pix)
detector.shape = detector.max_shape = shape

ai_init = {"dist":1.0,
           "poni1":0.0,
           "poni2":0.0,
           "rot1":0.0,
           "rot2":0.0,
           "rot3":0.0,
           "detector":detector,
           "wavelength":wl}

ai = AzimuthalIntegrator(**ai_init)

kwarg["method"] = IntegrationMethod.select_one_available("nosplit_csr", 1)

# flat = np.ones(detector.shape)
# res_flat = ai.integrate1d(flat, **kwarg)

# q = np.linspace(0, res_flat.radial.max(), npt)
# I = I0/(1+q**2)
# img_theo = ai.calcfrom1d(q, I, dim1_unit="q_nm^-1", correctSolidAngle=False,
#     polarization_factor=None)

# plt.imshow(img_theo)
# plt.show()

# dataset = np.random.poisson(img_theo, (nimg,) + img_theo.shape)
# np.save('test_chi_data.npy', dataset)

dataset = np.load('test_chi_data.npy')

kwarg = {"npt":npt,
         "method": IntegrationMethod.select_one_available("nosplit_csr", dim=1),
         "correctSolidAngle":True,
         'normalization_factor':10.,
         "safe":False}

# res = ai.integrate1d(dataset[0, :, :], **kwarg)

# plt.plot(res[1])
# plt.plot(r_iq)
# plt.show()

#Varying npt
npt = 500
kwarg['npt'] = npt

ai.reset()
ai_old_c2_500 = calc_distribution(ai, dataset, kwarg, integrator='old', variance='data')
# Azimuthal integrator, correcting solid angle
ai.reset()
ai_new_c2_500 = calc_distribution(ai, dataset, kwarg, integrator='new', variance='data')

npt = 1000
kwarg['npt'] = npt

ai.reset()
ai_old_c2_1000 = calc_distribution(ai, dataset, kwarg, integrator='old', variance='data')
# Azimuthal integrator, correcting solid angle
ai.reset()
ai_new_c2_1000 = calc_distribution(ai, dataset, kwarg, integrator='new', variance='data')

npt = 1448
kwarg['npt'] = npt

ai.reset()
ai_old_c2_1448 = calc_distribution(ai, dataset, kwarg, integrator='old', variance='data')
# Azimuthal integrator, correcting solid angle
ai.reset()
ai_new_c2_1448 = calc_distribution(ai, dataset, kwarg, integrator='new', variance='data')


plt.subplot(3, 2, 1)
h,b,_ = plt.hist(ai_old_c2_500, nbins)
y_sim = chi2_dist.pdf(b*(nimg-1), nimg)
y_sim *= h.sum()/y_sim.sum()
plt.plot(b, y_sim)
plt.title("old, 500 pts")

plt.subplot(3, 2, 2)
h,b,_ = plt.hist(ai_new_c2_500, nbins)
y_sim = chi2_dist.pdf(b*(nimg-1), nimg)
y_sim *= h.sum()/y_sim.sum()
plt.plot(b, y_sim)
plt.title("new, 500 pts")

plt.subplot(3, 2, 3)
h,b,_ = plt.hist(ai_old_c2_1000, nbins)
y_sim = chi2_dist.pdf(b*(nimg-1), nimg)
y_sim *= h.sum()/y_sim.sum()
plt.plot(b, y_sim)
plt.title("old, 1000 pts")

plt.subplot(3, 2, 4)
h,b,_ = plt.hist(ai_new_c2_1000, nbins)
y_sim = chi2_dist.pdf(b*(nimg-1), nimg)
y_sim *= h.sum()/y_sim.sum()
plt.plot(b, y_sim)
plt.title("new, 1000 pts")

plt.subplot(3, 2, 5)
h,b,_ = plt.hist(ai_old_c2_1448, nbins)
y_sim = chi2_dist.pdf(b*(nimg-1), nimg)
y_sim *= h.sum()/y_sim.sum()
plt.plot(b, y_sim)
plt.title("old, 1448 pts")

plt.subplot(3, 2, 6)
h,b,_ = plt.hist(ai_new_c2_1448, nbins)
y_sim = chi2_dist.pdf(b*(nimg-1), nimg)
y_sim *= h.sum()/y_sim.sum()
plt.plot(b, y_sim)
plt.title("new, 1448 pts")

plt.show()
```

**Comment by kif** [comment]
Hi Jesse,
Thanks for the report, I will investigate. I am neither a statistics guru. I recently read a book on stats and the chi² test was well explained. It depends on the number of bins chosen so I am not surprised  if there is an impact.. Unfortunately the book is in my office and I cannot access ESRF for the next two weeks :(

Right now I am preparing a computer to test and debug the other parts, as this tutorial needs tons of RAM which I don't have at home.
Cheers,
Jerome

**Comment by kif** [comment]
For me it is normal that the shape of the distribution depends on the number of bins you are binning in. The error is rather that the "theoretical" curve does not move, and this is clearly related to the scipy.stats.chi2 part. After re-reading the doc of the function:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.chi2.html
The number of degrees of freedom is not the number of images but the number of bins (which was accidentally the same.

**Comment by jbhopkins** [comment]
Jerome,

Yup, changing the degrees of freedom to the number of bins fixes it. See below. You might want to correct the variance notebook so no one else makes the same mistake I did.  Feel free to close this ticket.

![binning_test_fixed](https://user-images.githubusercontent.com/23534688/76980349-12d72a80-6907-11ea-96e8-b0fafc659f18.png)

**Comment by kif** [comment]
On Wed, 18 Mar 2020 15:57:09 +0000 (UTC)
jbhopkins <notifications@github.com> wrote:

> Jerome,
> 
> Yup, changing the degrees of freedom to the number of bins fixes it. See below. You might want to correct the variance notebook so no one else makes the same mistake I did.  Feel free to close this ticket.

Thanks for the confirmation.
The PR which is fixing the issues 1331 and 1333 has been merged. As you noticed, not all rebinning engines or all option have been adapted but I guess you realize the amount of work this all represents.

Cheers,
