### ISSUE TITLE
add a way to customize the documentation location

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#134]
In pyfai there is a link from the code to documentation

pyFAI-src/integrate_widget.py
-        self.help_browser = Browser("http://pyfai.readthedocs.org/en/latest/pyFAI.html")
-        self.help_browser.show()

It seems to me that the link should point to the documentaiton corresponding to the version of pyai insalled by the user, instead of the latest version.
This way the documentation is coherant with the version installed.

To my opinion, at tleas two link should be provided, one for the documentation of the version installed and one for the latest version so peoples can see the nice evolutions of the software.

For the first, it would be nice to provide a way to customize the location of the documentation from the setup.py file.

Maybe this should rely on the install path of the documentation during the build.

pyFAI-src/integrate_widget.py

if you want I can take care of this bug during my week of work on pyFAI.

Cheers

Fred

**Comment by vallsv** [comment]
In case of debian packaging, we could open the local files i guess.

**Comment by vallsv** [comment]
Hi Frederic, The PR #948 should allow you to custom the URL of the documentation.

On the file `pyFAI/gui/utils/projecturl.py` you have to patch the var `BASE_DOC_URL` with something like `"/usr/share/doc/python-pyfai/doc/html/{subpath}"`
