### ISSUE TITLE
Error when packaging pyFAI with PyInstaller

### ISSUE THREAD

**Issue by jbhopkins** [silx-kit/pyFAI#1344]
I create packaged versions of my program (https://bioxtas-raw.readthedocs.io/) using PyInstaller (https://pyinstaller.readthedocs.io/). When packaging pyFAI there's an error related to how it's searching for the resource path (there's no utils directory in the PyInstaller pyFAI package). It's an error with one line in `_get_data_path()` in `__init__.py` in `utils`.

Current code (lines 163-166 in the version I have installed):
```python
    resources = [
        os.environ.get("PYFAI_DATA"),
        data_dir,
        os.path.join(os.path.dirname(__file__), "..")]
```

It's a simple fix, you just need to make it an absolute path:
```python
resources = [
        os.environ.get("PYFAI_DATA"),
        data_dir,
        os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))]
```

I'm happy to submit this as a pull request, if you let me know what branch I should base it off of. Or if you just want to make the simple change that might be easiest.

Thanks.

Jesse

**Comment by kif** [comment]
On Fri, 03 Apr 2020 09:36:44 -0700
jbhopkins <notifications@github.com> wrote:

> I create packaged versions of my program (https://bioxtas-raw.readthedocs.io/) using PyInstaller (https://pyinstaller.readthedocs.io/). When packaging pyFAI there's an error related to how it's searching for the resource path (there's no utils directory in the PyInstaller pyFAI package). It's an error with one line in `_get_data_path()` in `__init__.py` in `utils`.
> 
> Current code (lines 163-166 in the version I have installed):
> ```python
>     resources = [
>         os.environ.get("PYFAI_DATA"),
>         data_dir,
>         os.path.join(os.path.dirname(__file__), "..")]
> ```
> 
> It's a simple fix, you just need to make it an absolute path:
> ```python
> resources = [
>         os.environ.get("PYFAI_DATA"),
>         data_dir,
>         os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))]
> ```
> 
> I'm happy to submit this as a pull request, if you let me know what branch I should base it off of. Or if you just want to make the simple change that might be easiest.

Hi Jesse,

You can make a PR on the master-branch by citing this issue. The CI will be triggered automatically.
I may ask Valentin or Fred Picca to have a look at it as they worked on this part.

Cheers,

Jerome
