### ISSUE TITLE
mask_crc reset unconditionally for "lut" method in _integrate1d_legacy

### ISSUE THREAD

**Issue by xiaoqiangwang** [silx-kit/pyFAI#1347]
See https://github.com/silx-kit/pyFAI/blob/master/pyFAI/azimuthalIntegrator.py#L1073

Is there a reason for this? This has put a huge penalty when processing multi frame images.

**Comment by kif** [comment]
On Tue, 21 Apr 2020 06:02:10 -0700
Xiaoqiang Wang <notifications@github.com> wrote:

> See https://github.com/silx-kit/pyFAI/blob/master/pyFAI/azimuthalIntegrator.py#L1073
> 
> Is there a reason for this? This has put a huge penalty when processing multi frame images.

Good point, you have probably spotted a bug.
Especially that there is no such reset in CSR part.

The only justification I can see is that this has been put in place to
work-around a missing feature ino the LUT engine, feature which is
apparently present in CSR.

I will investigate an fix this. Did you check: CSR is not impacted and
should anyway be faster.

Cheers,

Jerome

**Comment by xiaoqiangwang** [comment]
Yes. CSR shows no performance drop with mask image enabled. It seems to use 5% less time to finish the dataset.

I will switch to CSR method. Thanks.

**Comment by kif** [comment]
On Tue, 21 Apr 2020 23:29:58 -0700
Xiaoqiang Wang <notifications@github.com> wrote:

> Yes. CSR shows no performance drop with mask image enabled. It seems to use 5% less time to finish the dataset.

Great. I will nevetheless fix this...

CSR is usually faster then LUT thanks to the better structure in memory.

The only counter example I know is the distortion correction where the
memory access pattern in LUT is much more predictable then for CSR.
