### ISSUE TITLE
[multi_geometry] Error model giving values that are too low

### ISSUE THREAD

**Issue by rwalroth** [silx-kit/pyFAI#1365]
I noticed that the MultiGeometry integrate1d method is giving very small error values when using a provided error model (I have not tried it with an array of variances). Looking at the code, in line 156 of multi_geometry.py the sigma2 array is calculated as the sum of the squares of the individual variance arrays, and at the end the returned sigma array is the square root of sigma2 divided by the count. But in the individual AI objects, the returned sigma array is already being divided by the count for that AI. Isn't this in effect doing the normalization by pixel count twice? Doing some quick math it might make more sense to swap line 156:
`sigma2 += (res.sigma ** 2) / monitor`
with:
`sigma2 += ((res.count * res.sigma) ** 2) / monitor`

**Comment by kif** [comment]
Yes you are right.

**Comment by kif** [comment]
To be precise, those calculation should start from the accumulated variance which is now properly propagated with the new generation integrator. But this requires still  a lot of work at many places.
Thanks for the bug report.

**Comment by kif** [comment]
Apparently there is a bug in the auto-closing of issues... manual closing
