### ISSUE TITLE
Support for Eiger2 4M in detectors

### ISSUE THREAD

**Issue by weninc** [silx-kit/pyFAI#1375]
Hi,
I would be great to add support for the Dectris Eiger2 4M detector.
It has different shape and gaps than the Eiger 4M.
Eiger 2 4M shape is (2162, 2068)
1028 * 512 pixels per module
38 pixel vertical gap and 12 pixel horizontal gap between modules

**Comment by kif** [comment]
Hi Clemens,

I was not aware Dectris changed the size of the modules, their shape and the size of the gap between Eiger and Eiger2.
Thanks for reporting it.
