### ISSUE TITLE
Consider making logging handler configuration opt-in

### ISSUE THREAD

**Issue by danielballan** [silx-kit/pyFAI#1399]
Thanks for your work on this useful library.

We have noticed pyFAI adds handlers to the root logger in many places. To take one example:

https://github.com/silx-kit/pyFAI/blob/988f6f052a342a8a4b08e36cb0fb7f5502e3fa96/pyFAI/app/calib.py#L39

This can generate a lot of logging noise from other, unrelated libraries in the same process. We find ourselves having to clear that handler manually from the root logger after pyFAI is imported:

```py
import logging
logging.getLogger().handler.clear()  # Remove any handlers from the 'root' logger.
```

This makes pyFAI perhaps _more_ quiet than we want, and it has the possibility of accidentally clearing some 'root' logger that another part of the program is using. In short, it's a heavy-handed workaround. Would you consider an alternative approach to logging to make it easier for us to target pyFAI logs selectively? I'll suggest two possibilities, which could be adopted separately or together.

1. Add handlers specifically to `pyFAI` loggers, as in:

   ```py
   def configure_pyFAI_logging():
       logger = logging.getLogger('pyFAI')
       handler = logging.StreamHandler()
       logger.addHandler(handler)
   ```

   (For a more feature-complete example of a library-specific logging configuration function, this might be interesting: https://github.com/caproto/caproto/blob/master/caproto/_log.py#L353)

2. Adding logging configuration could become opt in. That is, `configure_pyFAI_logging` might _not_ be called at import time. The Python documentation recommends this.

   > It is strongly advised that you do not add any handlers other than NullHandler to your library’s loggers. This is because the configuration of handlers is the prerogative of the application developer who uses your library. The application developer knows their target audience and what handlers are most appropriate for their application: if you add handlers ‘under the hood’, you might well interfere with their ability to carry out unit tests and deliver logs which suit their requirements.

   Source: https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library

   I am not sure whether pyFAI considers itself a library intended to be used inside other applications (like IPython) or an application, so depending on your point of view on this the recommendation from the Python documentation may or may not apply. In caproto and bluesky development, we have followed this same progression, at first automatically configuring logging handlers at import time for "convenience" and then backing away from that once we discovered the unintended consequences and learned of Python's documented recommendation.

In any case, even (1) alone --- targeting any handlers added to loggers whose names begin with `pyFAI.*` --- would go a long way toward making it easier to control the flow of logging messages.

cc @DanOlds @gwbischof

**Comment by kif** [comment]
Hi,

I totally agree about the fact that a library should not initialize the root logger, and that this is the prerogative of the application.
So maybe there is a bug in our implementation.

I did a quick search and `logging.basicConfig` is called in:
 * Every application: indeed the pyFAI.app sub-module contains the code specific to all applications. This part of pyFAI should not be imported. Are you doing `from pyFAI import *` (I never tried, and suspect side effects are possible !)  
 * `pyFAI.__init__`  but only when it detects it runs in interactive mode (ipython, ...)

So for the first case (applications), you should not import application code, you should not import anything from `pyFAI.app`. 
Most of applications implement work-around for missing libraries which needs to be logged to help the user in debugging.

I suspect the logger get initialized by:
```
import sys
import logging
if "ps1" in dir(sys):
    logging.basicConfig()
```
Are you using pyFAI as part of an interactive environment or is your code wrongly detected as interactive ?

**Comment by kif** [comment]
Just a quick demo:
```
$ python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyFAI,logging;print(logging.root.handlers)
[<StreamHandler <stderr> (NOTSET)>]
```
PyFAI detected an interactive environment and initialized the logger as expected. Now the same in non-interactive mode:
```
python -c 'import pyFAI,logging;print(logging.root.handlers)'
```
And finally, the same when importing the code for an application:
```
python -c 'import pyFAI.app.saxs,logging;print(logging.root.handlers)'
No handlers could be found for logger "fabio.fabioformats"
WARNING:hdf5plugin:lz4 filter already loaded, skip it.
INFO:pyFAI.method_registry:Degrading method from _(dim=1, split='pseudo', algo='histogram', impl='*', target=None) -> _(dim=1, split='bbox', algo='histogram', impl='*', target=None)
INFO:pyFAI.method_registry:Degrading method from _(dim=2, split='full', algo='histogram', impl='*', target=None) -> _(dim=2, split='pseudo', algo='histogram', impl='*', target=None)
[<logging.StreamHandler object at 0x7f4d86bf5990>]

```

**Comment by vallsv** [comment]
I am sorry, but as the package `app` inform. This scripts are application, not library. So yes, this application setup the logging. Which is totally normal.

**Comment by danielballan** [comment]
Thanks for your prompt responses.

@vallsv Your statement is terse but fair. The example I cited from `pyFAI/pyFAI/app/calib.py` was too hastily chosen and poorly considered. Fortunately, @kif has honed in on the issue more precisely. The logger I am seeing is actually getting activated from:

```py
import sys
import logging
if "ps1" in dir(sys):
    logging.basicConfig()
```

Yes, this demo is precisely the issue. (We happen to be using IPython rather than Python, but the same principle applies.)

```
$ python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyFAI,logging;print(logging.root.handlers)
[<StreamHandler <stderr> (NOTSET)>]
```

This will make _all_ libraries imported in this interactive session noisy. We import PyFAI alongside many other libraries. Could PyFAI instead add a handler to a `'PyFAI'` logger (or whichever name makes sense) rather than the root logger --- i.e. my suggestion (1)?

My personal view is that libraries should not automatically add handlers to their loggers even when they detect that they are in an interactive session. It may be that PyFAI is just one part of what is being done in that session, and it would be better to make this opt in as in along the lines of my suggestion (2). (Again, we went through the same progression on projects that I work on.) But if that is not persuasive to you, (1) would be enough to solve our issue and let us avoid our current workaround.

**Comment by kif** [comment]
We have missed several deprecation warning from `h5py`, `numpy` and other project due to never activating the logging.
This is why we activate logging in interactive mode. You consider it is a bug, we consider it is a feature, we don't have to agree on this  :-)

I don't think that activating a specific logger for pyFAI would help as it will silent warnings from other libraries.

One solution I see is that we agree on an environment variable, for example `PYFAI_NO_LOGGING`, for bypassing the activation of the logging module:
```
import os
import sys 
import logging 
if "ps1" in dir(sys) and not (bool(os.environ.get("PYFAI_NO_LOGGING"))): 
     logging.basicConfig() 
```
But I don't think this is very elegant.

Another solution is maybe that you initialize logging the way _you_ want prior to importing pyFAI.  
According to: https://docs.python.org/3/library/logging.html#logging.basicConfig
If the logging module is already initialized, `logging.basicConfig()` will do nothing.

Maybe this is the best solution.

**Comment by danielballan** [comment]
OK, I think we understand one another’s point of view. I will think of PyFAI as an application that, when used as a library, mutates interactive applications’ global state at import time. If every library did this it would create a race whereby import order determines whose handlers “win”, which I imagine is why the docs advise against it, but I can appreciate the pragmatism of this approach for certain use cases.

We will add a `NullHandler` to the root logger before importing PyFAI. This is a good suggestion, certainly better than our current workaround. Thanks!

**Comment by tacaswell** [comment]
The core of the problem (and the inelegance) is trying to infer user intent to control import time behavior based on information that is only loosely coupled to that intent.  (We tried something similar in Matplotlib as well and ended up reverting it almost immediately as it was super brittle).  Using an ENV is the only way to give users a path to opt-out of the heuristics (as anything else will be too late), the elegant solution is what @danielballan suggested as 1. above, but if that is not an option, the ENV is the next best thing.

On the warning front, in Matplotlib we run the tests on travis setting all warnings to be errors which is a more effective way to catch that sort of thing. However, I think the warnings are orthogonal to the logging issues as neither h5py nor numpy use the logging framework to provide deprecation warnings.

**Comment by danielballan** [comment]
Thanks for the env var, all.
