### ISSUE TITLE
Lorentz corrections done by PyFAI

### ISSUE THREAD

**Issue by azkhadiev** [silx-kit/pyFAI#1414]
I guess, that somebody has asked the question about the Lorentz corrections in 1D plots after PyFAI integration. 
 As far as I know there are three types of Lorentz corrections that should be applied on "classic" data achieved by Diffractometers with 0D detector to get the right values of Intensities:

1. L1 = 1/(E**3 * sin(2*theta)
2. L2 = cos(theta)
3. L3 = 1/sin(2*theta)

Total Lorenzt factor is L1*L2*L3

Looks like, due to geometrical reasons, that L2 and L3 corrections are already applied in PyFAI if solid-angle correction is ON. Is it true? I am also not sure about the first one - L1. Do you have any information about that? I guess, that the people that do Rietveld refinement should know the right answer.

**Comment by kif** [comment]
PyFAI performs solid angle correction by default, which is described here: 
https://github.com/silx-kit/pyFAI/blob/master/pyFAI/geometry.py#L1124
There is no assumption that the incidence angle is equal to 2theta.

This looks like the L1*L3 term (1/E³). The L2 term tells nothing to me.

**Comment by azkhadiev** [comment]
Maybe you have some feedback from the people who do Reiveld refinement? I suppose, they face similar problems.

**Comment by kif** [comment]
I remember we had some discussion on this kind of correction when preparing this publication:
https://scripts.iucr.org/cgi-bin/paper?he5639
Nota:  The solid angle formula was just corrected at that time (fall 2013) and the SNBL team validated that the implementation was correct.

Are you working with a conventional source or a synchrotron light source ? are you dealing with polarization ?

**Comment by azkhadiev** [comment]
Thank you for your answer. I will read this article.
I am working on the synchrotron source. We do powder diffraction and correct 2D images by polarization. I correct the polarization by PyFAI. The difficult thing is that we change the energy during measurement, so L1 can also have an influence.

**Comment by kif** [comment]
In the latest paper from Bob Von Dreele, https://scripts.iucr.org/cgi-bin/paper?te5065,
He mentions that "most" Rietveld programs expects signal coming with a polarization of zero (~circular), while pyFAI corrects it to have no polarization effect. Have you tried to multiply your signal with (1+cos²(2theta) /2) ?

**Comment by azkhadiev** [comment]
Dear kif,

Thank you for the suggestion. For me, it was necessary to get intensities free of any distortions from geometry, polarization, etc. After discussing with Wout De Nolf and reading his PhD thesis (http://dx.doi.org/10067/1109100151162165141) I have found that after azimuthal integration one has to apply the following Lorentz correction:

L = 1/(E**3*sin(theta)*sin(2*theta))

After trying this with my data achieved on LaB6 powder and comparing corrected data with theoretical intensities, such correction seems to be reasonable.
I have also found a similar form of Lorentz correction in the old book by Guinier
"X-ray Diffraction in Crystals, Imperfect Crystals, and Amorphous Bodies"

**Comment by VolodymyrSvitlyk** [comment]
Fullprof has some integrated features to  account for polarization:
1. Ilo (Lorentz and polarization corrections). For synchrotron radiation, for instance, Ilo = 3. 
2.  If necessary, value of Rpolarz (polarization factor) can be manually adjusted. Additionally, monochromator polarisation correction (Cthm) can be introduced. Check Fullprof manual for more details.

**Comment by kif** [comment]
Thanks Volodymyr for this input ... I believe that with this contribution, one can close this issue. 
I understand better why some people are doing Rietveld analysis without issue and some are facing polarization issues.
