### ISSUE TITLE
Issue with debian packaging and sparsify-Bragg

### ISSUE THREAD

**Issue by t20100** [silx-kit/pyFAI#1423]
There is an issue with debian packaging and `sparsify-Bragg` (see https://gitlab.esrf.fr/silx/bob/pyfai/-/jobs/154088).
`sparsify-Bragg` requires pyopencl which is not in the `Build-Depends` and not in the `python3-pyfai` dependencies.

One solution is to add `pyopencl` as a dependency (but it can cause some issues, e.g., on ppc64le), the other is to make OpenCL optional when running `sparsify-Bragg --help`.
What do you think?

**Comment by kif** [comment]
> One solution is to add `pyopencl` as a dependency (but it can cause some issues, e.g., on ppc64le), the other is to make OpenCL optional when running `sparsify-Bragg --help`.
> What do you think?

I guess the best would be to avoid having pyopencl as a build-dep ...
I'll patch the script to ba able to call the help without opencl.

Thanks for the report.

**Comment by t20100** [comment]
I'm reopening it, since PR #1425 doesn't seems to have fixed the issue: https://gitlab.esrf.fr/silx/bob/pyfai/-/jobs/155133
It just bump the line number it breaks:
`  File "/builds/silx/bob/pyfai/pyFAI-0.20.0a0/build/debian9/pyFAI-0.20.0a0/build/lib.linux-x86_64-3.5/pyFAI/app/sparsify.py", line` ~~68~~ **69** `, in <module>`
`    from ..opencl.peak_finder import OCL_PeakFinder`
