### ISSUE TITLE
test failed with the debian package

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#143]
Here the output of the test when I try to buils the pyfai package.

running test
WARNING:fabioimage:PIL is not installed ... trying to do without
WARNING:tifimage:PIL is not installed ... trying to do without
WARNING:bruker100image:PIL is not installed ... trying to do without
WARNING:pyFAI.opencl:Unable to import pyOpenCl. Please install it from: http://pypi.python.org/pypi/pyopencl
WARNING:pyFAI.azimuthalIntegrator:Unable to import pyFAI.ocl_azim
ERROR:pyFAI.azimuthalIntegrator:Unable to import pyFAI.ocl_azim_lut for Look-up table based azimuthal integration on GPU
ERROR:pyFAI.azimuthalIntegrator:Unable to import pyFAI.ocl_azim_csr: pyopencl is not installed
WARNING:pyFAI.splitBBoxCSR:Pixel splitting desactivated !
WARNING:pyFAI.splitBBoxCSR:Pixel splitting desactivated !
WARNING:test_openCL:OpenCL module (pyopencl) is not present, skip tests. No module named pyopencl.
WARNING:pyFAI.azimuthalIntegrator:pyFAI.histogram is not available, falling back on numpy
WARNING:pyFAI.splitBBoxCSR:Pixel splitting desactivated !
WARNING:test_openCL:OpenCL module (pyopencl) is not present, skip tests
...WARNING:test_histogram:pixel count difference numpy/csr : max delta=8.0
WARNING:test_histogram:Intensity count difference numpy/csr : max delta=0.44450767539
......FWARNING:pyFAI.azimuthalIntegrator:pyFAI.histogram is not available, falling back on old numpy method !
...WARNING:pyFAI.azimuthalIntegrator:pyFAI.histogram is not available, falling back on old numpy method !
...................................................................WARNING:pyFAI.azimuthalIntegrator:Look-up table implementation not available: falling back on old method !
WARNING:pyFAI.azimuthalIntegrator:Look-up table implementation not available: falling back on old method !
WARNING:pyFAI.azimuthalIntegrator:Look-up table implementation not available: falling back on old method !
.........WARNING:pyFAI.geometry:Rotation conversion from pyFAI to SPD is not yet implemented
.....WARNING:pyFAI.azimuthalIntegrator:pyFAI.histogram is not available, falling back on numpy
.WARNING:pyFAI.azimuthalIntegrator:pyFAI.histogram is not available, falling back on numpy
.WARNING:pyFAI.azimuthalIntegrator:pyFAI.histogram is not available, falling back on numpy
.WARNING:pyFAI.azimuthalIntegrator:Cython histogram is not available; falling back on numpy histogram
.WARNING:pyFAI.azimuthalIntegrator:Cython histogram is not available; falling back on numpy histogram
.WARNING:pyFAI.azimuthalIntegrator:Cython histogram is not available; falling back on numpy histogram
...WARNING:pyFAI._distortion:Patching image as image is 2048x1024 and spline is 2048x1025
..WARNING:pyFAI.azimuthalIntegrator:pyFAI.histogram is not available, falling back on numpy
WARNING:pyFAI.azimuthalIntegrator:pyFAI.histogram is not available, falling back on old numpy method !
F.WARNING:pyFAI.azimuthalIntegrator:Cython histogram is not available; falling back on numpy histogram
debian/rules:25: recipe for target 'override_dh_auto_test' failed
make[1]: **\* [override_dh_auto_test] Error 247

**Comment by vallsv** [comment]
Is that something we can close?

**Comment by vallsv** [comment]
I close it. That's so old.
