### ISSUE TITLE
Energy/wavelength of test files

### ISSUE THREAD

**Issue by loichuder** [silx-kit/pyFAI#1473]
Sorry if it is a dumb question...

I am using the `Pilatus1M.edf` and its associated PONI from http://www.silx.org/pub/pyFAI/testimages/ to test my pyFAI notebook. The PONI is missing the `Wavelength` field.

Is there a way to know at which energy/wavelength the image has been acquired to complete this information ?

**Comment by kif** [comment]
> Is there a way to know at which energy/wavelength the image has been acquired to complete this information ?

The wavelength is about 1e10m for this file, or one can use pyFAI-calib2 to retrieve the energy/wavelength,
which gives 1.032222634095911e-10 m.

**Comment by loichuder** [comment]
Thanks ! :+1:
