### ISSUE TITLE
pip/pypi is broken for python2 users

### ISSUE THREAD

**Issue by jonwright** [silx-kit/pyFAI#1503]
I am trying to clean up some requirements to get my own code to be pip installable. For fabio, the same issue was fixed here: https://github.com/silx-kit/fabio/pull/382

For now, I can attempt to work around by doing something like this (pep 508?) :
```
pyFAI <= 0.18.0 ; python_version  < 3
pyFAI ; python_version >= 3
```
I created this issue in case someone else runs into the same problem or can offer a better workaround. It is not clear whether it is worthwhile to try to fix it now?

**Comment by kif** [comment]
Fixing it is on the way... but it won't have any effect before next release.
