### ISSUE TITLE
fabio_viewer cannot load nxs file

### ISSUE THREAD

**Issue by phlpphns** [silx-kit/pyFAI#1506]
I have a dataset containing many images in different positions for detector calibration (LaB6) in .nxs format. It contains 81 images. The dataset was recorded at Soleil synchrotron.
- I cannot explore the dataset with fabio_viewer with file->open->hdf5 data series.
- I could import them as image(s) if I set the properties manually fhough. But then only one image is shown.
- pyfai-calib2 can open it though.

The error fabio gives is:

```
Traceback (most recent call last):
  File "/home/philipp/miniconda3/envs/pyfai/lib/python3.9/site-packages/fabio/app/viewer.py", line 222, in open_h5_data_series
	entry = nxs.get_entries()[0]
IndexError: list index out of range
Aborted (core dumped)
```

I am able to access and plot the image arrays with a script
```
nxs_file = "/home/philipp/Downloads/LaB6/nxs/scan_0494_0001.nxs"

print(h5.keys())
print(h5.get('scan_0494').keys())
print(h5.get('scan_0494').get('scan_data').keys())
h5.get('scan_0494').get('scan_data').get('data_06')

h5 = h5py.File(nxs_file, mode="r")
work = h5.get('scan_0494').get('scan_data').get('data_06')
for image in work[::20]:
    plt.figure(figsize=(15, 7.5))
    plt.imshow(image)             # Display as an image
    #plt.show()
```
giving the following output and some images

    <KeysViewHDF5 ['scan_0494']>
    <KeysViewHDF5 ['DIFFABS', 'User', 'duration', 'end_time', 'proposal_number', 'proposal_title', 'run_cycle', 'scan_config', 'scan_data', 'start_time']>
    <KeysViewHDF5 ['actuator_1_1', 'data_01', 'data_02', 'data_03', 'data_04', 'data_05', 'data_06', 'data_07', 'integration_times', 'sensors_rel_timestamps', 'sensors_timestamps', 'trajectory_1_1']>

It happens in a freshly created environment, installed by invoking

    conda create -n pyfai pyfai -c conda-forge

I asked my partner if I am allowed to transmit the image it needed.

**Comment by kif** [comment]
Hi  Philipp,

The tool `fabio_viewer` is now deprecated and will be dropped with Qt4 (i.e. soon). If pyFAI is installed, you can directly use `silx view` (in 2 words) as replacement of `fabio_viewer`.

Cheers,

Jerome

**Comment by phlpphns** [comment]
Thanks Jérôme !

_________________
Philipp Hans, PhD

. co-chair of the ECA general interest group GIG01 "Young crystallographers"
https://ecanews.org/groups/gig-01-young-crystallographers/


Jerome Kieffer ***@***.***> schrieb am Mo., 26. Apr. 2021,
17:24:

**Comment by phlpphns** [comment]
A short follow-up question:
Is it then true that we should not use

    import fabio

anymore? It is for example still done in

_Multi-geometry azimuthal integration_
http://www.silx.org/doc/pyFAI/latest/usage/tutorial/multi-geometry.html

**Comment by vallsv** [comment]
Hi. `fabio viewer` only is deprecated. `fabio` as file reader will still be available.

**Comment by kif** [comment]
Can I close this ?

**Comment by phlpphns** [comment]
I think yes.

I see now that fabio_viewer is deprecated but fabio can be used further on.

Should I have closed the issue myself?

Philipp


_________________
Philipp Hans, PhD

. co-chair of the ECA general interest group GIG01 "Young crystallographers"
https://ecanews.org/groups/gig-01-young-crystallographers/


Jerome Kieffer ***@***.***> schrieb am Fr., 7. Mai 2021,
10:32:
