### ISSUE TITLE
Absorption correction on 'caked' images followed by 1d integration

### ISSUE THREAD

**Issue by azkhadiev** [silx-kit/pyFAI#1509]
Dear colleagues,

In reflection geometry, the absorption correction for 2D XRD patterns depends both on the azimuthal angle (chi angle in pyFAI notation) and 2theta angle, please see 'Two-dimensional X-ray diffraction, ' by Bob He ('Lorentz, Polarization, and Absorption corrections' section). It is a bit different from 1d diffractometer corrections because in 1d diffractometer the scan is going within a very narrow chi range and such chi-dependence is usually neglected.  
To do it correctly on 2D images one should consider both chi and 2theta angles. My first idea is to 'cake' the 2D detector image first to get an array of points with known chi and 2theta coordinates, make an absorption correction on it using known chi and 2theta values of each pixel, and then integrate the caked image to make 1d diffraction pattern. Would it be possible to do this somehow with the current capabilities of PyFAI? 
The second idea was to produce the correction array with the same size as a detector image, that could be used to correct initial detector data and then perform 1d integration. To make such a correction array I would need the chi and 2theta angle of every pixel on the detector. Does PyFAI have such a function? The function could take a poni file and array size as an input.

Thank you for your time and consideration.

**Comment by azkhadiev** [comment]
I have found twoThetaArray() and chiArray() functions that can produce an array of the angles for every pixel in the detector image for a given poni file. Probably the question is closed.

**Comment by kif** [comment]
Just for your information:
Absorption correction is not performed by default in pyFAI (in high-energy synchrotrons, his is often neglected) but I started to wire things to have such correction properly performed, numerically speaking.
See equation (1) from https://journals.iucr.org/s/issues/2020/02/00/gy5006/

Absorption correction should be applied as a normalization array, of the size of the image.
