### ISSUE TITLE
pyFAI-calib2 does not run on mac with anaconda

### ISSUE THREAD

**Issue by akhko** [silx-kit/pyFAI#1534]
Hi 

pyFAI-calib2 does not launch on my mac after installing Anaconda and pyFAI.

- macbook air M1 2020 (macOS big sur 11.3) 
- Anaconda installed (conda 4.10.3)
- Python 3.8.10
- pyfai is successfully installed with "conda install -c conda-forge pyfai "
- I get following error message after typing "pyFAI-calib2" on terminal.

>  (base) akihiko@Akihikos-MacBook-Air ~ % pyFAI-calib2                       
> Traceback (most recent call last):
>   File "/Users/akihiko/opt/anaconda3/bin/pyFAI-calib2", line 11, in <module>
>     sys.exit(main())
>   File "/Users/akihiko/opt/anaconda3/lib/python3.8/site-packages/pyFAI/app/calib2.py", line 572, in main
>     import silx.gui.plot.matplotlib
>   File "/Users/akihiko/opt/anaconda3/lib/python3.8/site-packages/silx/gui/plot/__init__.py", line 63, in <module>
>     from .PlotWidget import PlotWidget  # noqa
>   File "/Users/akihiko/opt/anaconda3/lib/python3.8/site-packages/silx/gui/plot/PlotWidget.py", line 55, in <module>
>     from . import matplotlib
>   File "/Users/akihiko/opt/anaconda3/lib/python3.8/site-packages/silx/gui/plot/matplotlib/__init__.py", line 67, in <module>
>     _matplotlib_use('Qt5Agg', warn=True, force=False)
>   File "/Users/akihiko/opt/anaconda3/lib/python3.8/site-packages/silx/gui/plot/matplotlib/__init__.py", line 59, in _matplotlib_use
>     matplotlib.use(backend, warn=warn, force=force)
> TypeError: use() got an unexpected keyword argument 'warn'

This reproduces on an Intel macbook 12 inch.
On a windows10 machine, pyFAI-calib2 beautifully works above similar installation of pyFAI and Anaconda.
I hope it also works on mac.

**Comment by vallsv** [comment]
Hi,

I think it is an issue with too old `matplotlib` and too recent `silx`.

Could you check the version of such lib?

Did  you tried to update silx and matplotlib?

**Comment by akhko** [comment]
I have updated all packages using "conda update --all".
I checked versions using "conda list".

- matplotlib 3.3.4
- silx 0.12.0

**Comment by vallsv** [comment]
The problem was fixed here: https://github.com/silx-kit/silx/pull/2890

Basically
- If you use `silx < 0.14` you have to use `matplotlib < 3.3`
- If you use `silx >= 0.14` you can use `matplotlib > 3.3` and probably `matplotlib < 3.3`

So you still have the choice of downgrading matplotlib where you use silx 0.12

**Comment by akhko** [comment]
`pyFAI-calib2` launches nicely now, after I downgrade matplotlib by using `conda install -c conda-forge matplotlib==3.2.2`.

Thank you so much.
