### ISSUE TITLE
sg.get_ai() got unexpected keyword argument when using custom detector

### ISSUE THREAD

**Issue by daviddoji** [silx-kit/pyFAI#1536]
I'm trying to setup a notebook to do the calibration based on the tutorial from [https://pyfai.readthedocs.io/en/master/usage/tutorial/Recalib/Recalib_notebook.html](url) using pyFAI `0.19`

At European XFEL, we are using custom detectors that are not yet in the database of pyFAI. They are defined as it's done in the GUI, meaning, with the pixel size and the shape:
![image](https://user-images.githubusercontent.com/4411314/127357507-f59d09d5-2411-4ad6-b374-80bf8764ebc1.png)

I'm able to go through the tutorial and extract several rings using the guessed initial conditions defined previously, but when I try to refine the geometry I'm getting the following error:
![image](https://user-images.githubusercontent.com/4411314/127355527-806b2d18-c496-4a71-a587-1d0a4a10ed42.png)

The single geometry object seems to be correct:
![image](https://user-images.githubusercontent.com/4411314/127355739-57377042-0293-4d32-9f1a-a62d378f9678.png)

The detector used in the tutorial (Pilatus 1M) works as expected with the `0.19` version and the geometry can be refined.

@takluyver 

Edit: I made it work by commenting the line where one pass the `max_shape` argument to the `OrderedDict` object in the `getPyFAI` method of the `Detector` class from the `_common.py` module, as this argument is wipe out anyway when creating the `SingleGeometry` object from the `goniometer` module

**Comment by kif** [comment]
Hi David, hi Thomas,

Thanks for reporting the bug. 
I will first try to provide you with a work-around: save the detector to disk and re-load it
```
detector0 = pyFAI.detectors.Detector(5e-4, 5e-4, max_shape=(190,1092))
detector0.save("detector.h5")
detector = pyFAI.detector_factory("detector.h5")
print(detector)
```
That said, I see two ways to fix the bug: modify the signature of the constructor of `AzimuthalIntegrator` (which contains already far too much legacy!) or use and alternative constructor like `setPyFAI` ... but it needs to be adapted.

I will investigate the second path. Anyway `setPyFAI` should always accept the description from `getPyFAI`. The camel-case style is  also legacy.

**Comment by daviddoji** [comment]
Thanks @kif for the quick fix!
