### ISSUE TITLE
problem with integrate_radial with csr_ocl

### ISSUE THREAD

**Issue by malte-storm** [silx-kit/pyFAI#1602]
Hi, 
I tried to run a radial integration with the csl_ocl method and I get the following error:
```
  File "<ipython-input-32-af49e0b0ffe6>", line 1, in <module>
    res = ai.integrate_radial(raw, 36, method='csr_ocl')

  File "C:\Program_writable\Anaconda3\envs\pydidas\lib\site-packages\pyFAI\azimuthalIntegrator.py", line 1617, in integrate_radial
    intensity[count == 0] = empty

TypeError: 'numpy.float32' object does not support item assignment
```
Using for example csl works fine. I checked the type and shape of the sum_ and count variables (lines 1612/1613) and they are 
sum with CSR_OCL: ```<class 'numpy.float32'>```
count with CSR_OCL: ```<class 'numpy.float32'>```
sum with CSR: ```<class 'numpy.ndarray'>```
count with CSR: ```<class 'numpy.ndarray'>```

and when I check the shapes of the res.sum and res.count from the integrate2d, they are
with CSR:
res.count.shape (36, 100)
res.sum.shape (36, 100)

and with CSR_OCL
res_ocl.count.shape (3600,)
res_ocl.sum.shape (3600,)

The same is true for LUT and LUT_OCL. The sum over axis -1 then yields a float for the _OCL methods which raises the TypeError.

I would assume this behaviour is a bug? I could reproduce the problem in Windows and Linux. I have looked through the list of the open issues and (judging by name) think this issue has not yet been reported.

**Comment by kif** [comment]
Thanks for the report. I hardly ever use `integrate_radial` ... but if you found the bug, it means it is used somewhere.
There is a patch that solves the issue by switching to the new type of integrator which are better tested and provide consistent error propagation. 

Nota: method kwarg can now be provided as a 3-tuple containing the pixel splitting scheme, the algorithm and the implementation like ("no", "histogram", "python") or ("bbox", "lut", "cython) and ("full", "csr", "opencl"). I believe it is more readable. Compatibility with former string is of course maintained.
