### ISSUE TITLE
Change output directory in pyFAI-integrate GUI

### ISSUE THREAD

**Issue by aconceicao** [silx-kit/pyFAI#1611]
Hi,
I am using the pyFAI-integrate to process my data. However, I'm not able to select a different output directory for batch processing. Can anyone help me with that?
Thank you

**Comment by kif** [comment]
Are you using it in GUI mode or without the Qt interface ?

**Comment by aconceicao** [comment]
Hi Jérôme,

I am using the GUI mode

**Comment by aconceicao** [comment]
In the command line mode (pyFAi-integrate --no-gui) although I can select the output folder I cannot change the format. For me always save as .dat even I've tried -f h5 or -f hdf5. Could you tell me the proper commando I should use to have the output data in hdf5 format?

**Comment by kif** [comment]
Even if you use the GUI, the `--output` keyword argument should allow you to save at a different place (I just tested).

About the export of the integrated data in HDF5, I have to admit that this feature has nicely been hidden by Valentin. Try:
`pyFAI-integrate --ouput /path/to/file.h5::entry`
and it should work. Apparently the format keyword is not used ... I will mark it as deprecated.

**Comment by kif** [comment]
Format argument implemented as #1614 to enforce HDF5 file writing.
