### ISSUE TITLE
0.21 failure with i386 and python 3.10 on Debian

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#1627]
Hello Jerome,

I integrated pyfai in Debian and got this FTBFS on the i386 architecture

https://buildd.debian.org/status/fetch.php?pkg=pyfai&arch=i386&ver=0.21.0%2Bdfsg1-1&stamp=1642683048&raw=0

for the 3.10 version of Python

```
======================================================================
FAIL: test_count_csr (pyFAI.test.test_histogram.TestHistogram2d)
Test that the pixel count and the total intensity is conserved
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10_pyfai/build/pyFAI/test/test_histogram.py", line 337, in test_count_csr
    self.assertTrue(delta == 0, msg="check all pixels were counted")
AssertionError: False is not true : check all pixels were counted

======================================================================
FAIL: test_numpy_vs_cython_vs_csr_2d (pyFAI.test.test_histogram.TestHistogram2d)
Compare numpy histogram with cython simple implementation
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10_pyfai/build/pyFAI/test/test_histogram.py", line 370, in test_numpy_vs_cython_vs_csr_2d
    self.assertTrue(delta_max <= self.err_max_cnt, "pixel count difference numpy/csr : max delta=%s" % delta_max)
AssertionError: False is not true : pixel count difference numpy/csr : max delta=8.0

======================================================================
FAIL: test_2d_nosplit (pyFAI.test.test_csr.TestCSR)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10_pyfai/build/pyFAI/test/test_csr.py", line 193, in test_2d_nosplit
    self.assertLess(error.mean(), 1e-3, "img are almost the same")
AssertionError: 244.15215998872887 not less than 0.001 : img are almost the same
```

```
Ran 289 tests in 72.345s

FAILED (failures=3, skipped=78)
```

but with python 3.9, I got this

```
Ran 289 tests in 75.628s

OK (skipped=78)
```

**Comment by kif** [comment]
Hi Fred,

Thanks for the report, this is only half a surprise to me since we don't test on i386.
To me, i386 is less important than armv7 since the x87 fpu does not follow the ieee754 specification for floating point operations.
I see 2 options:
1) drop i386, on the debian side.
2) Skip those 3 tests on this platform.

With Popcon, do you have an idea of how many of the 120 installation of pyFAI on debian computer, how many of them are on an i386 ?

IIRC, you are one of the very last person using such computer, so could you please recompile the package, enforcing the compiler to use the "SSE" unit instead of the x87 fpu. This is obtained by passing the  `-mfpmath=sse` option to the compiler on this platform (default for amd64). If the bug persists, it means it is probably an overflow of a pointer but this would be strange.

**Comment by picca** [comment]
Hello Jerome

----- Jerome Kieffer ***@***.***> a écrit :
> Hi Fred,
> 
> Thanks for the report, this is only half a surprise to me since we don't test on i386.
> To me, i386 is less important than armv7 since the x87 fpu does not follow the ieee754 specification for floating point operations.
> I see 2 options:
> 1) drop i386, on the debian side.
> 2) Skip those 3 tests on this platform.

If it does not work on i386, maybe it is time to remove pyfai on this i386 architecture.

> 
> With Popcon, do you have an idea of how many of the 120 installation of pyFAI on debian computer, how many of them are on an i386 ?
> 
> IIRC, you are one of the very last person using such computer, so could you please recompile the package, enforcing the compiler to use the "SSE" unit instead of the x87 fpu. This is obtained by passing the  `-mfpmath=sse` option to the compiler on this platform (default for amd64). If the bug persists, it means it is probably an overflow of a pointer but this would be strange.

I can not use sse for the i386 architecture on Debian

https://wiki.debian.org/ArchitectureSpecificsMemo?highlight=%28sse2%29#i386-1

**Comment by kif** [comment]
What puzzles me is that it works on i386+Python3.9 and stops working in 3.10. This probably means there is something hidden there inside.
```
Ran 344 tests in 899.088s
OK (skipped=18)
```
Debian is apparently the only system still providing python3.10 on 32bit, Anaconda dropped it a while ago which does not make debug easy. I'll need to use a docker or a debbootstrap environment.

For the 3 broken tests, one could decorate them with this:
```
@unittest.skipIf(platform.machine() in ['i386', 'i586', 'i686'] and platform.architecture()[0] == '32bits', "Known broken on x86")
```
inside debian patches for now and validate later that the calculation are performed properly, because the differences in numerical values looks huge.

**Comment by kif** [comment]
I cannot reproduce the bug in a debian sid x86 chroot:
```
======================================================================
SKIPPED: runTest (pyFAI.gui.test.SkipGuiTest)
----------------------------------------------------------------------
pyFAI.gui tests disabled (Skipped by command line)
======================================================================
SKIPPED: test_cythonSP_vs_fit2d (pyFAI.test.test_azimuthal_integrator.TestAzimHalfFrelon)
Compare cython splitPixel with results of fit2d
----------------------------------------------------------------------
test using >200M
======================================================================
SKIPPED: test_cython_vs_fit2d (pyFAI.test.test_azimuthal_integrator.TestAzimHalfFrelon)
Compare cython histogram with results of fit2d
SKIPPED: test_cython_vs_numpy (pyFAI.test.test_azimuthal_integrator.TestAzimHalfFrelon)
Compare cython histogram with numpy histogram
SKIPPED: test_numpy_vs_fit2d (pyFAI.test.test_azimuthal_integrator.TestAzimHalfFrelon)
Compare numpy histogram with results of fit2d
SKIPPED: testNumpy (pyFAI.test.test_saxs.TestSaxs)
SKIPPED: test_bug170 (pyFAI.test.test_bug_regression.TestBug170)
----------------------------------------------------------------------
test using >100Mb
======================================================================
SKIPPED: test_medfilt1d (pyFAI.test.test_azimuthal_integrator.TestAzimHalfFrelon)
SKIPPED: test_mask_CSR_OCL (pyFAI.test.test_mask.TestMask)
The masked image has a masked ring around 1.5deg with value -10
SKIPPED: test_mask_LUT_OCL (pyFAI.test.test_mask.TestMask)
The masked image has a masked ring around 1.5deg with value -10
SKIPPED: test_mask_LUT_OCL (pyFAI.test.test_mask.TestMaskBeamstop)
With a mask with and without limits
SKIPPED: test_nomask_LUT_OCL (pyFAI.test.test_mask.TestMaskBeamstop)
without mask, tth value should start at 0
SKIPPED: test_opencl (pyFAI.test.test_preproc.TestPreproc)
----------------------------------------------------------------------
User request to skip OpenCL tests
======================================================================
SKIPPED: test_histo (pyFAI.test.test_azimuthal_integrator.TestIntergrationNextGeneration)
----------------------------------------------------------------------
Skipping TestIntergrationNextGeneration.test_histo as OpenCL method not available
======================================================================
SKIPPED: testSolidAngle (pyFAI.test.test_geometry.TestSolidAngle)
This dataset goes up to 56deg, very good to test the solid angle correction
----------------------------------------------------------------------
skipping test using >400M
======================================================================
SKIPPED: testCython (pyFAI.test.test_saxs.TestSaxs)
SKIPPED: test_pos_lut (pyFAI.test.test_distortion.TestHalfCCD)
Compare position from _distortion.Distortion and distortion.Distortion.
----------------------------------------------------------------------
skipping test using >100M
======================================================================
SKIPPED: test_opencl_csr (pyFAI.test.test_csr.TestCSR)
----------------------------------------------------------------------
Test on OpenCL disabled
----------------------------------------------------------------------
Ran 344 tests in 126.113s

OK (skipped=18)
root@antarctica:/workspace/pyFAI# python3
Python 3.9.10 (main, Jan 16 2022, 17:12:18) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.architecture()
('32bit', 'ELF')
```

**Comment by kif** [comment]
Apparently the same bug exists on *armel*. I am bootstrapping an armel-sid system on an armhf-stable board to validate

**Comment by kif** [comment]
# python3.10 run_tests.py -x -o -l
[...]
Ran 344 tests in 1603.181s

OK (skipped=18)
# file /usr/bin/python3.10
/usr/bin/python3.10: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.3, BuildID[sha1]=8cc950b8f81026190bc57e8fa1167d99547f7900, for GNU/Linux 3.2.0, stripped
```

**Comment by kif** [comment]
skip 3 tests on 32-bit platforms
