### ISSUE TITLE
Calibration problems using contrains

### ISSUE THREAD

**Issue by azkhadiev** [silx-kit/pyFAI#1696]
Dear Jerome Kieffer,

It seems that the calibration (fitting of the rings of the standard materials to the calculated ones) in pyFAI-calib doesn't work properly if I fix some values with the lock in the GUI (Geometry section: ether distance or the PONI1 and PONI2 positions). The the CMD I got the following lines:

WARNING:py.warnings:C:\Programfiles\Anaconda3\lib\site-packages\scipy\optimize\_numdiff.py:519: RuntimeWarning: invalid value encountered in true_divide
  J_transposed[i] = df / dx

Inequality constraints incompatible    (Exit mode 4)
            Current function value: 0.00012830939315641805
            Iterations: 1
            Function evaluations: 7
            Gradient evaluations: 1
INFO:pyFAI.geometryRefinement:Constrained Least square 1.9440817144911827e-06 --> 1.9440817144911827e-06
Inequality constraints incompatible    (Exit mode 4)
            Current function value: 0.00012830939315641805
            Iterations: 1
            Function evaluations: 7
            Gradient evaluations: 1
INFO:pyFAI.geometryRefinement:Constrained Least square 1.9440817144911827e-06 --> 1.9440817144911827e-06
Final residual: 1.9440817144911827e-06 (after 1 iterations)

What, do you think, could be the problem? Am I doing something wrong?

Thank you in advance!

Regards, Azat

**Comment by azkhadiev** [comment]
Sorry. Seems the error is cleared after installing the new version of the package.

Sorry for bothering and thank you for the great software!

**Comment by kif** [comment]
I suspect this bug was related to the change of behavior of `scipy` when it comes to empty range for some parameters.
This bug was fixed ~18month ago.
