### ISSUE TITLE
Dropping Python3.6?

### ISSUE THREAD

**Issue by t20100** [silx-kit/pyFAI#1721]
`namedtuple`'s `defaults` argument used here:
https://github.com/silx-kit/pyFAI/blob/ee48af0fbba8fef2ab563ed18ee550eadea6ac4f/pyFAI/containers.py#L39-L40
was added in Python 3.7 while `setup.py` advertises `python_requires='>=3.6'` (https://github.com/silx-kit/pyFAI/blob/master/setup.py#L1099):

This was changed in #1706.

Is it an intended drop of Python3.6?

**Comment by kif** [comment]
The drop of python 3.6 was documented in:
https://github.com/silx-kit/pyFAI/commit/c95564e4432005beb1bd94d1c659605d857c4715
but setup.py was not updated acordingly
