### ISSUE TITLE
Missing versions in ReadTheDocs

### ISSUE THREAD

**Issue by loichuder** [silx-kit/pyFAI#1735]
Only `master` and `v0.19.0` are available on RTD (no `v0.20.x` or `v0.21.x`).

![image](https://user-images.githubusercontent.com/42204205/192452863-bc209da7-f9ac-48ab-841d-35f705a70c8f.png)

Is this intended ?

**Comment by kif** [comment]
Yes and no ... the official documentation is to be found at `silx.org` 
http://www.silx.org/doc/pyFAI/
and I did not delete the pyFAI version 0.19 from RTD. I will keep only the development branch there.

**Comment by kif** [comment]
It should be removed soon (until the cache gets updated)

**Comment by loichuder** [comment]
Got it :+1: !

It would be nice to add a link to http://www.silx.org/doc/pyFAI/ in the section _Documentation_ of the README to point users to right location then (unless I missed an existing link) ?

**Comment by vallsv** [comment]
I though read the doc was dead?

**Comment by kif** [comment]
> I though read the doc was dead?

I manage to get it working again, but I agree it is fairly unrealiable
