### ISSUE TITLE
inconsistent behaviour of toolTip for pyFAI.gui.widgets.ElidedLabel and generic QWidget

### ISSUE THREAD

**Issue by malte-storm** [silx-kit/pyFAI#1757]
Hi,

I already raised this issue for silx silx-kit/silx/issues/3641 and encoutered the same problem for the pyFAI calib2 window again, which also uses the ElidedLabel (as a pyFAI class).

```
label = QtWidgets.QLabel()
elided_label = pyFAI.gui.widgets.ElidedLabel.ElidedLabel()

type(label.toolTip)
Out: builtin_function_or_method

type(elided_label.toolTip)
Out: str
```

Could you apply the silx fix to the pyFAI widget as well? 

Also, is there a reason pyFAI includes these widgets in its own package? Since silx is a requirement for pyFAI, would it not be easier to use the widgets from silx directly to prevent such out-of-sync issues?

**Comment by vallsv** [comment]
It's because the time you need to use it the widget is not yet available.
I think it is mostly historical.

**Comment by kif** [comment]
use silx code ...
