### ISSUE TITLE
Clean README file

### ISSUE THREAD

**Issue by kinetik161** [silx-kit/pyFAI#1800]
I propose just small doc corrections. Found it while installing from source and following instructions from `README.rst`. There are leftovers from times when `master` was the default branch. There are just three places

> unzip pyFAI-master.zip
> All files are unpacked into the directory pyFAI-master:
> cd pyFAI-master

where `pyFAI-master` should be replaced with `pyFAI-main`

**Comment by kif** [comment]
Thanks for spotting it.
