### ISSUE TITLE
Docker compatibility for ARM64 architecture

### ISSUE THREAD

**Issue by ZhangxiJesseFeng** [silx-kit/pyFAI#1896]
I attempted to create a docker using my M1 Mac machine, and encountered issue that says pyFAI is not found at all. I was able to create a Docker image on GitHub CI with Linux/AMD64 but fails on Linux/ARM64.

Looking into this further, am I correct that pyFAI simply does not currently support Linux - ARM64? Is there a work-around if I want to build a Docker image of a project that uses pyFAI?

Jesse

**Comment by kif** [comment]
Hi Jesse,

It is true that linux-arm64 is not one of our target, so it is not tested  .... but I see no reason why it should not work.
`pyFAI` is running just fine on the apple side of a mac-M1. I will try to compile it into a docker environment.
I did test it on (native) linux ARM32 andARM64 several years back without issue (beside the slowness of the raspberry pi and the limited RAM).

Cheers,

Jerome

**Comment by ZhangxiJesseFeng** [comment]
Hi Jerome,

Thanks for getting back to me. I had the issue of linux/arm64 pyFAI not found for both GitHub CI and when creating conda environment in a Ubuntu Docker.

**Comment by kif** [comment]
I am on a debian11 docker image (without conda) and the default image is missing those packages:
"python3-dev gcc g++"
Then a `pip install pyFAI` is able to compile pyFAI from sources. After that, il compiles nicely. 
Can you have a look at your docker configuration file and ensure those packages are properly installed before pyFAI ?

**Comment by kif** [comment]
Nota: `apt install python3-pip` pulls all this (and much more !)

**Comment by ZhangxiJesseFeng** [comment]
When I did pip install pyfai I encountered similar issue of missing gcc, g++ compilers. But after I added those. Pip still failed when trying to build slix.

Do you mean that apt-get python3-pip would allow pip to install pyfai in an empty image? Thanks I'll give it a try and let you know

**Comment by kif** [comment]
I just checked, it pulls all those packages among which all the `-dev` packages for python and the compiler:
```
binutils binutils-aarch64-linux-gnu binutils-common build-essential bzip2 ca-certificates cpp cpp-12 dirmngr dpkg-dev fakeroot fontconfig-config fonts-dejavu-core g++ g++-12 gcc gcc-12
  gnupg gnupg-l10n gnupg-utils gpg gpg-agent gpg-wks-client gpg-wks-server gpgconf gpgsm javascript-common krb5-locales libabsl20220623 libalgorithm-diff-perl libalgorithm-diff-xs-perl
  libalgorithm-merge-perl libaom3 libasan8 libassuan0 libatomic1 libavif15 libbinutils libbrotli1 libbsd0 libc-dev-bin libc-devtools libc6-dev libcc1-0 libcrypt-dev libctf-nobfd0 libctf0
  libdav1d6 libde265-0 libdeflate0 libdpkg-perl libexpat1 libexpat1-dev libfakeroot libfile-fcntllock-perl libfontconfig1 libfreetype6 libgav1-1 libgcc-12-dev libgd3 libgdbm-compat4
  libgdbm6 libgomp1 libgpm2 libgprofng0 libgssapi-krb5-2 libheif1 libhwasan0 libisl23 libitm1 libjansson4 libjbig0 libjpeg62-turbo libjs-jquery libjs-sphinxdoc libjs-underscore
  libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 libksba8 libldap-2.5-0 libldap-common liblerc4 liblocale-gettext-perl liblsan0 libmpc3 libmpfr6 libncursesw6 libnpth0 libnsl-dev
  libnsl2 libnuma1 libperl5.36 libpng16-16 libpython3-dev libpython3-stdlib libpython3.11 libpython3.11-dev libpython3.11-minimal libpython3.11-stdlib librav1e0 libreadline8 libsasl2-2
  libsasl2-modules libsasl2-modules-db libsqlite3-0 libssl3 libstdc++-12-dev libsvtav1enc1 libtiff6 libtirpc-common libtirpc-dev libtirpc3 libtsan2 libubsan1 libwebp7 libx11-6 libx11-data
  libx265-199 libxau6 libxcb1 libxdmcp6 libxpm4 libyuv0 linux-libc-dev make manpages manpages-dev media-types netbase openssl patch perl perl-modules-5.36 pinentry-curses python3
  python3-dev python3-distutils python3-lib2to3 python3-minimal python3-pkg-resources python3-setuptools python3-wheel python3.11 python3.11-dev python3.11-minimal readline-common
  rpcsvc-proto xz-utils zlib1g-dev
```

**Comment by kif** [comment]
According to your dockerfile, you are not building it inside the conda environment but outside !

try:
```
# Install MILK
RUN cd MILK \
    && conda install mamba -n base -c conda-forge \
    && mamba create -n ${CONDA_ENV} -c conda-forge openmpi mpi4py \
    && mamba env update -n ${CONDA_ENV} -f environment_linux.yml \
    && echo "conda activate $CONDA_ENV" >> ~/.bashrc \
    && conda activate $CONDA_ENV \
    && python -m pip install pyfai
```

**Comment by ZhangxiJesseFeng** [comment]
> According to your dockerfile, you are not building it inside the conda environment but outside !
> 
> try:
> 
> ```
> [...]
> # Install MILK
> RUN cd MILK \
>     && conda install mamba -n base -c conda-forge \
>     && mamba create -n ${CONDA_ENV} -c conda-forge openmpi mpi4py \
>     && mamba env update -n ${CONDA_ENV} -f environment_linux.yml \
>     && echo "conda activate $CONDA_ENV" >> ~/.bashrc \
>     && conda activate $CONDA_ENV \
>     && python -m pip install pyfai
> ```

Hi Jerome,

I was in the Docker having the rietveld environment activated when I encountered those errors.

Jesse

**Comment by kif** [comment]
By the way, did you try a simple `conda install silx` ? 
I saw there has been an issue with the version of silx to build ... no idea where it comes from.

**Comment by ZhangxiJesseFeng** [comment]
I tried `conda install slix`, 'conda install slix -c conda-forge`, and `mamba install slix` just now and all three returned error:

```
PackagesNotFoundError: The following packages are not available from current channels:

  - slix
```

For the record, I am ok with pyfai not able to be installed in this setting. I just want to get a confirmation that it is the case before I give up.

**Comment by kif** [comment]
@t20100 requested the packaging of `silx` on arm64:
https://github.com/conda-forge/silx-feedstock/pull/50/commits

Once this is done, we can request pyFAI...

**Comment by ZhangxiJesseFeng** [comment]
Great news! Thanks! Please keep me posted when it is done.

**Comment by kif** [comment]
It is done for `silx` ... `pyFAI` ongoing

**Comment by kif** [comment]
It should be done for pyFAI ...

**Comment by ZhangxiJesseFeng** [comment]
Hi Jerome, it works now! Thanks!

**Comment by t20100** [comment]
@ZhangxiJesseFeng  thanks for the testing!
