### ISSUE TITLE
calib2 not compatible with PySide6

### ISSUE THREAD

**Issue by malte-storm** [silx-kit/pyFAI#1918]
Hello,

while silx allows to use Qt6 (PySide6) as backend, running pyfai-calib2 with PySide6 raises some exceptions because of small differences how signals are handled.

The overloaded signal definition for the list model requires tuples instead of lists in Qt6.

**Comment by kif** [comment]
Thanks a lot ... apparently this addresses the issue #1852
@vallsv  did not find yet time for diving into it and I don't have Qt skills ...
The code LGTM, I am checking if it addresses all issued spotted.
