### ISSUE TITLE
unit handling on script command line

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#192]
From Olivier Taché:
When using "pyFAI-saxs -unit q_A^-1" I have an error

  File "C:\winpython\python-2.7.9.amd64\Scripts\pyFAI-saxs.py", line 160, in mai
n
    polarization_factor=options.polarization_factor)
  File "C:\winpython\python-2.7.9.amd64\lib\site-packages\pyFAI\azimuthalIntegra
tor.py", line 2188, in integrate1d
    pos0_scale = unit.scale
AttributeError: 'NoneType' object has no attribute 'scale'

**Comment by kif** [comment]
I did not manage to reproduce the bug ...

**Comment by vallsv** [comment]
Looks to be closed
