### ISSUE TITLE
Please add a .desktop for pyFAI-calib2 and other gui scripts.

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#1928]
Hello, it would be great if you could provide an official desktop file and an official icon for pyfai-calib and other gui scripts.

This allow to find them in the gnome-software application.

Cheers

Fred

**Comment by kif** [comment]
I used the first icon generator I found on the web to make this:
![pyFAI-calib2](https://github.com/silx-kit/pyFAI/assets/1018880/95eb025a-eefd-4a80-93c2-b869a5864fb5)

**Comment by picca** [comment]
In fact most of the desktop files are wrong ;), I am wondering if the Terminal should be actyivated for the gui applications.

**Comment by picca** [comment]
I can confirm that without the doc/source/img is works :)

**Comment by kif** [comment]
What do you mean ? I don't have desktop integration for now ...  just added those files believing they can be used by debian but I don't use them myself (yet).

**Comment by picca** [comment]
Hello, here the patch I need to apply in order to have coherant desktop files :).

https://sources.debian.org/src/pyfai/2023.9.0-1/debian/patches/0001-fix-desktop-files.patch/


I removed the Terminal=True, but I forgot for diffmap. I like when there is no parasitic windows :).
another interesting feature should be to add the mime type in the desktop file.

This one in from firefox

MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/vnd.mozilla.xul+xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;

Here the official mime type available

https://www.iana.org/assignments/media-types/media-types.xhtml

This way the menu should propose to pyFAI-something to open the given file.

In order to take the file input, you need to add a %u in the Exec command

like this

Exec=/usr/lib/firefox/firefox %u

**Comment by kif** [comment]
Should be fixed now
