### ISSUE TITLE
pyFAI-integrate batch processing on windows

### ISSUE THREAD

**Issue by ergabor92** [silx-kit/pyFAI#1929]
I cannot do batch processing on Windows when a mask file is added in the pyFAI-integrate GUI.

What could be the issue? I have the Python 3.11.4 version installed.

**Comment by kif** [comment]
On Fri, 01 Sep 2023 01:31:11 -0700
ergabor92 ***@***.***> wrote:

> I cannot do batch processing on Windows when a mask file is added in the pyFAI-integrate GUI.

Do you have a stack-trace ?

**Comment by ergabor92** [comment]
I don't.

Meanwhile, I tried with anaconda prompt, and in anaconda, it works.

Best regards,
Gabor

**Comment by kif** [comment]
then I close the issue.
