### ISSUE TITLE
Is it possible to reorder image to rectilinear (qx, qy) coordinates?

### ISSUE THREAD

**Issue by dscran** [silx-kit/pyFAI#1951]
Hi all,

I am trying to use pyFAI to do a 2d reordering of detector images, but as target coordinate system I need rectilinear (qx, qy) coordinates instead of polar coordinates (Q, chi). (Such that Q=sqrt(qx^2 + qy^2) and chi=arctan(qy/qx))

I have not found anything like that in the docs and I'm wondering whether it's possible to achieve with the existing methods? Any hints  and pointers in the right direction are greatly appreciated!

Many thanks and cheers!

**Comment by kif** [comment]
Hi Michael,

This sounds like a good idea. Nobody asked it to me until now.

Implementing it would requires:
- [ ] define two `units` called `qx` and `qy`  (see for example http://www.silx.org/doc/pyFAI/dev/usage/tutorial/LogScale/Guinier.html)
- [ ]  use the 2D binning engine. Not sure it can be done without modification of pyFAI, but I am ready to help in this step.

Defining the unit is fairly simple thanks to the numexpr library. 

Cheers,

Jerome

**Comment by kif** [comment]
OK, it confirms my guess: one can easily tune the "radial" unit but not the "azimuthal" unit (which are now both miss-named)...
I am currently in a conf, i.e. no time ... but it does not look complicated and I am happy to help you soon.

**Comment by kif** [comment]
Hi, you can have a look at the PR #1956. It works as long as qy is in the range -pi->pi since some limitation coming from the periodicity of the azimuthal angle are hard-coded a bit everywhere.
