### ISSUE TITLE
Integrate `pilx` into pyFAI

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#1999]
To be discussed, for now pilx is a stand-alone package which would gain in getting a closer integration into pyFAI.

**Comment by kif** [comment]
postponed ... not for 2024.01

**Comment by EdgarGF93** [comment]
Working on it, to open pilx after integration with pyFAI-diffmap

**Comment by EdgarGF93** [comment]
working here [#edgar](https://github.com/EdgarGF93/pyFAI/tree/1999_pilx)

**Comment by kif** [comment]
Done, now `pyFAI-diffmap-view` calls the `pilx` code
