### ISSUE TITLE
pyFAI-benchmark with GPUs

### ISSUE THREAD

**Issue by EdgarGF93** [silx-kit/pyFAI#2011]
There is no possibility of performing only GPU benchmark through the command line:

pyFAI-benchmark (with no cpu/gpu arguments) benchmarks using only CPU device
`pyFAI-benchmark --number 1 --size 6`
![no_argument](https://github.com/silx-kit/pyFAI/assets/112327909/33360173-b6e8-4aa4-b8cf-0d898c57dad6)

pyFAI-benchmark --cpu does the same
`pyFAI-benchmark --cpu --number 1 --size 6`
![cpu](https://github.com/silx-kit/pyFAI/assets/112327909/23ff2de5-cd12-41ed-ba6a-9d9b23c59d4e)

pyFAI-benchmark --gpu benchmarks both CPU and GPU (no possibility for only GPU benchmark)
`pyFAI-benchmark --gpu --number 1 --size 6`
![gpu](https://github.com/silx-kit/pyFAI/assets/112327909/106e2aa5-ad97-455e-b6af-de4925759b72)

The reason is that lines 750-754 are executed independently of the argument devices.
https://github.com/silx-kit/pyFAI/blob/e6778ffc889b097967a563feff6ab2d25afe83ce/src/pyFAI/benchmark/__init__.py#L748-L755

**Also, in line 734:**
https://github.com/silx-kit/pyFAI/blob/e6778ffc889b097967a563feff6ab2d25afe83ce/src/pyFAI/benchmark/__init__.py#L730-L740
Shouldn't it be len(device)? the list 'devices' contains strings

**Comment by kif** [comment]
I  guess, the best would be to provide a list of targets to actually benchmark like:
```
(no, histogram,*)
(full, *,*)
```

**Comment by kif** [comment]
For info: `--cpu` means all OpenCL CPU drivers. 
By default, cython histograms and sparse matrix multiplication are included.

**Comment by EdgarGF93** [comment]
Go to pull request #2016
