### ISSUE TITLE
Add grazing-incidence units

### ISSUE THREAD

**Issue by EdgarGF93** [silx-kit/pyFAI#2035]
Add grazing-incidence units (qxy) and qz (all three dimensions of q and squared root of both horizontal directions squared)

**Comment by EdgarGF93** [comment]
In-plane and Out-of-plane q arrays are now available but with incident_angle and tilt_angle=0.0

- [ ] Method to change manually the angles
- [ ] Integrate along qip and qoop units
- [ ] Join detector orientation with orientation of qip and qoop (instead of using unit_rot90)

**Comment by kif** [comment]
This looks like to be implemented now ... can we close the issue
