### ISSUE TITLE
PyFAI-calib2 still crashes on macOS

### ISSUE THREAD

**Issue by gitkuy** [silx-kit/pyFAI#2077]
Crashes after 'Extract more rings', regardless of the initialized refinement and the way the file is imported.

Reported at the Usermeeting

MacOS Sonoma 14.2.1 (23C71)
Chip: Apple M1 Max

INFO:numexpr.utils:Note: NumExpr detected 10 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
UNSUPPORTED (log once): buildComputeProgram: cl2Metal failed
INFO:pyFAI.method_registry:Degrading method from Method(dim=1, split='pseudo', algo='histogram', impl='*', target=None) -> Method(dim=1, split='bbox', algo='histogram', impl='*', target=None)
2024-02-05 17:33:11.012 Python[82835:3850493] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
INFO:pyFAI.massif:Image size is (2162, 2068)
INFO:pyFAI.massif:Binning size is [1, 1]
INFO:pyFAI.massif:Labeling found 1270 massifs.
Optimization terminated successfully    (Exit mode 0)
            Current function value: 3.908549506658066e-08
            Iterations: 39
            Function evaluations: 290
            Gradient evaluations: 39
INFO:pyFAI.geometryRefinement:Constrained Least square 0.26023607370283536 --> 1.0021921811943758e-09
INFO:pyFAI.geometryRefinement:maxdelta on dist: 0.1 --> 0.4154516705501784 
zsh: bus error  pyFAI-calib2

**Comment by EdgarGF93** [comment]
The user told me that probably was an issue after installation from the source, after removing and installing from pip, it's working fine.
