### ISSUE TITLE
Wavelength unit incorrect in Geometry.getImageD11

### ISSUE THREAD

**Issue by jadball** [silx-kit/pyFAI#2079]
The wavelength in ImageD11 parameter files is assumed to be in Angstroms, but pyFAI gives the wavelength in nanometres:

https://github.com/silx-kit/pyFAI/blob/c0773fa13b75c0528a1eee68991e1f3ae92eedd6/src/pyFAI/geometry/core.py#L1556-L1601

**Comment by EdgarGF93** [comment]
Jerome and me are not using ImageD11, so essentially, it would be changing the nm to Angstroms? Is that okay? @jonwright

**Comment by jonwright** [comment]
Yes please.

ImageD11 does not select units but just expects people to be consistent. Most humans choose Angstrom. For ImageD11 you just need to use the same unit for unit cell parameters and wavelength. Also use the same unit for sample to detector distance as pixel size (in the code example above, the distance is micron not nm).

I have in mind there are some other issues with ImageD11 <-> pyFAI parameters. 
- We miss a way to share the spatial distortion information
- there was something missing on the ImageD11 side to receive an ordered dict
- The required flip for the Eiger at ID11 is (-1,0,0,-1) and this is not handled by the pyFAI code above.  
 
@jadball we could probably fix some things on the ImageD11 and then send any needed pull request for pyFAI. I think there is just a sign inversion on some of the tilts for the flip, but flips were recently added on the pyFAI side too. For the distortion it means adding something like dxfile and dyfile entries, or learning to use the nexus detector file on the ImageD11 side. Do you flip the distortion image or assume it is applied before the flip? Yesterday Pierre-Olivier was looking at that story for Dioptas.

For a testcase with ImageD11 (better to skip than add a dependency?). I think both packages can compute pixel positions in 3D space (ImageD11.transform.compute_xyz_lab for pixel centres) and the conventions should be similar:
- ImageD11/fable x axis = beam direction = pyFAI x3 direction?
- ImageD11/fable z axis = vertically up, normal to the beam = pyFAI x1 direction?
- ImageD11/fable y axis = away from the centre of the synchrotron = negative of pyFAI x2 direction?

Comparing two theta is 'easy', for 'azimuth' angle then I guess we have different origins (and maybe signs). Do you have a testcase already? On the ImageD11 side we could try to write a come up with a "to_poni" and/or "from_poni" function too...

**Comment by kif** [comment]
@jonwright I agree with you the exchange of detector definition is currently pretty weak ... and addressing it in a general manner is out of the scope of this issue. Feel free to open a dedicated issue (could be more efficient when opening a JIRA ticket :-) .

Concerning the orientation of the detector, I agree with you: Eiger differs from Frelon (and pyFAI does not handle it properly, but fixing it would break any existing PONI-file). 

Could you please provide me with a snippet to generate 2theta/chi arrays from a parameter-set so that the equivalence of orientation could be validated. thanks

**Comment by jonwright** [comment]
Hopefully it is easy to get tth/azimuth arrays from here:

https://github.com/jonwright/ImageD11/blob/82c99a134c66465f23f4d3f0c56d74a3571e999f/ImageD11/transform.py#L659

The __init__ on PixelLUT should have most of that, where coordinates are pixel centers.

I think the azimuth definition is different however (and I am on vacation for another week or so, so will not get back to check it for a while)

**Comment by kif** [comment]
* 2theta arrays are ok-ish. The difference is ~ 0.01° which is not negligible. Probably an issue related to the position of the center vs corner of pixel ... worth investigating
* Azimuthal angles do not have the same origin ...
* `spline` as to be absent from the dict, not `None`. I would consider this as a bug.
