### ISSUE TITLE
refine2_wavelength doesn't refine wavelength?

### ISSUE THREAD

**Issue by emilymassahud** [silx-kit/pyFAI#2093]
There are 2 methods doing almost the same thing, `refine2` and `refine2_wavelength`. However `refine2_wavelength` docstring says it's supposed to be refining wavelength as well, but has an:  `if fix is None: fix = ["wavelength"]` inside it. Just wondering if this is correct?
https://github.com/silx-kit/pyFAI/blob/main/src/pyFAI/geometryRefinement.py#L510

**Comment by kif** [comment]
Well spotted !
indeed it is a bug.
