### ISSUE TITLE
Issue using pyFAI-integrate 

### ISSUE THREAD

**Issue by SeanDrewry** [silx-kit/pyFAI#2168]
When I try to run pyFAI-integrate in anaconda prompt, I am running into this error:

"(pyFAI_env_2) C:\Users\iianO>pyFAI-integrate
INFO:numexpr.utils:Note: NumExpr detected 20 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
INFO:pyFAI.method_registry:Degrading method from Method(dim=1, split='pseudo', algo='histogram', impl='*', target=None) -> Method(dim=1, split='bbox', algo='histogram', impl='*', target=None)
Traceback (most recent call last):
  File "C:\Users\iianO\anaconda3\envs\pyFAI_env_2\Scripts\pyFAI-integrate-script.py", line 6, in <module>
    from pyFAI.app.integrate import main
  File "C:\Users\iianO\anaconda3\envs\pyFAI_env_2\Lib\site-packages\pyFAI\app\integrate.py", line 58, in <module>
    import pyFAI.worker
  File "C:\Users\iianO\anaconda3\envs\pyFAI_env_2\Lib\site-packages\pyFAI\worker.py", line 102, in <module>
    from .distortion import Distortion
  File "C:\Users\iianO\anaconda3\envs\pyFAI_env_2\Lib\site-packages\pyFAI\distortion.py", line 41, in <module>
    from .opencl import ocl
ImportError: cannot import name 'ocl' from 'pyFAI.opencl' (C:\Users\iianO\anaconda3\envs\pyFAI_env_2\Lib\site-packages\pyFAI\opencl\__init__.py)"

I am using windows and my python version is 3.12.3. I used conda to install pyFAI (conda install pyfai -c conda-forge).

**Comment by kif** [comment]
This is a known issue. Please downgrade silx to version 2.0 instead of 2.1 until we release pyFAI 2024.5 (foreseen soon).

**Comment by kif** [comment]
The release is ready ... just a matter of making wheels.

**Comment by SeanDrewry** [comment]
Perfect! This worked for now, will look forward to the 2.1 release!

**Comment by kif** [comment]
The release is out on PyPI ... conda forge should follow in a couple of days.
