### ISSUE TITLE
bunch of files with unknown license informations

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#217]
Hello,

SO here the files with no license informations when checked by licensecheck

picca@ORD03037:~/Debian/main/pyfai/pyfai$ licensecheck -r -m . | grep UNKNOW
./src/crc32.h   UNKNOWN
./src/histogram.pyx     UNKNOWN
./src/crc32.c   UNKNOWN
./benchmark/benchmark_split.py  UNKNOWN
./benchmark/benchmark_distortion.py     UNKNOWN
./benchmark/benchmark.py        UNKNOWN
./benchmark/benchmark_ocl_csr3.py       UNKNOWN
./doc/source/mathjax.py UNKNOWN
./test/profile_splitPixelFullLUT.py     UNKNOWN
./test/bug-1280.py      UNKNOWN
./test/debug_split_pixel.py     UNKNOWN
./test/profile_ocl_lut_pixelsplit2.py   UNKNOWN
./test/splitpixel_vs_splitpixelfull.py  UNKNOWN
./test/profile_pixelsplitFullLUT2.py    UNKNOWN
./test/check_calib.py   UNKNOWN
./test/profile_ocl_hist_pixelsplit.py   UNKNOWN
./test/profile_csr.py   UNKNOWN
./test/profile_csr_2d.py        UNKNOWN
./test/profile_OCLFullSplit.py  UNKNOWN
./test/chi_square.py    UNKNOWN
./test/chi_square_ds8.py        UNKNOWN
./test/profile_csr_all_platforms.py     UNKNOWN
./test/profile_hdf5.py  UNKNOWN
./test/profile_ocl_lut_pixelsplit.py    UNKNOWN
./test/profile_pixelsplitFullLUT.py     UNKNOWN
./test/profile_ocl_lut_pixelsplit3.py   UNKNOWN
./test/blob.py  UNKNOWN
./test/bug_ocl_cpu.py   UNKNOWN
./test/memleak.py       UNKNOWN
./test/debug_ocl_sort.py        UNKNOWN
./test/profile_lut_pixelsplitFull.py    UNKNOWN
./test/profile_csr_fullsplit.py UNKNOWN
./test/profile_pixelsplitFull.py        UNKNOWN
./test/mactrace.py      UNKNOWN
./test/profile_csr_padded_csr.py        UNKNOWN
./openCL/for_eclipse.h  UNKNOWN
./build-deb.sh  UNKNOWN
./pyFAI-src/_version.py UNKNOWN
./pyFAI-src/OCLFullSplit1D_template.py  UNKNOWN

**Comment by picca** [comment]
the license header of openCL/ocl_lut.cl is missing

**Comment by picca** [comment]
Unwanted files

PyFAI.egg-info/

**Comment by kif** [comment]
Tests files have been fixed.

**Comment by kif** [comment]
I found a new one :)
./doc/source/usage/tutorial/Soleil/soleil.py

**Comment by vallsv** [comment]
It was improved for the release 0.15. But Debian 8 or Debian 9 do not probvide the same output.

**Comment by kif** [comment]
On Thu, 18 Oct 2018 00:26:11 -0700
Valentin Valls <notifications@github.com> wrote:

> Maybe we could closde this issue now? Here is the current state.
> ```
> ./doc/source/mathjax.py	UNKNOWN
> ./sandbox/profile_ocl_lut_pixelsplit3.py	UNKNOWN
> ./sandbox/profile_lut_pixelsplitFull.py	UNKNOWN
> ./sandbox/profile_ocl_lut_pixelsplit2.py	UNKNOWN
> ./sandbox/profile_ocl_hist_pixelsplit.py	UNKNOWN
> ./sandbox/profile_OCLFullSplit.py	UNKNOWN
> ./sandbox/test_opencl_reduction_test4.py	UNKNOWN
> ./sandbox/raspberry.py	UNKNOWN
> ./sandbox/test_integrate_ui.py	UNKNOWN
> ./sandbox/bug_267.py	UNKNOWN
> ./sandbox/profile_pixelsplitFull.py	UNKNOWN
> ./sandbox/profile_pixelsplitFullLUT2.py	UNKNOWN
> ./sandbox/profile_ocl_lut_pixelsplit.py	UNKNOWN
> ./sandbox/profile_csr.py	UNKNOWN
> ./sandbox/demo_225.py	UNKNOWN
> ./sandbox/profile_splitPixelFullLUT.py	UNKNOWN
> ./sandbox/profile_csr_padded_csr.py	UNKNOWN
> ./sandbox/profile_pixelsplitFullLUT.py	UNKNOWN
> ./ci/amd_sdk.sh	UNKNOWN
> ./ci/before_install-linux.sh	UNKNOWN
> ./ci/intel_opencl_icd.sh	UNKNOWN
> ./plugins/Tango/DistortionDS.py	UNKNOWN
> ./plugins/PyMca/AzimuthalIntegrationPlugin.py	UNKNOWN
> ./plugins/Lima/pyFAI_lima.py	UNKNOWN
> ./plugins/Lima/pyfai.py	UNKNOWN
> ./plugins/Lima/AzimuthalIntegration.py	UNKNOWN
> ./plugins/Lima/limaFAI.py	UNKNOWN
> ./plugins/Lima/DistortionCorrection.py	UNKNOWN
> ./plugins/Lima/demo_pyFAI.py	UNKNOWN

None of those files are part of the debian packaging ... so it is OK for me.

-- 
Jérôme Kieffer
tel +33 476 882 445

**Comment by vallsv** [comment]
And mathjax is explicitly BSD
Fine then.
