### ISSUE TITLE
Explicitly close files in all applications making heavy use of data

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#2171]
This is problem ESRF users are facing more and more often: cannot open new files because too many were already opened. Typically ~1000 files.
One should ensure all application within pyFAI close the access to data file when done with them:
- [ ] pyFAI-integrate (batch mode)
- [ ] diffmap
- [ ] ???

One possible limitation is HDF5 itself since data are concatenated in a virtual dataset referring to data in more than 1000 files. In such cases, one should avoid using the master-file to access to the raw data.

**Comment by t20100** [comment]
One workaround is to increase the soft limit of opened files:

https://github.com/silx-kit/silx/blob/755fa6d3cbe35e1078f65557f6e9e8352b826da5/src/silx/app/view/main.py#L106-L118

**Comment by kif** [comment]
We should follow both roads ... playing with `ulimit` makes little sense if the code leaves files unnecessary open.
This work-around should be  exposed in fabio, and possibly used in pyFAI.
