### ISSUE TITLE
would it be possible to switch from python-fftw to python-pyfftw

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#220]
Hello, I prepared pyfai pacakges for python, python3, python-dbg and python3-dbg

Since pyfftw has all the necessary pacakges instead of pyton-fftw.
Would it be possible to move from python-fftw to python-pyfftw.

~$ apt-cache search fftw python
python-pyfftw - Pythonic wrapper around FFTW - Python 2
python-pyfftw-dbg - Pythonic wrapper around FFTW - Python 2 (debug)
python3-pyfftw - Pythonic wrapper around FFTW - Python 3
python3-pyfftw-dbg - Pythonic wrapper around FFTW - Python 3 (debug)
python-fftw - Python bindings to the FFTW3 C-library for Fourier transforms

Cheers

Fred

**Comment by kif** [comment]
On Tue, 28 Jul 2015 01:26:17 -0700
picca <notifications@github.com> wrote:

> Hello, I prepared pyfai pacakges for python, python3, python-dbg and python3-dbg
> 
> Since pyfftw has all the necessary pacakges instead of pyton-fftw.
> Would it be possible to move from python-fftw to python-pyfftw.
> 
> ~$ apt-cache search fftw python
> python-pyfftw - Pythonic wrapper around FFTW - Python 2
> python-pyfftw-dbg - Pythonic wrapper around FFTW - Python 2 (debug)
> python3-pyfftw - Pythonic wrapper around FFTW - Python 3
> python3-pyfftw-dbg - Pythonic wrapper around FFTW - Python 3 (debug)
> python-fftw - Python bindings to the FFTW3 C-library for Fourier transforms

The API of the 2 libraries are very different. 
it is more likely this FFT part gots ported to numpy (or scipy) instead.

Cheers,

**Comment by picca** [comment]
Hello Jerome, it would be great to get rid of this dependency. less dependency is less work for integration.
