### ISSUE TITLE
v2023.1 is default on Readthedocs

### ISSUE THREAD

**Issue by takluyver** [silx-kit/pyFAI#2211]
Hi @kif ! I noticed that if I go to https://pyfai.readthedocs.io it redirects me to the docs for v2023.1, now fairly old, rather than stable or latest. Is there a reason for that being the default? Or is it an oversight?

Thanks :slightly_smiling_face:

**Comment by kif** [comment]
Hi Thomas,
I just forgot to update the things ... should be fixed now. 
I consider `www.silx.org` the stable repo for the doc of pyFAI while RTD is only the CI to test the building of those docs.

**Comment by takluyver** [comment]
Thanks! If you consider the location on silx.org to be the main docs, I'll update our links to point there.
