### ISSUE TITLE
[pilx] reads only the first HDF5 source dataset

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#2275]
Only supports source data coming from a single HDF5 dataset. 
Typical maps come from several HDF5 files
Using a virtual-dataset would be an option but HDF5 then keeps all files open so it is likely to crash because too many files opened. To me it is not an option when working with a large number of files like we do in this kind of experiments.
I would prefer to use external links so that we can manage the file opening/closing. 

@loichuder I don't know if you have time to look after this issue or if you prefer Edgar or I do it.

**Comment by loichuder** [comment]
Could you give an example file or the procedure to generate one ?

**Comment by kif** [comment]
You can find one example in "/tmp_14_days/kieffer/test....h5"

The issue is in `pilx/MainWindow.py` line 121 where the path looks like hard coded.
At this stage, I would scan for all datasets available (in order, with the proper prefix) and populate a dict with {dataset_path: number_of_frames}, then take care of closing those (external) files.

Later on at line 200, I would compare the image_index with the cumsum of the previous dict to find the proper dataset to open and the reduced index.

**Comment by loichuder** [comment]
I think @EdgarGF93 already did some changes to support multiple datasets. You can select a different data path via the `-d` arg of the command line:

```
pyFAI-diffmap-view ~/Data/pilx/test_20240916.h5 -d /entry_0000/measurement/images_0005
```

But if I understood correctly, you would want `pilx` to be able to navigate through all the datasets at once ?

**Comment by kif** [comment]
Yes, this is the idea. In this example, 130000 frames (85x160 map) are distributed over 7 files.
