### ISSUE TITLE
Default "no" splitting in multi_geometry when using grazing incidence units

### ISSUE THREAD

**Issue by EdgarGF93** [silx-kit/pyFAI#2279]
We did it for standard ai.integrate2d, but not in multi_geometry which is using ("full", "histogram", "cython") by default
So, by default, GI + multi_geometry will fill the missing wedge

**Comment by EdgarGF93** [comment]
Actually, it's only in the `integrate1d_fiber` , it's not using it through the integrate2d ... :)

**Comment by kif** [comment]
There are warning in place ...
