### ISSUE TITLE
pyFAI-calib2: cannot include polarization factor flag when calling from the cli

### ISSUE THREAD

**Issue by maak-sdu** [silx-kit/pyFAI#2280]
When calling the pyFAI-calib2 gui from the cli, I am not able to use the polarization factor flag. (-P or --polarization)

**cli call:**
`pyFAI-calib2 {image} -w {wavelength} -c {calibrant} -D {detector} -m {mask} --unit {unit} -l {dist_mm} --npt {npt} -P {polarization_factor}`

**Error message:**
```
INFO:numexpr.utils:NumExpr defaulting to 4 threads.
INFO:pyFAI.method_registry:Degrading method from Method(dim=1, split='pseudo', algo='histogram', impl='*', target=None) -> Method(dim=1, split='bbox', algo='histogram', impl='*', target=None)
ERROR:pyFAI-calib2.UNCAUGHT:ExperimentSettingsModel.polarizationFactor() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/bin/pyFAI-calib2", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3/dist-packages/pyFAI/app/calib2.py", line 629, in main
    setup_model(context.getCalibrationModel(), options)
  File "/usr/lib/python3/dist-packages/pyFAI/app/calib2.py", line 363, in setup_model
    settings.polarizationFactor(options.polarization_factor)
TypeError: ExperimentSettingsModel.polarizationFactor() takes 1 positional argument but 2 were given
```

When searching for the error message, it appears to be related to [_syntactic sugar_](https://stackoverflow.com/questions/23944657/typeerror-method-takes-1-positional-argument-but-2-were-given-but-i-only-pa).

**Comment by kif** [comment]
Thanks for the report. 
Indeed this bug has be waiting for you for 7 years! 
Fortunately, the fix is fairly straight forward.

For info, polarization correction is only used when performing integration, not for the extraction of control-points since we don't have the geometry yet.
