### ISSUE TITLE
AttributeError: DiffTomo object has no attribute 'setup_ai'

### ISSUE THREAD

**Issue by CiolJegou** [silx-kit/pyFAI#2355]
Hello,

I encountered an issue while using diff_tomo to process diffraction data. Specifically, I ran into the following error:
`AttributeError: DiffTomo object has no attribute 'setup_ai'`

Upon investigating, it seems that the function `setup_ai()` does not exist in `diffmap.py`. Could it be a typo, possibly meant to call `init_ai() ` instead? (Referencing diff_tomo.py, line 207).

Thank you for your assistance!

Best regards,
Loïc

**Comment by kif** [comment]
Thanks for the report ... Indeed, this looks like a regression introduced when we migrated from using `ai` to `worker`.
