### ISSUE TITLE
Problem of encoding when loading .cl files on MacOSX

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#281]
An exception occurred when loading .cl file on MacOSX/Python 3.5
The default encoding looks to not support accents in .cl files.

Then it would be nice to
- Avoid accent in .cl files (and prevent to add accents)
  or
- Patch the python open method to take care of the encoding (and supporting Python 2.7 and Python 3.5)

**Comment by kif** [comment]
I checked and it looks OK:
```
for f in glob.glob("pyFAI/resources/openCL/*.cl"):
    d = open(f).read()
    n = numpy.fromstring(d, dtype="uint8")
    if (n>127).sum():
        print(f, numpy.where(n>127))
```
