### ISSUE TITLE
pyFAI 0.12 test failed once installed

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#286]
Hello, I put here the ouput of

pyFAI.test().

In [2]: pyFAI.tests()
pyFAI.test.test_dummy
<module 'pyFAI' from '/usr/lib/python2.7/dist-packages/pyFAI/__init__.pyc'>
.WARNING:pyFAI.splitBBoxCSR:Pixel splitting desactivated !
.WARNING:pyFAI.splitBBoxCSR:Pixel splitting desactivated !
.WARNING:pyFAI.splitBBoxCSR:Pixel splitting desactivated !
.WARNING:pyFAI.splitBBoxCSR:Pixel splitting desactivated !
WARNING:test_histogram:pixel count difference numpy/csr : max delta=8.0
WARNING:test_histogram:Intensity count difference numpy/csr : max delta=0.357018871039
.WARNING:pyFAI.splitBBoxCSR:Pixel splitting desactivated !
.WARNING:pyFAI.splitBBoxCSR:Pixel splitting desactivated !
.WARNING:pyFAI.splitBBoxCSR:Pixel splitting desactivated !
.WARNING:pyFAI.splitBBoxCSR:Pixel splitting desactivated !
WARNING:test_histogram:pixel count difference numpy/csr : max delta=1.0
WARNING:test_histogram:Intensity count difference numpy/csr : max delta=16.0
.....................WARNING:pyFAI.geometry:No fast path for space: d*2
.WARNING:pyFAI.geometry:No fast path for space: d*2
.......................................................WARNING:pyFAI.geometry:No fast path for space: d*2
.WARNING:pyFAI.geometry:No fast path for space: log(q)
....WARNING:pyFAI.geometry:No fast path for space: d*2
.WARNING:pyFAI.geometry:No fast path for space: log(q)
....WARNING:pyFAI.geometry:No fast path for space: d*2
.WARNING:pyFAI.geometry:No fast path for space: log(q)
....WARNING:pyFAI.geometry:No fast path for space: d*2
.WARNING:pyFAI.geometry:No fast path for space: log(q)
.................../usr/lib/python2.7/dist-packages/pyopencl/__init__.py:61: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  "to see more.", CompilerWarning)
.......WARNING:pyFAI.geometry:Rotation conversion from pyFAI to SPD is not yet implemented
........WARNING:pyFAI.geometry:No fast path for space: None
..........WARNING:pyFAI._distortion:Patching image as image is 2048x1024 and spline is 2048x1025
.ERROR:pyFAI.distortion:The image shape ((1024, 2048)) is not the same as the detector ((1025, 2048)). Adapting shape ...
.ERROR:pyFAI.distortion:The image shape ((1024, 2048)) is not the same as the detector ((1025, 2048)). Adapting shape ...
...WARNING:pyFAI.geometry:No fast path for space: None
.WARNING:pyFAI.histogram_omp:No pixel splitting in histogram
.........WARNING:pyFAI.detectors:Binning factor (10x10) is not an official value for Rayonix detectors
..........................................................WARNING:pyFAI.splitBBoxCSR:Pixel splitting desactivated !
.WARNING:pyFAI.splitBBoxCSR:Pixel splitting desactivated !
.WARNING:pyFAI.splitBBoxCSR:Pixel splitting desactivated !
.../usr/lib/python2.7/dist-packages/sklearn/pls.py:7: DeprecationWarning: This module has been moved to cross_decomposition and will be removed in 0.16
  "removed in 0.16", DeprecationWarning)
usage: pyFAI-average [options] [options] -o output.edf file1.edf file2.edf ...
pyFAI-average: error: unrecognized arguments: --quiet
ERROR:test_bug_regression:
/usr/bin/python /usr/bin/pyFAI-average --quiet -q 0.2-0.8 -o /tmp/pyFAI_ndysmi_picca/out.edf /tmp/pyFAI_ndysmi_picca/img_0.edf /tmp/pyFAI_ndysmi_picca/img_1.edf /tmp/pyFAI_ndysmi_picca/img_2.edf /tmp/pyFAI_ndysmi_picca/img_3.edf /tmp/pyFAI_ndysmi_picca/img_4.edf
ERROR:test_bug_regression:Environment:
    GNOME_DESKTOP_SESSION_ID: this-is-deprecated
    GJS_DEBUG_OUTPUT: stderr
    http_proxy: http://195.221.10.7:8080
    XDG_CURRENT_DESKTOP: GNOME
    LOGNAME: picca
    USER: picca
    HOME: /home/experiences/instrumentation/picca
    XDG_VTNR: 7
    PATH: /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
    WINDOWPATH: 7
    SSH_AGENT_PID: 3040
    LANG: en_US.UTF-8
    TERM: xterm
    SHELL: /bin/bash
    XAUTHORITY: /var/run/gdm3/auth-for-picca-pn0tie/database
    SESSION_MANAGER: local/diffabs6:@/tmp/.ICE-unix/3001,unix/diffabs6:/tmp/.ICE-unix/3001
    SHLVL: 1
    DISPLAY: :0
    WINDOWID: 27279500
    GPG_AGENT_INFO: /run/user/22503/keyring/gpg:0:1
    USERNAME: picca
    XDG_SESSION_DESKTOP: default
    XDG_RUNTIME_DIR: /run/user/22503
    PYTHONPATH: :/usr/bin:/usr/lib/python2.7:/usr/lib/python2.7/plat-x86_64-linux-gnu:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/PILcompat:/usr/lib/python2.7/dist-packages/gtk-2.0:/usr/lib/pymodules/python2.7:/usr/lib/python2.7/dist-packages/wx-3.0-gtk2:/usr/lib/python2.7/dist-packages/IPython/extensions:/home/experiences/instrumentation/picca/.ipython
    SSH_AUTH_SOCK: /run/user/22503/keyring/ssh
    VTE_VERSION: 3801
    GDMSESSION: default
    XDG_SESSION_ID: 3
    DBUS_SESSION_BUS_ADDRESS: unix:abstract=/tmp/dbus-KCofLYQvXR,guid=af2acad9b2fcfa898be17aec57568b74
    _: /usr/bin/ipython
    HTTPS_PROXY: http://195.221.10.7:8080
    DESKTOP_SESSION: default
    OLDPWD: /home/experiences/instrumentation/picca
    GDM_LANG: en_US.UTF-8
    XDG_DATA_DIRS: /usr/share/gnome:/usr/local/share/:/usr/share/
    PWD: /tmp
    XDG_MENU_PREFIX: gnome-
    LS_COLORS: rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
    GJS_DEBUG_TOPICS: JS ERROR;JS LOG
    XDG_SEAT: seat0
F..WARNING:pyFAI.timeit:init_labels took 0.908s
WARNING:pyFAI.timeit:init_borders took 0.023s
WARNING:pyFAI.timeit:init_regions took 0.232s
WARNING:pyFAI.timeit:init_pass took 0.185s
162145
64
64
...WARNING:test_multi_geometry:TestMultiGeometry.test_integrate2d gave difference of intensity: 2.99028954487e-06, count: 8.08242361927e-14 cum: 1.46765025875e-05
.......[0 1]
..ERROR:pyFAI.worker:['error in integration', 'Out of memory', 'data.shape: (1,)', 'data.size: 1', 'ai:', '<pyFAI.test.test_worker.AzimuthalIntegratorMocked instance at 0x7fa39c64c200>', 'csr:']
...Gtk-Message: Failed to load module "canberra-gtk-module"
WARNING:pyFAI.integrate_widget:Undefined unit !!! falling back on 2th_deg
WARNING:pyFAI.integrate_widget:item is not a file ... guessing it is a numpy array
.WARNING:pyFAI.integrate_widget:Undefined unit !!! falling back on 2th_deg
WARNING:pyFAI.integrate_widget:item is not a file ... guessing it is a numpy array
WARNING:pyFAI.geometry:No fast path for space: None
.WARNING:pyFAI.integrate_widget:Undefined unit !!! falling back on 2th_deg
WARNING:pyFAI.integrate_widget:No input data to process
.WARNING:pyFAI.integrate_widget:Undefined unit !!! falling back on 2th_deg
WARNING:pyFAI.integrate_widget:Undefined unit !!! falling back on 2th_deg
.WARNING:pyFAI.integrate_widget:Undefined unit !!! falling back on 2th_deg
WARNING:pyFAI.integrate_widget:Undefined unit !!! falling back on 2th_deg
WARNING:pyFAI.geometry:No fast path for space: None
.
======================================================================
FAIL: test_quantile (pyFAI.test.test_bug_regression.TestBug211)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pyFAI/test/test_bug_regression.py", line 139, in test_quantile
    self.assertEqual(p, 0, msg="pyFAI-average return code %i != 0" % p)
AssertionError: pyFAI-average return code 2 != 0

----------------------------------------------------------------------
Ran 223 tests in 196.519s

FAILED (failures=1)
Test suite failed

**Comment by kif** [comment]
Hi Fred,

thanks for the report, can I ask you if those 2 files are properly installed ?
/usr/bin/python /usr/bin/pyFAI-average

This test actually runs the scripts to validate their proper installation.

**Comment by picca** [comment]
> Hi Fred,

> thanks for the report, can I ask you if those 2 files are properly installed ?
> /usr/bin/python /usr/bin/pyFAI-average

No this is during the build.

In thaht case this should be skip

BUT

I can use these tests with autopkgtest (test as installed)

Cheers

**Comment by kif** [comment]
On Mon, 20 Jun 2016 09:14:12 -0700
picca <notifications@github.com> wrote:

> > Hi Fred,
> 
> > thanks for the report, can I ask you if those 2 files are properly installed ?
> > /usr/bin/python /usr/bin/pyFAI-average
> 
> No this is during the build.
> 
> In thaht case this should be skip
> 

During the build, the $PATH should be patched to find pyFAI-average in
the script directory... unless it has been modified/moved away.

We should debug by printing the path searched ...

Cheers,

**Comment by picca** [comment]
> During the build, the $PATH should be patched to find pyFAI-average in
> the script directory... unless it has been modified/moved away.

ok,in that case, I can prepend the script dir during the test phase of the build process.

thanks

Fred
