### ISSUE TITLE
Remove logging initialization from the library

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#295]
https://docs.python.org/2/howto/logging.html#configuring-logging-for-a-library

Logger should be only initialized by the application part (scripts, benchmark, test runner...)

**Comment by kif** [comment]
There is a side effect: app should initialize the logger which is currently not the case !

**Comment by vallsv** [comment]
Looks to be done. I will check.

**Comment by vallsv** [comment]
The last `logging.basicConfig()` is done on the init.

**Comment by vallsv** [comment]
It's merged
