### ISSUE TITLE
figure error in the documetnation

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#319]
Hello,

While playing with the pyFAI geometry, we saw that the figure in the 1.3.2 section seems to be wrong.
The rot2 and rot3 rotations are non-direct. is it normal ? (règle du tire bouchon).

Cheers

**Comment by kif** [comment]
On Thu, 23 Jun 2016 06:47:50 -0700
picca <notifications@github.com> wrote:

> Hello,
> 
> While playing with the pyFAI geometry, we saw that the figure in the 1.3.2 section seems to be wrong.
> The rot2 and rot3 rotations are non-direct. is it normal ? (règle du tire bouchon).

You are right !!!

This figure has been around for a couple of years and 2 people spotted the error in a week ... funny.

Cheers,

Jerome

**Comment by kif** [comment]
Is this better ?
https://github.com/kif/pyFAI/blob/issue_319/doc/source/usage/tutorial/Geometry/geometry.ipynb

**Comment by kif** [comment]
The documentation has been merged in the master. close issue
