### ISSUE TITLE
Clean up uses of 'input'

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#370]
The project uses different ways to call ```input``` in a portable way.
Looking around six. Instead of using ```input```. Maybe we should use this way:

```
try:
    import six
except ImportError:
    from .third_party import six

six.moves.input("How old is the captain?: ")
```

**Comment by kif** [comment]
Actually it was decided to do:
```
try:
      from .third_party import six
except:
       import six
six.moves.input("How old is the captain?: ")
```

**Comment by kif** [comment]
the reason id for debian packaging as they remove the third-party.

**Comment by vallsv** [comment]
Ill check that. Normally it is already fixed like that

**Comment by vallsv** [comment]
Done
