### ISSUE TITLE
Normalize/remove use of StringTypes

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#372]
The enum ```StringTypes```

- is not defined on Python 3
- is defined many times in pyFAI modules
- six.string_types exists but do not looks the same
- can we use isinstance?

We should use an unique way to check strings.

**Comment by kif** [comment]
isinstance is OK with generalized "new style classes" 
but one needs to join unicode and bytes

**Comment by vallsv** [comment]
Fix it using `utils.StringTypes`
