### ISSUE TITLE
pyFAI 0.12.0 build error on powerpc

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#390]
Hello,

I got his error when building pyfai 0.12.0 on powerpc

https://buildd.debian.org/status/fetch.php?pkg=pyfai&arch=powerpc&ver=0.12.0%2Bdfsg-2&stamp=1471458133

==========================================================================
ERROR: test_shift (pyFAI.test.test_utils.TestUtils)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«BUILDDIR»/pyfai-0.12.0+dfsg/.pybuild/pythonX.Y_2.7/build/pyFAI/test/test_utils.py", line 126, in test_shift
    self.assert_(abs(utils.shiftFFT(ref, delta) - res).max() < 1e-12, "shift with FFTs works")
  File "/«BUILDDIR»/pyfai-0.12.0+dfsg/.pybuild/pythonX.Y_2.7/build/pyFAI/utils.py", line 847, in shiftFFT
    fft = fftw3.Plan(input_, output, direction='forward', flags=['estimate'])
  File "/usr/lib/python2.7/dist-packages/fftw3/planning.py", line 351, in __init__
    self.create_plan(inarray,outarray)
  File "/usr/lib/python2.7/dist-packages/fftw3/planning.py", line 374, in create_plan
    nthreads=self.nthreads)
  File "/usr/lib/python2.7/dist-packages/fftw3/planning.py", line 272, in _create_plan
    _cal_flag_value(flags))
  File "/usr/lib/python2.7/dist-packages/fftw3/planning.py", line 203, in _create_complex_plan
    direction, flags)
ArgumentError: argument 3: <type 'exceptions.TypeError'>: array must have flags ['C_CONTIGUOUS', 'ALIGNED', 'WRITEABLE']

======================================================================
ERROR: test_gaussian_filter (pyFAI.test.test_utils.TestUtils)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«BUILDDIR»/pyfai-0.12.0+dfsg/.pybuild/pythonX.Y_2.7/build/pyFAI/test/test_utils.py", line 136, in test_gaussian_filter
    blurred2 = utils.gaussian_filter(self.flat, sigma, mode=mode)
  File "/«BUILDDIR»/pyfai-0.12.0+dfsg/.pybuild/pythonX.Y_2.7/build/pyFAI/utils.py", line 231, in gaussian_filter
    fft = fftw3.Plan(fftIn, fftOut, direction='forward')
  File "/usr/lib/python2.7/dist-packages/fftw3/planning.py", line 351, in __init__
    self.create_plan(inarray,outarray)
  File "/usr/lib/python2.7/dist-packages/fftw3/planning.py", line 374, in create_plan
    nthreads=self.nthreads)
  File "/usr/lib/python2.7/dist-packages/fftw3/planning.py", line 272, in _create_plan
    _cal_flag_value(flags))
  File "/usr/lib/python2.7/dist-packages/fftw3/planning.py", line 203, in _create_complex_plan
    direction, flags)
ArgumentError: argument 3: <type 'exceptions.TypeError'>: array must have flags ['C_CONTIGUOUS', 'ALIGNED', 'WRITEABLE']

**Comment by picca** [comment]
Just for info this bug will block the migration into Debian testing.

**Comment by picca** [comment]
Here you can find all the failing buildlog

https://buildd.debian.org/status/package.php?p=pyfai

python-fftw ?

**Comment by kif** [comment]
On Wed, 17 Aug 2016 23:14:32 -0700
picca <notifications@github.com> wrote:

> Here you can find all the failing buildlog
> 
> https://buildd.debian.org/status/package.php?p=pyfai
> 
> python-fftw ?

Nop the solution is to drop the dependency on fftw and relay on the pure numpy version.

Unfortunately this will be for 0.13. do we have enough time before debian 9?

Cheers,

Jérôme

**Comment by picca** [comment]
Hello,

I removed the python-fftw dependency and now it works everywhere except on ppc64el

here the log

https://buildd.debian.org/status/fetch.php?pkg=pyfai&arch=ppc64el&ver=0.12.0%2Bdfsg-5&stamp=1472318941

good luck.

The freeze is around February but I would like to have something ok before December if it is possible for you.

Febuary will be the Debian freeze, but other freeze stages will start around November.

**Comment by kif** [comment]
On Mon, 29 Aug 2016 03:29:02 -0700
picca <notifications@github.com> wrote:

> Hello,
> 
> I removed the python-fftw dependency and now it works everywhere except on ppc64el
> 
> here the log
> 
> https://buildd.debian.org/status/fetch.php?pkg=pyfai&arch=ppc64el&ver=0.12.0%2Bdfsg-5&stamp=1472318941

Hi Fred,

Thanks for the feed-back.

The error message :
  File "/«BUILDDIR»/pyfai-0.12.0+dfsg/.pybuild/pythonX.Y-dbg_2.7/build/pyFAI/test/test_geometry.py", line 280, in test_corner_array
    self.assert_(numpy.allclose(py_res, cy_res, atol=2.9e-5), "data:%s, space: %s delta: %s" % (data, space, delta))
AssertionError: data:{'poni1': 0.07803878450256929, 'poni2': 0.2601779472529494, 'rot1': -0.33177239820033455, 'wavelength': 1e-10, 'rot3': 0.2928945825578625, 'rot2': 0.2762729953307118, 'detector': 'Pilatus300k', 'dist': 0.43544642285972124}, space: 2th_rad delta: 6.28319

This typically looks like the random error we have for a while in pyFAI (the test case is based on a random  geometry). 
There is a (partial) fix in #issue 391 
where the azimuthal result is separated from the radial part.
The radial part is checked at 1e-5 (hence better than currently the
2.9e-5) while the number of non-matching pixel (at the same precision)
on the azimuthal part is limited. Here the error is 2pi due to rounding
errors !

> 
> good luck.
> 
> The freeze is around February but I would like to have something ok before December if it is possible for you.
> 
> Febuary will be the Debian freeze, but other freeze stages will start around November.

Thanks for the information.

Cheers,

-- 
Jérôme Kieffer
tel +33 476 882 445

**Comment by kif** [comment]
fixed
