### ISSUE TITLE
RuntimeWarning: invalid value encountered in true_divide

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#406]
Hello

While playing with pyFAI, I got this warning message.

/usr/lib/python2.7/dist-packages/pyFAI/azimuthalIntegrator.py:2339: RuntimeWarning: invalid value encountered in true_divide
  sigma = numpy.sqrt(a) / b / normalization_factor

b = [  4.88187543   9.26802288  12.14924642 ...,   1.3082323    0.81447655
   0.32351741] 

b.min() -> 0.0
b.max() ->  88.0389081194

So Indeed dividing by 0.0 is a problem.

**Comment by picca** [comment]
Here a example of the output

[lut.pdf](https://github.com/silx-kit/pyFAI/files/452220/lut.pdf)

So I have zero where my detector (XPAD) has holes.   ok no count but no count is an information, Not available is a better interpretation of the reallity :)

**Comment by kif** [comment]
actually not as the line after is written:
sigma[b == 0] = dummy if dummy is not None else self._empty

so NaN are replaced by self._empty (which can be NaN but more often people prefer 0)

Here:
b=number of pixels (fractional)
a=summed intensity 
if b is 0, one can assume a is also 0. so one could say:
b[b==0]=1 
But I did not want to do this assumption. Especially that b could be <1 and it would look odd to have an empty bin more populated than an almost empty one.

**Comment by kif** [comment]
what did you do to get this curve ?

**Comment by kif** [comment]
in multi-geometry I just avoided the warning with this trick:
I = sum / numpy.maximum(count, EPS32 - 1)
I[count <= (EPS32 - 1)] = self.empty

would you prefer ?

**Comment by picca** [comment]
Hello Jerome,

In order to create this curve, I extended the poni with a rotation matrix for now whcih talke into account the diffractometer position where the calibration was done.
Then I generate a poni  for each position of the diffractometer during a scan.

I think that if there is no pixel in a bin, the Intensity should be zero and that's all.

**Comment by kif** [comment]
Empty is "0" by default but some beamlines want to personalize it. See #425

**Comment by vallsv** [comment]
Should we close this issue?

**Comment by picca** [comment]
ok
