### ISSUE TITLE
Poni vs. np.min(r) vs. xy center

### ISSUE THREAD

**Issue by CJ-Wright** [silx-kit/pyFAI#409]
So I have ran into an interesting discrepancy in the following code.
```python 
from pyFAI.geomtry import Geometry
geo = Geometry(
    detector='Perkin', pixel1=.0002, pixel2=.0002,
    dist=2.056529e-01,
    poni1=.209, poni2=.207,
    rot1=-0.001397, rot2=0.001836, rot3=0.000669
    wavelength=1.828000e-11)
shape = (2048, 2048)
r  = geo.rArray(shape)
center1 = np.unravel_index(np.argmin(r), shape)
center2 = geo.poni1/200e-6, geo.poni2/200e-6
print(center1, center2)
print(r[center1], r[center2])
```
However, these don't seem to agree with where the center is. Also this doesn't agree with the x, y center quoted by `print(geo)`
Does anyone know what is going on?

In collaboration with @sbanerjee23.

**Comment by kif** [comment]
Hi Christopher,

What you are seeing is the effect of the tilt on the detector.
This is why pyFAI always presents the geometry object with 2 coordinate systems, one using the point of normal incidence as origin (default) and the one using the beam-center as reference.

Only when tilt is zero (i.e. rot1 = rot2 =0) the two are the same. 



Detector Perkin detector	 PixelSize= 2.000e-04, 2.000e-04 m
Wavelength= 1.828000e-11m
SampleDetDist= 2.056529e-01m	PONI= 2.090000e-01, 2.070000e-01m	rot1=-0.001397  rot2= 0.001836  rot3= 0.000669 rad
DirectBeamDist= 205.653mm	Center: x=1036.436, y=1046.888 pix	Tilt=0.132 deg  tiltPlanRotation= 52.733 deg

**Comment by sbanerjee23** [comment]
Thanks for the quick response @kif, this makes sense to me.

**Comment by CJ-Wright** [comment]
So is it safe to use`np.argmin(r)` as the center of the detector? What does pyFAI use for its integration as the detector center?

**Comment by kif** [comment]
On Fri, 09 Sep 2016 04:44:17 -0700
"Christopher J. Wright" <notifications@github.com> wrote:

> So is it safe to use`np.argmin(r)` as the center of the detector? What does pyFAI use for its integration as the detector center?

The formula is defined here:
https://github.com/silx-kit/pyFAI/blob/master/pyFAI/units.py#L73

If you need the center of the detector, there is a function to
calculate it. No need to initiate the whole array to get the center!

https://github.com/silx-kit/pyFAI/blob/master/pyFAI/geometry.py#L1260

Cheers,
-- 
Jérôme Kieffer

**Comment by CJ-Wright** [comment]
Thank you very much!
