### ISSUE TITLE
Distorsion.uncorrect does not seem to uncorrect at all...

### ISSUE THREAD

**Issue by degeuser** [silx-kit/pyFAI#418]
Hi,

I was testing the distortion module, in order to display raw and/or "corrected" images (for mask editing, among other things) on of D2AM Xpad's and for fun tried to display
1) image
2) dis.correct(image)
3) dis.uncorrect(dis.correct(image))[0]

Whithin reasonable information loss, 3) should be looking close to 1), but it does not appear so:
![2016-09-15 14_57_15-saxs processing](https://cloud.githubusercontent.com/assets/20084227/18550662/36a3036a-7b55-11e6-8c57-3f0a274e1465.png)

Not sure what is wrong here...

Cheers,
Fred

**Comment by kif** [comment]
On Thu, 15 Sep 2016 06:03:56 -0700
degeuser <notifications@github.com> wrote:

> Hi,
> 
> I was testing the distortion module, in order to display raw and/or "corrected" images (for mask editing, among other things) on of D2AM Xpad's and for fun tried to display
> 1) image
> 2) dis.correct(image)
> 3) dis.uncorrect(dis.correct(image))[0]
> 
> Whithin reasonable information loss, 3) should be looking close to 1), but it does not appear so:
> ![2016-09-15 14_57_15-saxs processing](https://cloud.githubusercontent.com/assets/20084227/18550662/36a3036a-7b55-11e6-8c57-3f0a274e1465.png)
> 
> Not sure what is wrong here...
> 
> Cheers,
> Fred

Hi Fred,
you probably spotted a bug as the distortion correction was originally
done for wrapping/unwrapping while keeping the same size.

The uncorrect part is probably not right: there is obviouly an aligment
issue.

Thanks for reporting the bug.

Cheers,

Jerome

**Comment by degeuser** [comment]
Thanks Jerome,

Yes, I figured as much, and it does actually sort of work when Distorsion is used with resize argument as False
![2016-09-16 09_35_03-saxs processing](https://cloud.githubusercontent.com/assets/20084227/18578561/0461d9a2-7bf1-11e6-943b-480db248d4b2.png)

But this is obviously not the way to go for discontinuous detectors such as the imxpad.

Cheers
Fred

**Comment by kif** [comment]
Dear Frederic,

It looks like the offset along the vertical axis is wrong ... could you provide me the input image and the  detector specification you used ... in #426, Fred Picca is suggesting a change in geometry for this kind of detectors. it would help me validate his code.

Moreover do you have a pair of images WOS+SAXS of a calibrant taken simulaneously ?

Cheers,

Jerome

**Comment by degeuser** [comment]
Hi Jerome, 

I certainly can. Do you have access to the /data/bm02 mount on ESRF machines ? If so I can give your the list of files you need.

The image above was taken on the D7 CdTe Xpad for which we tried (Nils, myself, you) more or less independently to create a h5 description.

Let me know if you have access locally to the bm02 data so that I send you the list of files locations.

Fred

**Comment by kif** [comment]
On Thu, 22 Sep 2016 00:09:12 -0700
degeuser <notifications@github.com> wrote:

> Hi Jerome, 
> 
> I certainly can. Do you have access to the /data/bm02 mount on ESRF machines ? If so I can give your the list of files you need.

yes, I have access

> 
> The image above was taken on the D7 CdTe Xpad for which we tried (Nils, myself, you) more or less independently to create a h5 description.


There was no flight tube in place for testing the D7, was there ? Fred
Picca submitted a patch which is for the "Silicon" based detector, not
the CdTe. Their behaviors regarding the corner pixels is different.

Cheers,
-- 
Jérôme Kieffer
tel +33 476 882 445

**Comment by degeuser** [comment]
There was a flight tube. The whole SAXS setup (down to the detector) was under vacuum. The image above were recorded from a glassy carbon sample.
I am emailing you a list of file for testing.

**Comment by kif** [comment]
Coming back to this issue ... there is solution in simply "inverting" the sparse matrix (which is not square).
You can have a look there:
https://github.com/kif/pyFAI/blob/containers/sandbox/distortion_i418.ipynb

This method is likely to be implemented in pyFAI soon: Single-liner, it works and it slow enough to prevent people misusing it :)
