### ISSUE TITLE
XPad_flat geometry description is wrong ?

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#426]
Hello, I will put my investigations here :)

here my haskell code which correspond to the  xpad_flat pixel coordinates.

    coordinates Xpad32 (NptPoint x y) = fromList [g (round y), f (round x), 0]
      where
        chipw = 80
        chiph = 120
        pixel = 130e-6
        bigPixelwidthFactor = 2.5
        bigPixelWidth = pixel * bigPixelwidthFactor
        interModule = 3.57e-3

        -- width
        w :: Int -> Double
        w i'
          | i' == chipw * 1 - 1 = bigPixelWidth
          | i' == chipw * 1 = bigPixelWidth
          | i' == chipw * 2 - 1 =bigPixelWidth
          | i' == chipw * 2 = bigPixelWidth
          | i' == chipw * 3 - 1 = bigPixelWidth
          | i' == chipw * 3 = bigPixelWidth
          | i' == chipw * 4 - 1 = bigPixelWidth
          | i' == chipw * 4 = bigPixelWidth
          | i' == chipw * 5 - 1 = bigPixelWidth
          | i' == chipw * 5 = bigPixelWidth
          | i' == chipw * 6 - 1 = bigPixelWidth
          | i' == chipw * 6 = bigPixelWidth
          | otherwise = pixel
  
        f :: Int -> Double
        f 0 = (w 0) / 2
        f i' = f (i' - 1) + (w (i' - 1)) / 2 + (w i') / 2
  
        -- height
        module' :: Int -> Int
        module' j = div j chiph
  
        g :: Int -> Double
        g j = pixel / 2.0 + (pixel * (fromIntegral j)) + interModule * fromIntegral (module' j)

When I play with this, it seems that the width part is ok but the height one is not.

(NptPoint {nptPointX = 0.0, nptPointY = 0.0},fromList [6.5e-5,6.5e-5,0.0])
(NptPoint {nptPointX = 79.0, nptPointY = 0.0},fromList [6.5e-5,1.0432500000000025e-2,0.0])
(NptPoint {nptPointX = 80.0, nptPointY = 0.0},fromList [6.5e-5,1.0757500000000024e-2,0.0])
(NptPoint {nptPointX = 312.0, nptPointY = 0.0},fromList [6.5e-5,4.179500000000027e-2,0.0])
(NptPoint {nptPointX = 559.0, nptPointY = 0.0},fromList [6.5e-5,7.507500000000024e-2,0.0])
(NptPoint {nptPointX = 0.0, nptPointY = 1.0},fromList [1.9499999999999997e-4,6.5e-5,0.0])
(NptPoint {nptPointX = 0.0, nptPointY = 119.0},fromList [1.5535e-2,6.5e-5,0.0])
(NptPoint {nptPointX = 0.0, nptPointY = 120.0},fromList [1.9235e-2,6.5e-5,0.0])

If I do the same with the pyFAI detector, I get

    import pyFAI

    det = pyFAI.detectors.Xpad_flat()
    coord = det.calc_cartesian_positions()

    def p(x: int, y:int) -> (float, float):
        print((x, y), (coord[1][y][x], coord[0][y][x]))

    p(0, 0)
    p(79, 0)
    p(80, 0)
    p(312, 0)
    p(559, 0)
    p(0, 1)
    p(0, 119)
    p(0, 120)

    (0, 0) (6.5e-05, 6.5e-05)
    (79, 0) (0.0104325, 6.5e-05)
    (80, 0) (0.0107575, 6.5e-05)
    (312, 0) (0.041795, 6.5e-05)
    (559, 0) (0.075075001, 6.5e-05)
    (0, 1) (6.5e-05, 0.000195)
    (0, 119) (6.5e-05, 0.015632499)
    (0, 120) (6.5e-05, 0.019527499)

If you compare both version, you will see a difference.

let's speak about the x=0, y=119 pixel

    (NptPoint {nptPointX = 0.0, nptPointY = 119.0},fromList [1.5535e-2,6.5e-5,0.0])
    (0, 119) (6.5e-05, 0.015632499)

there is a difference of

    0.015632499 - 1.5535e-2 = 9.749900000000089e-5

this represent 

    9.75e-5 / 119 = 8.19327731092437e-7 per pixel.

If I do the computation by hand

for 119 pixels of 130 micrometer, I have

    Prelude> 130e-6*119 + 65e-6
    1.5535e-2

which is the haskell version and not the pyFAI version (0.015632499).

at the end the difference is

    (NptPoint {nptPointX = 0.0, nptPointY = 959.0},fromList [0.149725,6.5e-5,0.0])
    (0, 959) (6.5e-05, 0.152455)

so

    0.152455 - 0.149725 = 2.73000000000001e-3

    Prelude> 2.73000000000001e-3 / 130e-6
    21.00000000000008 pixels ???

what is your opinion about this problème.

**Comment by picca** [comment]
![figure_1](https://cloud.githubusercontent.com/assets/2741482/18635158/51dbcb30-7e84-11e6-84f3-b5d9c199cdca.png)

blue: pyfai
green: haskell

as we can see, the slope is "almost" identical on both curves,but the big step do not seems equal.

here a close up of the first step

![figure_2](https://cloud.githubusercontent.com/assets/2741482/18635268/c1869316-7e84-11e6-81a1-a27eef50cfdb.png)


I need to verify if there is a 2.5 pixel also in the y direction.

**Comment by picca** [comment]
confirmation from Arek, there is no 2.5 pixels along the y axis.

**Comment by picca** [comment]
Another point just for reference, the big pixels of the xpad 3.1 are 130x320 µm

**Comment by kif** [comment]
On Mon, 19 Sep 2016 07:47:23 -0700
picca <notifications@github.com> wrote:

> Another point just for reference, the big pixels of the xpad 3.1 are 130x320 µm

Interesting

-- 
Jérôme Kieffer
tel +33 476 882 445

**Comment by kif** [comment]
According to my local python installation:
320/130. = 2.4615384615384617
so the 2.5 is then a rounding !

Is this true for any xpad detector, or is it specific to v3.1 ?

**Comment by picca** [comment]
Hello Jerome,
No for the 3.2 xpad ans other Imxpad the ratio is 2.5. I just put here the factor for the 3.1 which was used ate SOLEIL and D2AM :)

**Comment by kif** [comment]
OK ... a direct collaboration with ImXpad would be great !
PyFAI may be more appealing to them if the license switches to something they can distribute ?
Xenocs at least was interested

**Comment by picca** [comment]
Did Xenocs distribut his own code with a DFSG-free license ?
Same question for ImXPAD.

So here the problem I try to investigate.

In geometry.py it seems that the edges are deal the right way.

    def calc_pixels_edges(self):
        """
        Calculate the position of the pixel edges, specific to the S540, d5 detector
        """
        if self._pixel_edges is None:
            # all pixel have the same size along the vertical axis, some pixels are larger along the horizontal one
            pixel_size1 = numpy.ones(self.max_shape[0]) * self._pixel1
            pixel_size2 = self._calc_pixels_size(self.max_shape[1], self.module_size[1], self._pixel2)
            pixel_edges1 = numpy.zeros(self.max_shape[0] + 1)
            pixel_edges2 = numpy.zeros(self.max_shape[1] + 1)
            pixel_edges1[1:] = numpy.cumsum(pixel_size1)
            pixel_edges2[1:] = numpy.cumsum(pixel_size2)
            self._pixel_edges = pixel_edges1, pixel_edges2
        return self._pixel_edges

In direction 1 (vertical) there is no 2.5 half pixel size (ok)
In direction 2 (horizontal) there is 2.5 half pixel generated by _calc_pixels_size.

I would say, I am a little bit lost...

**Comment by kif** [comment]
On Tue, 20 Sep 2016 00:50:09 -0700
picca <notifications@github.com> wrote:

> Did Xenocs distribut his own code with a DFSG-free license ?

No, they don't want to distribute "their" added value.
Xenocs considers their added value is only the integration and user
interface.
What matters most to me is to have the science properly done (i.e.
calculation). So the important is to have feed-back on bugs. 
From that perspective, collaboration is possible and would be
profitable to everybody.

> Same question for ImXPAD.

I have no direct contact with them but it would probably solve many
issues you guys have at Soleil with ImXpad detectors. 

> In direction 1 (vertical) there is no 2.5 half pixel size (ok)
> In direction 2 (horizontal) there is 2.5 half pixel generated by _calc_pixels_size.

Can you generate a HDF5 file with the proper detector layout so that I can test here ?

thanks,

-- 
Jérôme Kieffer
tel +33 476 882 445

**Comment by picca** [comment]
This method does not compute the real edges of the pixels, since it does not take into account the gap between the modules. It computes sort of edges if the detectors had no gap.

pyFAI deals with the gap in the 

    def get_pixel_corners(self):
        """
        Calculate the position of the corner of the pixels

        @return:  4D array containing:
                    pixel index (slow dimension)
                    pixel index (fast dimension)
                    corner index (A, B, C or D), triangles or hexagons can be handled the same way
                    vertex position (z,y,x)
        """
        if self._pixel_corners is None:
            with self._sem:
                if self._pixel_corners is None:
                    pixel_size1 = self._calc_pixels_size(self.max_shape[0], self.module_size[0], self._pixel1)
                    pixel_size2 = self._calc_pixels_size(self.max_shape[1], self.module_size[1], self._pixel2)
                    # half pixel offset
                    pixel_center1 = pixel_size1 / 2.0  # half pixel offset
                    pixel_center2 = pixel_size2 / 2.0
                    # size of all preceeding pixels
                    pixel_center1[1:] += numpy.cumsum(pixel_size1[:-1])
                    pixel_center2[1:] += numpy.cumsum(pixel_size2[:-1])
                    # gaps
                    for i in range(self.max_shape[0] // self.module_size[0]):
                        pixel_center1[i * self.module_size[0]:
                                      (i + 1) * self.module_size[0]] += i * self.MODULE_GAP[0]
                    for i in range(self.max_shape[1] // self.module_size[1]):
                        pixel_center2[i * self.module_size[1]:
                                      (i + 1) * self.module_size[1]] += i * self.MODULE_GAP[1]

                    pixel_center1.shape = -1, 1
                    pixel_center1.strides = pixel_center1.strides[0], 0

                    pixel_center2.shape = 1, -1
                    pixel_center2.strides = 0, pixel_center2.strides[1]

                    pixel_size1.shape = -1, 1
                    pixel_size1.strides = pixel_size1.strides[0], 0

                    pixel_size2.shape = 1, -1
                    pixel_size2.strides = 0, pixel_size2.strides[1]

                    corners = numpy.zeros((self.shape[0], self.shape[1], 4, 3), dtype=numpy.float32)
                    corners[:, :, 0, 1] = pixel_center1 - pixel_size1 / 2.0
                    corners[:, :, 0, 2] = pixel_center2 - pixel_size2 / 2.0
                    corners[:, :, 1, 1] = pixel_center1 + pixel_size1 / 2.0
                    corners[:, :, 1, 2] = pixel_center2 - pixel_size2 / 2.0
                    corners[:, :, 2, 1] = pixel_center1 + pixel_size1 / 2.0
                    corners[:, :, 2, 2] = pixel_center2 + pixel_size2 / 2.0
                    corners[:, :, 3, 1] = pixel_center1 - pixel_size1 / 2.0
                    corners[:, :, 3, 2] = pixel_center2 + pixel_size2 / 2.0
                    self._pixel_corners = corners
        return self._pixel_corners

ok, the bug is here

                    pixel_size1 = self._calc_pixels_size(self.max_shape[0], self.module_size[0], self._pixel1)
                    pixel_size2 = self._calc_pixels_size(self.max_shape[1], self.module_size[1], self._pixel2)

we do not need the extra 2.5 pixels on the dimension1

so
                    pixel_size1 = numpy.ones(self.max_shape[0]) * self._pixel1
                    pixel_size2 = self._calc_pixels_size(self.max_shape[1], self.module_size[1], self._pixel2)

solve my issue :))

**Comment by kif** [comment]
done
