### ISSUE TITLE
[drawmask] set logarithmic scale by default 

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#438]
Diffraction data is not usable in linear scale.
The default should be logarithmic + colormap (inferno ?)

**Comment by vallsv** [comment]
+1
We should try the new thomas' colormap, to see the feed back

**Comment by kif** [comment]
On Mon, 03 Oct 2016 00:16:56 -0700
Valentin Valls <notifications@github.com> wrote:

> We should try the new thomas' colormap, to see the feed back

We agreed on inferno or magma (I prefer the former). They are all part of silx now.

-- 
Jérôme Kieffer
tel +33 476 882 445
