### ISSUE TITLE
Native pyFAI method for integration as a function of chi

### ISSUE THREAD

**Issue by tgdane** [silx-kit/pyFAI#442]
As far as I am aware there is not currently a method in pyFAI to integrate as a function of chi (rather than the radial unit), i.e., for extracting orientation/texture information around a specific ring. I currently do this using `integrate2d` (usually over a narrow radial range covering the ring) then summing along the radial axis. This is a common operation for many experiments and whilst it is simple to do, it would be great to have such a 1D function native to pyFAI.

There would be two approaches to this. The first would involve a modification at the core of the `integrate1d` function. This is what have done in my grazing-incidence [package](https://github.com/tgdane/pygix). In short you just switch the `pos0` and `pos1` scales/arrays such that `pos0` is then chi and `pos1` is radial. This then has to be handled in `units.py` and everything else that goes with it. I have used a master `integrate_1d` function, then have wrappers for `profile_sector`, `profile_chi` (also for box ROIs, having four 1D integrations was for me enough reason to make such a change). The `integrate_1d` function takes `process` kwarg, which it uses to select the appropriate `pos0` and `pos1` arrays. See wrappers starting [here](https://github.com/tgdane/pygix/blob/master/pygix/transform.py#L1130) and main function [here](https://github.com/tgdane/pygix/blob/master/pygix/transform.py#L1326). Of course throughout the pyFAI `integrate1d` function, `pos1` is often labelled as chi so this would require renaming these arrays/variables. 

The simpler approach (might be good to have it up and running in pyFAI in the short term) would be to write a simple wrapper:

``` python
def integrate_chi(self, data, npt_azim, radial_range=None, azim_range=None,
                  unit='q_nm^-1', **kwargs):
    # npt_rad is arbitrary as it will be flattened but need to provide something
    npt_rad = 20
    i, q, chi = self.integrated2d(data, npt_rad, npt_azim, radial_range=radial_range, 
                                  azim_range=azim_range, unit=unit, **kwargs)
    i = np.sum(i, axis=1)
    # of course with all the proper handling of result
    return i, chi
```

**Comment by kif** [comment]
On Tue, 11 Oct 2016 08:01:34 -0700
Thomas Dane <notifications@github.com> wrote:

> ```python
> def integrate_chi(self, data, npt_azim, radial_range=None, azim_range=None,
>                   unit='q_nm^-1', **kwargs):
>     # npt_rad is arbitrary as it will be flattened but need to provide something
>     npt_rad = 20
>     i, q, chi = self.integrated2d(data, npt_rad, npt_azim, radial_range=radial_range, 
>                                   azim_range=azim_range, unit=unit, **kwargs)
>     i = np.sum(i, axis=1)
>     # of course with all the proper handling of result
>     return i, chi

Hi Thomas,

We will implement a method with similar signature, but enabling the
look-up table integration which is much faster.

Cheers,

-- 
Jérôme Kieffer
