### ISSUE TITLE
[question] Masking Convention

### ISSUE THREAD

**Issue by CJ-Wright** [silx-kit/pyFAI#443]
Out of curiosity why is the masking convention for pyFAI 1 is a bad pixel to be masked and 0 is a good pixel not to be masked? I notised that this convention is [flipped](https://github.com/silx-kit/pyFAI/blob/561f0b8f46579708d16009f069305cd76b062509/pyFAI/azimuthalIntegrator.py#L290) to 1 is good, 0 is bad in the code itself.

**Comment by vallsv** [comment]
I understand that when pyFAI was created people was using both convention 0=bad or 1=bad, without any consensus. I guess, with his experience, Jerome was finally convinced to choose the more convenient. But i don't remember the exact explanation.

**Comment by kif** [comment]
Valentin is right ... both convention have been used (this is closely related to the "dummy"  story... )
Currently the mask should be 1 (or True) for masked out pixels.
It is True that it needs to be inverted for numpy based algorithms but they are left only for example and I don't expect many people to use the numpy based algorithms as they are a least 5x slower.  

There is now a common preprocessing code (https://github.com/kif/pyFAI/blob/master/pyFAI/ext/preproc.pyx) which does apply the mask and should soon be used by most  integrator engines.

**Comment by kif** [comment]
see #425
