### ISSUE TITLE
[pyFAI-integrate] divide by monitor value

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#446]
similar to what is done on pyFAI-average

**Comment by vallsv** [comment]
I see it as a way to initialize the normalization factor param you show us yesterday. Do you think it is reasonable? Or it should normalize the raw data?

**Comment by kif** [comment]
On Wed, 19 Oct 2016 00:01:06 -0700
Valentin Valls <notifications@github.com> wrote:

> I see it as a way to initialize the normalization factor param you show us yesterday. Do you think it is reasonable? Or it should normalize the raw data?
> 

Normalizing the processed data is much faster than normalizing the raw data.

-- 
Jérôme Kieffer
tel +33 476 882 445
