### ISSUE TITLE
[pyFAI-calibrate] does not work on stretch

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#448]
Hello, we just tested pyFAI on the lateste ubuntu, but this is the same on Debian.

python-qt4  doen not provide the webkit  widget anymore.
this cause some troubles when using pyFAI-calibrate.

I do not know if pyFAI use this module but it would be great to remove it from the gui_utils module in order to solve this issue.

Cheers

**Comment by vallsv** [comment]
Hi, Frederic.
Right now the webkit module is used to display help. But it is better (and easy) to remove it and use the default system browser.
I will do it soon.
Thanks for the feed back.

**Comment by vallsv** [comment]
This patch should fix the problem. QtWebKit is not anymore requested.

**Comment by kif** [comment]
On Fri, 21 Oct 2016 12:09:17 -0700
picca <notifications@github.com> wrote:

> Hello, we just tested pyFAI on the lateste ubuntu, but this is the same on Debian.
> 
> python-qt4  doen not provide the webkit  widget anymore.
> this cause some troubles when using pyFAI-calibrate.
> 
> I do not know if pyFAI use this module but it would be great to remove it from the gui_utils module in order to solve this issue.

Hi Fred,

Are you speaking of the development version ? of the v0.12?
We will soon switch to a dependency on silx for all releted to Qt.
The mask widget is already depending on silx.

In silx we still use Qt4 for python2 and Qt5 for python3 but as you
guess everything works with Qt5 except that most people dont haave Qt5
yet (especially at ESRF)

Cheers,

Jerome
