### ISSUE TITLE
Please support PyQt5

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#450]
Hello,

It would be nice to support PyQt5 in pyFAI.
You can have a look at the python-qtpy in order to support multiple version of Qt.

Cheers

**Comment by vallsv** [comment]
Hi,

Soon we will create, i guess, a dependancy on `silx` which provide the same feature.

**Comment by picca** [comment]
Hello, just for info. I think that this silx dependency should not be mandated for Stretch, it is too late in the release process to my opinion.

cheers

**Comment by vallsv** [comment]
This patch should to the job https://github.com/silx-kit/pyFAI/pull/452

**Comment by kif** [comment]
Like silx, we will support Qt4&pyside in Python2.7 and PyQt5 in Python 3.5+
