### ISSUE TITLE
[OSX] --no-cython is not more working ...

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#475]
Consequence: it takes ages to develop on OSX (+ lot of battery to compile)

**Comment by vallsv** [comment]
Maybe we should compile everything without OpenMP. If you dont want to use cython and dont have openmp there is an inconsistency cause .c files uses openmp.

**Comment by vallsv** [comment]
By the way, do you use ccache?

**Comment by kif** [comment]
On Thu, 10 Nov 2016 04:50:53 -0800
Valentin Valls <notifications@github.com> wrote:

> By the way, do you use ccache?

Actually I was considering installing ccache to get rid of this issue.

My idea would be, on OSX to have this behaviour:

 * python setup.py -> force cythonize
 * python setup.py --no-cython -> disable cythonize

This would be achieved by just flipping 2 tests.
I am validating it.

-- 
Jérôme Kieffer
tel +33 476 882 445

**Comment by kif** [comment]
ccache helps as bit indeed but it still runs cythonize and link:
"python setup.py" takes 90s
