### ISSUE TITLE
radial_range not read from pyFAI-integrate on Windows 10

### ISSUE THREAD

**Issue by jetteodder** [silx-kit/pyFAI#481]
I've been trying to use pyFAI-integrate-py (pyFAI 0.12.0) on Windows 10 to do radial integration with various azimuthal and radial ranges. I am able to use different azimuthal ranges, but the radial range never seem to be read. I want to use unit=r_mm, but I've also attempted a 2theta radial range without being able to set the limits. For unit=r_mm I assume the values of the radial range should be in mm, but I've also attempted pixels and meters with no more success, I always get the entire data range.  Please help.

**Comment by kif** [comment]
I will have a look.

**Comment by vallsv** [comment]
Hi.  There was effectively a problem on the radial range introduced by myself.
It will be fixed on the master soon, and on the version 0.13 soon.

**Comment by jetteodder** [comment]
Thank you very much for looking into this.

Jette Oddershede

**Comment by vallsv** [comment]
Just in case, here is the fix https://github.com/silx-kit/pyFAI/pull/494/commits/a10e09c40b41aedb08e36d20eb1761438dc3619f
Thanks a lot for your report.
