### ISSUE TITLE
[doc] Clean up refinement2D.py

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#485]
It contains a lot of things like that
```
        ???

        :param axis: ???
        :type axis: ???
        :param dx: ???
        :type dx: ???

        :return: ???
        :rtype: ???
```

It would be better to remove it

**Comment by kif** [comment]
On Thu, 24 Nov 2016 08:54:38 -0800
Valentin Valls <notifications@github.com> wrote:

> It contains a lot of things like that
> ```
>         ???
> 
>         :param axis: ???
>         :type axis: ???
>         :param dx: ???
>         :type dx: ???
> 
>         :return: ???
>         :rtype: ???
> ```
> 
> It would be better to remove it
> 
I think refinement2d -> sandbox. I can't remember why I wrote that.
It is probably not used by anyone.

**Comment by vallsv** [comment]
Ok, lets check it
