### ISSUE TITLE
ERROR: testEigerMask (pyFAI.test.test_scripts.TestScriptsHelp)

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#504]
Hello whilepreparing the Debian package 0.13 I got this error using python2.7-dbg

```
======================================================================
ERROR: testEigerMask (pyFAI.test.test_scripts.TestScriptsHelp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<BUILDDIR>>/pyfai-0.13.0+dfsg/.pybuild/pythonX.Y-dbg_2.7/build/pyFAI/test/test_scripts.py", line 102, in testEigerMask
    self.executeScipt("eiger-mask")
  File "/<<BUILDDIR>>/pyfai-0.13.0+dfsg/.pybuild/pythonX.Y-dbg_2.7/build/pyFAI/test/test_scripts.py", line 82, in executeScipt
    for k, v in self.env.items():
AttributeError: 'TestScriptsHelp' object has no attribute 'env'
----------------------------------------------------------------------
Ran 309 tests in 702.181s
```

**Comment by picca** [comment]
Maybe this is related to this problem...


Stderr:
Traceback (most recent call last):
  File "/<<BUILDDIR>>/pyfai-0.13.0+dfsg/scripts/eiger-mask", line 44, in <module>
    import h5py
  File "/usr/lib/python2.7/dist-packages/h5py/__init__.py", line 24, in <module>
    from . import _errors
ImportError: /usr/lib/python2.7/dist-packages/h5py/_errors.i386-linux-gnu.so: undefined symbol: Py_InitModule4
[21680 refs]

**Comment by picca** [comment]
This is an issue because in order to backport pyFAI on Debian8, we need to be able to skip tests if the debug modules is not available .

**Comment by vallsv** [comment]
Hi. Thanks for the feed back.
Can you try to use ipython (or anything else) and just try to import h5py?
It looks like h5py import fails by itself.

**Comment by vallsv** [comment]
Hi Frederic,

Sorry to be late, but we was in the hurry. Anyway, we just release PyFAI 
v0.13.1 to backport 3 issues from the develop branch to the 0.13.

It should fix this issue relative to eiger-mask test.

Let us know if something still blocking.

**Comment by vallsv** [comment]
Should be fixed
