### ISSUE TITLE
Next generation averaging mechanism: follow the path

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#520]
This issue describes the transition path from the current integration mechanism to the next generation.

Currently:
Preproc: I = (Raw-Dark) / (Flat x SolidAngle x Polarization)
Averaging: Im = histogram(pos, weights=I) / histogrram(pos) 

Next Generation:
PreprocN: In = (Raw-Dark) 
             D: Id = (Flat x SolidAngle x Polarization)
Averaging: Im = histogram(pos, weights=In) / histogram(pos, weights=Id)

Advantage: Mathematically better with tilted detector, allows error propagation, ...
Draw-back: may be twice slower ! but we are fighting to make it fast again !

During this refactoring one will need to store 2 temporary arrays instead of one. I suggest to store it as and "array of struct" to allow subsequently to read it back again as an array of float2 in OpenCL.

During the refactoring, I would like to drop the "LUT" representation in favour of the "CSR" which is almost always faster.

This creates the given path:
- [x] write as pre-processing with split-output (array of struct: (num, denom)) in Cython
- [x] write the same in pure Python and validate
- [x] Write once again the same in OpenCL
- [x] Integration using 2 weighted numpy histograms
- [x] Integration using scipy.sparse matrix multiplication based on the CSR look-up table
- [x] Integration using cython histograms, combined, without splitting. Is it still faster ? 
- [x] Integration using cython sparse matrix multiplication, combined
- [x] Integration using OpenCL sparse matrix multiplication based on float2.

Each step will require a bunch of tests to validate the result.

**Comment by CJ-Wright** [comment]
You might also try Numba to help speed things up: http://numba.pydata.org/

**Comment by kif** [comment]
On Wed, 04 Jan 2017 09:30:58 -0800
"Christopher J. Wright" <notifications@github.com> wrote:

> You might also try Numba to help speed things up: http://numba.pydata.org/

I read a bit about numba ... it is very promising; it looks like the
future as it is just-in time compiled code which can run on multiple type of hardware.

I see a few problems:
* The CPU (LLVM optimized) code does not look parallel.
* The GPU code can run on nvidia hardware using CUDA or AMD hardware
  using HSA but the code needs to be adapted each time which does not
  make it portable.

With PyOpenCL we already got parallel code, compiled as needed and
running efficiently both on CPU and on GPU: the CPU code has been
compared with ahead of time compiled code from Cython and OpenCL still
is slightly faster than C-code. 

It would be interesting if you could provide some benchmarks as the
integration code is only a few dozens of lines:
* OpenCL:
  https://github.com/silx-kit/pyFAI/blob/master/pyFAI/resources/openCL/ocl_azim_CSR.cl#L56
* Cython
  https://github.com/silx-kit/pyFAI/blob/master/pyFAI/ext/splitPixelFullCSR.pyx#L562

Cheers,

Jerome

**Comment by kif** [comment]
This is now ready for 0.20
