### ISSUE TITLE
provide manylinux wheel for latest release

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#534]

**Comment by kif** [comment]
Isn't  0.13.1 availableon pypi ?

**Comment by vallsv** [comment]
No, right now it is only a tag, there's no build.

**Comment by kif** [comment]
On Mon, 06 Feb 2017 08:43:07 -0800
Valentin Valls <notifications@github.com> wrote:

> No, right now it is only a tag, there's no build.

Sources, ManyLinux1 wheels and MacOSX wheels have been uploaded together with the documentation on PyPI. 
Only windows is missing as I don't have access to such (virtual) hardware for now.

**Comment by CJ-Wright** [comment]
There is a [conda-forge 0.13.1 build](https://anaconda.org/conda-forge/pyfai).

**Comment by kif** [comment]
On Mon, 06 Feb 2017 12:32:15 -0800
"Christopher J. Wright" <notifications@github.com> wrote:

> There is a [conda-forge 0.13.1 build](https://anaconda.org/conda-forge/pyfai).

Thanks for the info. I may update the documentation accordingly. Does
this forge also provide wheels, beside tar-balls for anaconda ?
You may know manylinux wheels need to be built on a specifically
limited system (deactivating OpenMP) and they are not very efficient:
~20% slower than the native builds.

Nevertheless we still prefer working based on wheels as it helps us to
simplify the documentation and the continuous integration in a
multi-platform way.

By the way, manylinux wheels are available now.
https://pypi.python.org/pypi/pyFAI/0.13.1#downloads

Let's focus on the development of v0.14 as there is still huge work to do.

Cheers,

**Comment by vallsv** [comment]
Then i will upload the windows build on PyPi. BTW, nice to know there is a conda repository up-to-date !

**Comment by CJ-Wright** [comment]
I don't think it provides wheels, although I am not certain.
