### ISSUE TITLE
Azimuthal inpaining

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#557]
This a feature request for an ugly hack, requested by ID31 to paint (i.e. invent values) for missing pixel in their Pilatus detector.

**Comment by jonwright** [comment]
I (still) think this is a good idea to be explored.
It seems to be just calling geometry.calcfrom1d a few times to replace the masked values and iterate.
... but perhaps there is something more interesting via integrate2d and fourier analysis.
Did someone get it working already or are you in need of a proof of principle?

**Comment by kif** [comment]
On Thu, 20 Apr 2017 12:32:05 -0700
Jon Wright <notifications@github.com> wrote:

> I (still) think this is a good idea to be explored.
> It seems to be just calling geometry.calcfrom1d a few times to replace the masked values and iterate.
> ... but perhaps there is something more interesting via integrate2d and fourier analysis.
> Did someone get it working already or are you in need of a proof of principle?

I agree this is needed for proper Fourier analysis.

There is a jupyter notebook with the proof of principle. Basically it works.
It takes ~5s per image in pure python:
First 3 integrate2d, with a blank image without mask, then with the mask and finally with the data.
The 2D missing bins are then inpainted using a convolution in polar
space and backprojected in using a 2d bilinear intepolation.
Adding poissonian noise allows to finally "polish" the painted data. 

The convolution and the bilinear projection from polar to cartesian
space have been re-implemented in cython but not yet validated nor tested.
You will have to wait for another week to have it available.
I will commit the code as I work on it.

Cheers,

Jerome

**Comment by kif** [comment]
merged
