### ISSUE TITLE
Add conda installation to docs

### ISSUE THREAD

**Issue by CJ-Wright** [silx-kit/pyFAI#573]
There is a conda install for pyFAI!
Would it be possible to add something to this effect to the docs/readme?
A simple `conda install -c conda-forge pyfai` would most likely suffice (although we currently only have builds for Linux and OSX).

**Comment by kif** [comment]
On Fri, 19 May 2017 20:19:45 -0700
"Christopher J. Wright" <notifications@github.com> wrote:

> There is a conda install for pyFAI!

Thanks Christopher ,

> Would it be possible to add something to this effect to the docs/readme?
> A simple `conda install -c conda-forge pyfai` would most likely suffice (although we currently only have builds for Linux and OSX).

The most efficient is to provide a pull-request on the doc. As I don't use much anaconda and I have a very limited experience with it.
I just know pyFAI wheels install well on anaconda (may be a solution on windows).

I may update the doc only for the release, but this is not planed in the near future.

By the way, the current master has changed license to MIT.

Cheers,

Jerome

**Comment by vallsv** [comment]
BTW, how does it work? Cause we soon have dependency with `silx`.

**Comment by CJ-Wright** [comment]
You install [anaconda](https://www.continuum.io/downloads) or [miniconda](https://conda.io/miniconda.html). Then you run `conda install pyfai -c conda-forge` and it installs the software onto the system with pre-compiled binaries. [Info on conda-forge](https://conda-forge.github.io/) and [conda](https://conda.io/docs/index.html).

As for the new dep, I guess we'll have to package that too.
