### ISSUE TITLE
[calib2] Some comments

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#577]
A couple of bugs ...
In the mask/peak-picker/Geometry-fitting tabs, the image is by default zoomed in (quite a bit) with imxpad images. It was OK in the Experiment settings (?)

The peak-picking does not work due to a change in API in silx:
/usr/lib/python2.7/dist-packages/pyFAI/gui/calibration/utils.pyc in getFreeColorRange(colormap)
     42     import matplotlib.cm
     43     from silx.gui.plot import Colors
---> 44     cmap = Colors.getMPLColormap(name)
     45     norm = matplotlib.colors.Normalize(0, 255)
     46     scalarMappable = matplotlib.cm.ScalarMappable(norm=norm, cmap=cmap)

AttributeError: 'module' object has no attribute 'getMPLColormap'

**Comment by vallsv** [comment]
Yes, have to be fixed

**Comment by vallsv** [comment]
Fixed on a previous PR https://github.com/silx-kit/pyFAI/pull/578
