### ISSUE TITLE
[MultiGeometry] For consistency rename "monitors" into "normalization_factors"

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#605]
Fred, what do you think ?
@picca

**Comment by picca** [comment]
Hello Jerome,
What do you want me to comment about ? Can you explain what is the plan about this issue ?

**Comment by kif** [comment]
On Fri, 16 Jun 2017 01:51:24 -0700
picca <notifications@github.com> wrote:

> Hello Jerome,
> What do you want me to comment about ? Can you explain what is the plan about this issue ?

Hi Fred,

In AzimuthalIntegrator, we use "normalization_factor" as keyword for the same feature. 
It would make sense to use the same keyword wherever it is possible.

I guess this feature is used only at Soleil as you provided the patch
in November 2016.

As we are about to change the way integration is performed this
normalization factor should be integrated with the other normalizations like
solid angle, polarization, flatfield, .... This also simplifies the
management of "dummy values": those values are processed like the other 
except their normalization is "0".

Cheers,

-- 
Jérôme Kieffer
tel +33 476 882 445

**Comment by picca** [comment]
Thanks for the explanation.

ok for me :))
