### ISSUE TITLE
[error] No open mp

### ISSUE THREAD

**Issue by CJ-Wright** [silx-kit/pyFAI#635]
It seems that `--no-openmp` is no longer supported, but its still in the `README.rst`
https://travis-ci.org/conda-forge/pyfai-feedstock/jobs/256729331#L2219

**Comment by vallsv** [comment]
The setup.py was cleaned up. It is supported as a `build` argument. Then you should still be able to use `python setup.py build --no-openmp`. I will fix the README.

**Comment by vallsv** [comment]
The README looks to be ok. Can you confirm `python setup.py build --no-openmp` is not working?

**Comment by CJ-Wright** [comment]
Sorry, I must have missed the change from install to build

**Comment by CJ-Wright** [comment]
The command not working is `python setup.py install --no-openmp`

**Comment by vallsv** [comment]
Yes, you have to use this one:
`python setup.py build --no-openmp install`

Then change of the behaviour was not on the release note. My bad. Then i close the issue.

**Comment by CJ-Wright** [comment]
Thank you!

**Comment by vallsv** [comment]
Thanks for the conda integration

**Comment by CJ-Wright** [comment]
No problem, let me know if you ever want to be on the maintainers list
