### ISSUE TITLE
.ipynb_checkpoints in the source package (normal ?)

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#637]
Hello guyes, while I am preparing the 0.14 package for Debian.
I found .ipynb_checkpoints directories in all the notebook tutorials.
Is it normal ?

They take plenty of room.

**Comment by vallsv** [comment]
Definitely not. I would say is should not be there on the git repo too. Did you try from a fresh git clone?

It can easily be filtered out using the `setup.py` or on the `MANIFEST`

**Comment by picca** [comment]
No I just downloaded the 0.14.0 package via pip using git-buildpackage.

**Comment by vallsv** [comment]
BTW i release a 0.14.1 version to fix debian issue on scripts, but it is not uploaded in pypi.

**Comment by vallsv** [comment]
It means our packages on pypi are big for nothing? Jerome complains about the size but we did not investigate the problem at this time.

**Comment by picca** [comment]
yes they contained thoses big files.

**Comment by kif** [comment]
I confirm the bug
