### ISSUE TITLE
which keyring should I use to verify the pip signature

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#638]
Hello, I will now check the signature of the package. So I need to know whcih pgp key I need to use in order to do this.

thanks

**Comment by vallsv** [comment]
The ones from my git account or the one from the jerome account.

**Comment by picca** [comment]
Can you give me the signatures please

**Comment by picca** [comment]
I prefer the long keyid, the short one is not secure.

**Comment by vallsv** [comment]
Is this one is fine? https://pgp.mit.edu/pks/lookup?search=valentin.valls%40esrf.fr&op=index

**Comment by picca** [comment]
yes, I just need also the one from jerome whci is not on my computer now. Do you know it ?

**Comment by vallsv** [comment]
It looks to be this one https://pgp.mit.edu/pks/lookup?op=vindex&search=0x9EA87A4CB8C8CE7C

**Comment by picca** [comment]
:~/Debian/pyfai/pyfai$ uscan --verbose
uscan info: uscan (version 2.17.6+deb9u1) See uscan(1) for help
uscan info: Scan watch files in .
uscan info: Check debian/watch and debian/changelog in .
uscan info: package="pyfai" version="0.13.0+dfsg-1" (as seen in debian/changelog)
uscan info: package="pyfai" version="0.13.0+dfsg" (no epoch/revision)
uscan info: ./debian/changelog sets package="pyfai" version="0.13.0+dfsg"
uscan info: Process ./debian/watch (package=pyfai version=0.13.0+dfsg)
uscan info: Found upstream signing keyring: debian/upstream/signing-key.asc
uscan info: opts: repacksuffix=+dfsg,pgpsigurlmangle=s/$/.asc/,uversionmangle=s/(rc|a|b|c)/~$1/,dversionmangle=s/\+dfsg//
uscan info: line: http://pypi.debian.net/pyFAI/pyFAI-(.+)\.(?:zip|tgz|tbz|txz|(?:tar\.(?:gz|bz2|xz)))
uscan info: Parsing repacksuffix=+dfsg
uscan info: Parsing pgpsigurlmangle=s/$/.asc/
uscan info: Parsing uversionmangle=s/(rc|a|b|c)/~$1/
uscan info: Parsing dversionmangle=s/\+dfsg//
uscan info: line: http://pypi.debian.net/pyFAI/pyFAI-(.+)\.(?:zip|tgz|tbz|txz|(?:tar\.(?:gz|bz2|xz)))
uscan info: Last orig.tar.* tarball version (from debian/changelog): 0.13.0+dfsg
uscan info: Last orig.tar.* tarball version (dversionmangled): 0.13.0
uscan info: Requesting URL:
   http://pypi.debian.net/pyFAI/
uscan info: Matching pattern:
   (?:(?:http://pypi.debian.net)?\/pyFAI\/)?pyFAI-(.+)\.(?:zip|tgz|tbz|txz|(?:tar\.(?:gz|bz2|xz)))
uscan info: Found the following matching hrefs on the web page (newest first):
   /pyFAI/pyFAI-0.14.0.tar.gz (0.14.0) index=0.14.0-1 
   /pyFAI/pyFAI-0.13.1.tar.gz (0.13.1) index=0.13.1-1 
   /pyFAI/pyFAI-0.13.0.tar.gz (0.13.0) index=0.13.0-1 
   /pyFAI/pyFAI-0.12.0.tar.gz (0.12.0) index=0.12.0-1 
   /pyFAI/pyFAI-0.11.0.tar.gz (0.11.0) index=0.11.0-1 
   /pyFAI/pyFAI-0.11.0.zip (0.11.0) index=0.11.0-0 
   /pyFAI/pyFAI-0.10.3.tar.gz (0.10.3) index=0.10.3-1 
   /pyFAI/pyFAI-0.10.2.tar.gz (0.10.2) index=0.10.2-1 
   /pyFAI/pyFAI-0.10.0.tar.gz (0.10.0) index=0.10.0-1 
   /pyFAI/pyFAI-0.9.2.tar.gz (0.9.2) index=0.9.2-1 
uscan info: Matching target for downloadurlmangle: http://pypi.debian.net/pyFAI/pyFAI-0.14.0.tar.gz
uscan info: Upstream URL (downloadurlmangled):
   http://pypi.debian.net/pyFAI/pyFAI-0.14.0.tar.gz
uscan info: Newest upstream tarball version selected for download (uversionmangled): 0.14.0
uscan info: Download filename (filenamemangled): pyFAI-0.14.0.tar.gz
uscan: Newest version of pyfai on remote site is 0.14.0, local version is 0.13.0+dfsg
 (mangled local version is 0.13.0)
uscan:    => Newer package available from
      http://pypi.debian.net/pyFAI/pyFAI-0.14.0.tar.gz
uscan info: Not downloading, using existing file: pyFAI-0.14.0.tar.gz
uscan info: Downloading OpenPGP signature from
   http://pypi.debian.net/pyFAI/pyFAI-0.14.0.tar.gz.asc (pgpsigurlmangled)
   as pyFAI-0.14.0.tar.gz.pgp
uscan info: Requesting URL:
   http://pypi.debian.net/pyFAI/pyFAI-0.14.0.tar.gz.asc
uscan info: Verifying OpenPGP signature pyFAI-0.14.0.tar.gz.pgp for pyFAI-0.14.0.tar.gz
gpgv: Signature faite le jeu. 20 juil. 2017 16:36:15 CEST
gpgv:                avec la clef RSA 9EA87A4CB8C8CE7C
gpgv: Bonne signature de « Jerome Kieffer <jerome@terre-adelie.org> »
gpgv:                 alias « Jerome Kieffer <jerome.kieffer@esrf.fr> »
gpgv:                 alias « Jerome Kieffer <root@lintaillefer.esrf.fr> »
gpgv:                 alias « Jerome Kieffer <kieffer@lintaillefer.esrf.fr> »
gpgv:                 alias « Jerome Kieffer <jerome.kieffer@terre-adelie.org> »
uscan info: New orig.tar.* tarball version (oversionmangled): 0.14.0
uscan info: Executing internal command:
   mk-origtargz --package pyfai --version 0.14.0 --repack-suffix +dfsg --compression gzip --directory .. --copyright-file debian/copyright ../pyFAI-0.14.0.tar.gz
uscan info: New orig.tar.* tarball version (after mk-origtargz): 0.14.0+dfsg
uscan info: Successfully repacked ../pyFAI-0.14.0.tar.gz as ../pyfai_0.14.0+dfsg.orig.tar.gz, deleting 30 files from it.


it works great
