### ISSUE TITLE
silx is missing in the setup.py file install_requires

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#639]
Hello if I look at the setup.py

there is no reference to silx in the requieres part. Is it normal ?

**Comment by vallsv** [comment]
No it is not. We fixed the Debian files, but not the setup... Thanks for the feed back.

**Comment by picca** [comment]
When you says Debian files, which files are you talking about ?

**Comment by vallsv** [comment]
The ones with the dependencies `package/debian8/control` and `package/debian9/control`
