### ISSUE TITLE
[manpages] BuildMan does not work with python3.5

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#647]
Hello,

It seems that the pyFAI-calib2 script  does not work with python3.5.

(it works with python2.7 and python2.7-dbg)

I: pybuild pybuild:242: python3.5 setup.py build_man
INFO:root:Generating grammar tables from /usr/lib/python3.5/lib2to3/Grammar.txt
INFO:root:Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
INFO:pyFAI.setup:Use setuptools
running build_man
INFO:pyFAI.setup:Build man for entry-point target 'check_calib'
INFO:pyFAI.setup:Build man for entry-point target 'detector2nexus'
INFO:pyFAI.setup:Build man for entry-point target 'diff_map'
INFO:pyFAI.setup:Build man for entry-point target 'diff_tomo'
INFO:pyFAI.setup:Build man for entry-point target 'eiger-mask'
INFO:pyFAI.setup:Build man for entry-point target 'MX-calibrate'
INFO:pyFAI.setup:Build man for entry-point target 'pyFAI-average'
INFO:pyFAI.setup:Build man for entry-point target 'pyFAI-benchmark'
INFO:pyFAI.setup:Build man for entry-point target 'pyFAI-calib'
INFO:pyFAI.setup:Build man for entry-point target 'pyFAI-calib2'
help2man: can't get `--help' info from /tmp/pyFAI-calib2_lqxgr5ak
Try `--no-discard-stderr' if option outputs to stderr
Traceback (most recent call last):
  File "setup.py", line 847, in <module>
    setup_package()
  File "setup.py", line 844, in setup_package
    setup(**setup_kwargs)
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 245, in run
    raise RuntimeError("Fail to generate '%s' man documentation" % target_name)
RuntimeError: Fail to generate 'pyFAI-calib2' man documentation
E: pybuild pybuild:283: build: plugin distutils failed with: exit code=1: python3.5 setup.py build_man
dh_auto_build: pybuild --build -i python{version} -p 3.5 --after-build {interpreter} setup.py build_man returned exit code 13
debian/rules:17 : la recette pour la cible « override_dh_auto_build » a échouée

**Comment by picca** [comment]
In fact the our for python 2.7 doesn not contain the manpages but plenty of exceptions like this

.\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.47.4.
.TH ERROR:FABIO.NEXUS:H5PY "1" "July 2017" "ERROR:fabio.nexus:h5py module missing" "User Commands"
.SH NAME
ERROR:fabio.nexus:h5py \- manual page for ERROR:fabio.nexus:h5py module missing
.SH DESCRIPTION
ERROR:fabio.nexus:h5py module missing
ERROR:pyFAI.io:h5py module missing
WARNING:pyFAI.opencl.common:Unable to import pyOpenCl. Please install it from: http://pypi.python.org/pypi/pyopencl
Traceback (most recent call last):
.IP
File "/tmp/pyFAI\-calib2__zvPR_", line 2, in <module>
.IP
import pyFAI.app.calib2 as app
.IP
File "/home/picca/Debian/pyfai/pyfai/.pybuild/pythonX.Y\-dbg_2.7/build/pyFAI/app/calib2.py", line 49, in <module>
.IP
import silx.gui
.PP
ImportError: No module named silx.gui
[255145 refs]
.PP
ERROR:pyFAI.io:h5py module missing
WARNING:pyFAI.opencl.common:Unable to import pyOpenCl. Please install it from: http://pypi.python.org/pypi/pyopencl
Traceback (most recent call last):
.IP
File "/tmp/pyFAI\-calib2__zvPR_", line 2, in <module>
.IP
import pyFAI.app.calib2 as app
.IP
File "/home/picca/Debian/pyfai/pyfai/.pybuild/pythonX.Y\-dbg_2.7/build/pyFAI/app/calib2.py", line 49, in <module>
.IP
import silx.gui
.PP
ImportError: No module named silx.gui
[255145 refs]
.SH "SEE ALSO"
The full documentation for
.B ERROR:fabio.nexus:h5py
is maintained as a Texinfo manual.  If the
.B info
and
.B ERROR:fabio.nexus:h5py
programs are properly installed at your site, the command
.IP
.B info ERROR:fabio.nexus:h5py
.PP
should give you access to the complete manual.



As we can see the manpages require silx.gui (ok) -> packaging of silx

Now why python3.5 fail and python 2.7 does not fail.
It means that the return code of the script is different between python 2.7 and python3.5 ???

**Comment by vallsv** [comment]
```
As we can see the manpages require silx.gui (ok) -> packaging of silx
```
As PyFAI needs silx, and manpages needs a working PyFAI. You need silx for building the man pages, yes.

**Comment by picca** [comment]
Ok, With silx it is ok, but I need to install also the python3-pyqt4-dbg packages.
