### ISSUE TITLE
[test] please provide a way to unactive the OpenCL tests

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#667]
Hello it would be nice if the OpenGL test could be unactivated via an environment variable.

It cause  troubles during the debian package build process.

thanks

Fred

**Comment by picca** [comment]
and OpenCL ;)

**Comment by t20100** [comment]
Isn't this related to silx? There's no OpenGL in pyFAI...
If it is for silx, you can set `WITH_GL_TEST` and `SILX_OPENCL` to False (otherwise, there are options in the `run_tests.py`)

**Comment by picca** [comment]
You are right maybe this is related to openCL.
The error I saw was about dri when no X display was available.

sorry.
