### ISSUE TITLE
[calib2] Is it possible to use degree instead of radian in geoemtry fitting

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#680]
Hello,

In geometry fitting it would be nice if rot1, rot2, rot2 were expressed as degree.

**Comment by vallsv** [comment]
The coming patch will allow you to select angle unit, as user preference. To custom it you will be able to click on the unit on the geometry fitting screen. A popup will allow you to select another angle unit. This also could be done with length and wavelength, at a low cost.
