### ISSUE TITLE
[debian] integration of the debian directory in the sources of pyFAI.

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#686]
Hello, in order to ease the developpement  of pyFAI on Debian.
I think that it would be nice to put the debian directory into the sources.

It would target the unstable distribution which is the entry point for the Debian distribution.

This way a simple

git clone ...
mk-build-dep -i
debuild

would allow an easy test/installation of pyFAI.

then the debian8/debian7 directory should contain only the files which need to be overrided in the debian directory.

**Comment by picca** [comment]
Hello, Jerome,

I am still thinking abou tthis and it seems to me that the best is to put the debian directoy  for unstable directly in the sources in order to be able to build and install developpement version of pyFAI easily.

I milit for the debian directory directly because all the Debian tools expect the debian directory at this place.


So is it possible to add the debian directory directly in the sources.

To my opiinon this directory should be compatible for the current stable and unstable.... until a split is necessary...

pleaser comment  :)

**Comment by kif** [comment]
On Fri, 01 Dec 2017 14:05:06 +0000 (UTC)
picca <notifications@github.com> wrote:
> 
> pleaser comment  :)

What about putting it into the packaging (which contains the packaging extra files for any OS) as  "debian-10" or "debian-sid" ?

**Comment by picca** [comment]
This is just that Debian tools are expecting the debian directory to be located at the root of the project.
gbp-buildpackage, debuild etc...

**Comment by kif** [comment]
On Fri, 01 Dec 2017 06:42:40 -0800
picca <notifications@github.com> wrote:

> This is just that Debian tools are expecting the debian directory to be located at the root of the project.
> gbp-buildpackage, debuild etc...

On the other hand, Debian is not the only target system. We support
windows, macOS and I think MaxIV is targetting RedHat. As the "debian"
directory has to be taylored to each flavor, it would make sense to
separate "ubuntu" from "debian" as well. 
Hence it makes sense to have everything related to the packaging in
"package" + some scripts which extract the needed files in build/target
where target is debian8 for example and runs the build there.

Finally the built package(s) is copied into dist. In such a way we can
handle as many distribution/OS as needed without having the repository
polluted with files from all systems. I have to ackowledge the great
work by Valentin on this subject.

Cheers,

Jerome

**Comment by vallsv** [comment]
I never understand why debian force a directory to the root while there is so many distribution available. I am very surprise it is not customable. As said Jerome we decently can't create a directory per distribution in the root.

That's maybe not a big deal to add a `cp -r package/debianfoo debianfoo` on your side before packaging. What do you think?

BTW we also have a `build_deb.sh` script on the root for the glue.
