### ISSUE TITLE
pyFAI-calib2 saves wrong poni if the wavelength has been fitted

### ISSUE THREAD

**Issue by satarsa** [silx-kit/pyFAI#694]
In pyFAI-calib2 you unlock and fit the wavelength, then save the poni file. Result: the wavelength in the poni has the starting value, but not the fitted one.
It also seems that both the cake and the integrated image are also done using the starting value of the wavelength, but it is just a feeling which is not easy to prove.

**Comment by vallsv** [comment]
Hi, thanks for the feed back. And sorry, i did not answer before. I don't think i will have time to take a look at it before 2 or 3 weeks. Is that urgent?

**Comment by satarsa** [comment]
No, not urgent, I'm just reporting the bug. Could you reproduce it?

**Comment by vallsv** [comment]
I trust you :-)

**Comment by vallsv** [comment]
Hi. Then only the saved file looks impacted. The integration is based on the right wavelength.

**Comment by vallsv** [comment]
Thanks again for the feedback. Here is the patch https://github.com/silx-kit/pyFAI/pull/703. It should be merged before the end of the week.

**Comment by satarsa** [comment]
Ok, great, thanks!
