### ISSUE TITLE
the latest 0.14.2 pip source was not signed ?

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#695]
Hello,

while trying to work on the 0.14.2 version, I got this error message from uscan.

uscan warn: In directory ., downloading
  http://pypi.debian.net/pyFAI/pyFAI-0.14.2.tar.gz.asc failed: 404 NOT FOUND
uscan warn: FAIL Checking OpenPGP signature (no signature file downloaded).
uscan info: Scan finished

did you forgot to sign this release ?

**Comment by kif** [comment]
lintaillefer:~ % cd /tmp
lintaillefer:/tmp % git clone https://github.com/silx-kit/pyFAI
Cloning into 'pyFAI'...
remote: Counting objects: 21276, done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 21276 (delta 29), reused 49 (delta 21), pack-reused 21195
Receiving objects: 100% (21276/21276), 136.46 MiB | 9.93 MiB/s, done.
Resolving deltas: 100% (15497/15497), done.
lintaillefer:/tmp % cd pyFAI
lintaillefer:/tmp/pyFAI % git tag
before_refactoring
v0.10.1
v0.10.2
v0.10.3
v0.11.0
v0.12.0
v0.13.0
v0.13.1
v0.14.0
v0.14.1
v0.14.2
v0.7.2
v0.8
v0.9.2
lintaillefer:/tmp/pyFAI % git tag -v v0.14.2
object 871c2dc00f80684f449827e184e6f62291285216
type commit
tag v0.14.2
tagger Jerome Kieffer <jerome.kieffer@esrf.fr> 1505400653 +0200

PyFAI version 0.14.2

Bugfix release with >110 commits:
* Fix seg-fault with manylinux1 wheels, in fastcrc module (thanks
Thomas)
* Fix Qt4-Qt5 compatibility (thanks Vadim)
* Easier to understand geometry transformation (thanks Jon)
* Lower memory consumption, better cache management
* Unified debian packaging working for 6->9
* New detector: Mythen & CirPad (thanks Fred)
* Clean up debug code which avoid to use pyFAI-calib2
* pyFAI-calib2 now expect fabio >= 0.5
* Fix issue with metadata saving in 1d
* Fix performance regression with pyopencl >2015.2 (Thanks Andreas)
* pyFAI saxs and waxs scripts guess now the binning of the detector
(thanks Fred).
gpg: Signature made Thu 14 Sep 2017 04:52:39 PM CEST
gpg:                using RSA key B6DDAE4AEFFC372B1CD20D479EA87A4CB8C8CE7C
gpg:                issuer "jerome.kieffer@esrf.fr"
gpg: Good signature from "Jerome Kieffer <jerome@terre-adelie.org>" [unknown]
gpg:                 aka "Jerome Kieffer <kieffer@lintaillefer.esrf.fr>" [unknown]
gpg:                 aka "Jerome Kieffer <jerome.kieffer@esrf.fr>" [unknown]
gpg:                 aka "Jerome Kieffer <jerome.kieffer@terre-adelie.org>" [unknown]
gpg:                 aka "Jerome Kieffer <root@lintaillefer.esrf.fr>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: B6DD AE4A EFFC 372B 1CD2  0D47 9EA8 7A4C B8C8 CE7C

**Comment by kif** [comment]
OK I found the bug: I did upload the files with twin but without the "-s" option to sign them on the fly.

**Comment by kif** [comment]
I could not send the signature only, I have removed the source file and re-uploaded it under a different name. That's the best I could do.

**Comment by picca** [comment]
It works thanks
