### ISSUE TITLE
Appveyor in repo

### ISSUE THREAD

**Issue by CJ-Wright** [silx-kit/pyFAI#729]
Would it be possible to add the appveyor info into the repo? This may help with the making of a windows conda-forge build.

**Comment by vallsv** [comment]
Hi. What do you mean by info? and where?
There is information on the README displaying if tests succeed or not.

**Comment by CJ-Wright** [comment]
Yes but where is the file itself which has the configuration. We'd like to package a Windows version for conda-forge and having the configuration that actually runs on a Windows system would be helpful.

**Comment by kif** [comment]
Are you looking for the appveyor configuration file ?
it is: https://github.com/silx-kit/pyFAI/blob/master/ci/appveyor.yml

**Comment by CJ-Wright** [comment]
Yep thank you!
