### ISSUE TITLE
[Inpainting] maybe fixed upstream

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#739]
> I'm making a simple script to use the inpainting ad for some reason the
> inpainting() method gets stuck (run on rnice8) without any errors.
> 
> python /data/id31/inhouse/scripts/pyFAIWInpaint.py -j .azimint.json -o .
> empty_spin_P3_0001_0000.edf
> 
> run from /data/visitor/ma3624/id31/Agnieszka folder.
> 
> The problem is on line 235.
> 
> When I use it in the jupyter notebook (
> http://scisoft13:8000/user/drnec/notebooks/temp/Inpainting.ipynb), it is
> perfectly fine.

**Comment by vallsv** [comment]
Same here.

I copy-paste the script and the data from ID31, with up-to-date libs

**Comment by vallsv** [comment]
I found that the inpainting request was fully masked. Then there was no solution to the problem. @kif can we check it together with the data? To be sure.

I also found that the input data of the `polar_inpaint` is quite strange: `img.shape ==  [512, 1024, 0, 0, 0, 0, 0, 0]` but `img.ndim == 2`. Then it also make me crazy. Any idea why? Maybe i don't understand some magic numpy concepts.

**Comment by vallsv** [comment]
Then i was wrong, the user mask is not fully masked, maybe there is a problem in the mask transformation from x/y space to to azym/radial space.

**Comment by kif** [comment]
Indeed this is a bug but not fixed upstream.
The issue comes when dark/flat are defined in the AI. This causes some perturbation on the mask integration which is performed prior to inpainting.

**Comment by vallsv** [comment]
flat = 1, and dark = 0 did the job.
