### ISSUE TITLE
Merge changes from silx setup/bootstrap

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#749]

**Comment by kif** [comment]
mostly done... some polishing postponed to 0.16

**Comment by kif** [comment]
I believe the "HAVE_OPENMP" compile time option vanished whithin the setup.py which prevent proper "cythonization"

**Comment by vallsv** [comment]
`HAVE_OPENMP` is still there, but maybe the behaviour of reusing the precompiled c files have to be patched. I guess using `--no-cython` or `--force-cython` should force recompilation of the cython files. Using no command arg should reuse the generated files, or generate them using cython.
