### ISSUE TITLE
Update constants value

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#758]
Use the one from scipy to avoid having to maintain physical constants:
`pyFAI.units.hc = scipy.constants.c*scipy.constants.h/scipy.constants.e*1e5`

**Comment by kif** [comment]
Should be 
pyFAI.units.hc = scipy.constants.c*scipy.constants.h/scipy.constants.e*1e7

**Comment by vallsv** [comment]
Oups... I create a PR.
Crazy that no tests catch it.

**Comment by kif** [comment]
the value should be close to 12.4 (keV <-> A)
