### ISSUE TITLE
rm pyFAI/ext/histogram.c not in repo

### ISSUE THREAD

**Issue by CJ-Wright** [silx-kit/pyFAI#777]
is `rm pyFAI/ext/histogram.c` still needed for OSX builds?

**Comment by kif** [comment]
On Thu, 01 Feb 2018 17:26:20 -0800
"Christopher J. Wright" <notifications@github.com> wrote:

> is `rm pyFAI/ext/histogram.c` still needed for OSX builds?

We have removed the generated C-files and made Cython a build dependency for building from the git repo.

The "rm" is still needed if you start from the release source tar.gz which still contains openmp-enabled C-code.

**Comment by CJ-Wright** [comment]
Thank you
