### ISSUE TITLE
Split detectors in several modules

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#784]
We can create a `detectors` package containing few modules without breaking the API.

- `__init__` (while still expose all the available detectors)
- `_common` (for base classes and factories)
- `_pilatus`
- `_eiger`
- `_rayonix`
- `_others`

**Comment by kif** [comment]
On Tue, 06 Feb 2018 09:51:30 +0000 (UTC)
Valentin Valls <notifications@github.com> wrote:

> We can create a `detectors` package containing few modules without breaking the API.
> 
> - `__init__` (while still expose all the available detectors)
> - `_common` (for base classes and factories)
> - `_pilatus`
> - `_eiger`
> - `_rayonix`
> - `_others`

I believe it is possible without too much work

-- 
Jérôme Kieffer
tel +33 476 882 445

**Comment by vallsv** [comment]
Closed by #795
