### ISSUE TITLE
Add metadata to the detectors

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#785]
To be able to provide a generic GUI to select a detector, it would be nice to add metadata on the classes about model name and manufacturer.

**Comment by kif** [comment]
On Tue, 06 Feb 2018 09:53:18 +0000 (UTC)
Valentin Valls <notifications@github.com> wrote:

> To be able to provide a generic GUI to select a detector, it would be nice to add metadata on the classes about model name and manufacturer.

There are aliases but adding the manufacturer is not an issue.

-- 
Jérôme Kieffer
tel +33 476 882 445
