### ISSUE TITLE
use pyFAI without opencl and avoid annoying warnings

### ISSUE THREAD

**Issue by newville** [silx-kit/pyFAI#788]
We're using pyFAI, but not using opencl.  Every time we run a program that imports pyFAI, we get a Warning of 

    WARNING:pyFAI.opencl.common:Unable to import pyOpenCl. Please install it from: http://pypi.python.org/pypi/pyopencl

Well, we are not planning on using opencl for every use of pyFAI., and it would add a pretty big dependency  to our code.  

We can set the environment variable `PYFAI_OPENCL' to '0' to change this message to 

    WARNING:pyFAI.opencl.common:Use of OpenCL has been disables from environment variable: SILX_OPENCL=0

(seems like a misleading message, BTW).  But we don't see a way to turn such messages off.   

Is it possible to use pyFAI with this message being written every time?   Perhaps we could set environmental variable of 'PYFAI_OPENCL'  to 'WE_KNOW_IT_IS_MISSING' or something similar to suppress these warnings?

Thanks!

**Comment by vasole** [comment]
I think you are right the log level once the environmental variable has been set should be INFO and not WARNING

Independently of the request, you should be able to prevent that warning with something on the lines of:

import logging
logging.getLogger("pyFAI.opencl.common").setLevel(logging.CRITICAL)

**Comment by kif** [comment]
We could lazy load opencl and offer an option:

```
import pyFAI
pyFAI.disable_opencl=True
```

**Comment by vallsv** [comment]
As discussed today the better thing to do is to warn when OpenCL is requested at the computation stage. This say it will maybe request refactoring, then have to be investigated.

**Comment by newville** [comment]
Maybe the way to think about this is that use of  `logger.warning()` for import errors is going to be the cause of many annoying messages.   It might be better to warn about missing optional packages at install time. or to warn when the functionality is actually requested by the API.

In `opencl.common.py` you warn and also set `pyopencl = False` if the import fails.   You might consider adding a "WithPyOpenCl" decorator for each function that actually needs opencl, and that decorator could simply raise an exception  `if not pyopencl`.   That exception would happen when trying to use `pyFAI.opencl`, but not when importing `pyFAI`.

FWIW, I think there are similar import-time warnings in the `pyFAI.matplotlib` module if one of the PyQt variants isn't installed...

**Comment by vallsv** [comment]
The matplotlib/qt thing is relatively more complex. It also can be your responsibility if you import matplotlib, or Qt before, else it's a problem on the order of imports on our side.

**Comment by newville** [comment]
@vallsv  re: matplotlib/qt  Oh, I agree completely that order is (can be) important and subtle with matplotlib.  

I just meant that in the rare case (that you probably never see, and I have seen only once or twice) where matplotlib is installed but no PyQt wrapper is installed that you'll get an import-time warning similar to the case when opencl is not installed.

**Comment by vallsv** [comment]
Here is the implementation on my branch. As proposed by Jerome, we will provide an API to disable OpenCL programatically.

```
In [1]: import pyFAI
/home/valls/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
In [2]: pyFAI.use_opencl = False
In [3]: import pyFAI.opencl
In [4]: print(pyFAI.opencl.pyopencl)
None
```
As you can see there is no more log on our side.

It will be merge in few weeks.

**Comment by newville** [comment]
@vallsv Thanks!  That will be very helpful...  I guess I should go complain to the h5py folks next ;).

**Comment by vallsv** [comment]
Exactly :-)
