### ISSUE TITLE
Create the Mar555 detector

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#789]
135um pixel size

**Comment by kif** [comment]
On Thu, 08 Feb 2018 08:28:30 -0800
Valentin Valls <notifications@github.com> wrote:

> 135um pixel size

There is also 139 and 140 µm pixel size in this document:
http://petra3-project.desy.de/e13/e1034/e1036/e1557/e2207/e95745/Webinfo.mar555_eng.pdf

According to the size the pixel size should be 136.7x139.9
Without a proper calibration, defining this detector is probably useless. 

Who is requesting this ? can he provide the recording of a grid pattern ?
I can calibrate it if needed.

-- 
Jérôme Kieffer
tel +33 476 882 445
