### ISSUE TITLE
define rotation from quaternion

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#815]
Rotations of the detector is properly parametrized in pyFAI but it would be great to define it from a quaternion, especially when dealing with multi-axis goniometers.

Impacts 2 beamlines

**Comment by picca** [comment]
Hello, Jerome,

I am using quaternion in the hk library in order to represent the rotations.
Where do you want to put the quternions in pyFAI ?

**Comment by kif** [comment]
On Tue, 27 Mar 2018 08:11:44 +0000 (UTC)
picca <notifications@github.com> wrote:

> Hello, Jerome,
> 
> I am using quaternion in the hk library in order to represent the rotations.
> Where do you want to put the quternions in pyFAI ?

ai.set_rot_from_quaternion([a,b,c,d])

-- 
Jérôme Kieffer
tel +33 476 882 445

**Comment by kif** [comment]
The code has been merged, it work
There will be a tutorial on this ... a bit later
