### ISSUE TITLE
Distortion correction device server requested by ID02 (part of UPBL)

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#82]
Design:
Probably a Tango device server 

Receives:
image as file, slice in hdf5, network stream ?

Output:
another image (same size ?) as file, slice in hdf5, network stream ?
output is probably as float array

Configuration: to be refined
will handle spline file and distortion array dx,dy.
Correction dark, flat and mask (before distortion)
requested: binning, ROI, orientation correction (applied before distortion correction)

**Comment by kif** [comment]
This is available as a worker.

**Comment by toqduj** [comment]
Awesome!
