### ISSUE TITLE
calib2 polygon mask right click

### ISSUE THREAD

**Issue by jangarrevoet** [silx-kit/pyFAI#838]
On centos 7 with a kde session when trying to set the last point of the polygon mask using right click it does not set the last point but gives you to option "Zoom Back" instead.

**Comment by vallsv** [comment]
Hi,

Thanks for the feed back. I think it is relative to silx, but it's also fine here.

Could you check the version of pyFAI and silx you are using?

**Comment by t20100** [comment]
With applications using silx mask, you can close a polygon with a left click on the first point.
We would like to keep the right click for context menu.
It might be worth adding a menu entry to close the polygon in the context menu along with "zoom back".

**Comment by vallsv** [comment]
Oh, yes, you are maybe right, i forgot it's the default behaviour.
If you use to play with PyMca the behaviour is maybe not the same.

**Comment by jangarrevoet** [comment]
I compiled from the latest master (MAJOR = 0
MINOR = 15
MICRO = 0
RELEV = "dev"  # <16
SERIAL = 1  # <16
)

What the behaviour is, is all the same to me. I was just using right click since that is what the tooltip tells you to do to close the polygon.

**Comment by vallsv** [comment]
Because the behavior have changed. It is not possible to close the polygon in this way anymore. You have to click back to the first point.

**Comment by t20100** [comment]
There is an error in the tooltip.

We'll fix it for the next release of silx (planned for june) See issue: https://github.com/silx-kit/silx/issues/1845
Thanks for the feedback

**Comment by vallsv** [comment]
Hi.

If you have installed silx 0.9 it should be fixed.

Feel free to reopen this issue if you still have inconsistencies.
