### ISSUE TITLE
Bug in Spline.array2spline : xmax and ymax inverted ? 

### ISSUE THREAD

**Issue by jonwright** [silx-kit/pyFAI#841]
I was making a spline file for an ROI (frame transfer mode) and came across a glitch in spline.py (python2 on rnice at ESRF) :

```
In [1]: from pyFAI import spline 
In [2]: s = spline.Spline("halfccd.spline")
In [3]: s.spline2array()
In [4]: s.array2spline()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-24bc5d5a0bb9> in <module>()
----> 1 s.array2spline()

/usr/lib/python2.7/dist-packages/pyFAI/spline.pyc in array2spline(self, smoothing, timing)
    443             numpy.arange(self.ymax + 1),
    444             self.xDispArray.transpose(),
--> 445             s=smoothing)
    446 
    447         if timing:

/usr/lib/python2.7/dist-packages/scipy/interpolate/fitpack2.pyc in __init__(self, x, y, z, bbox, kx, ky, s)
    958             raise TypeError('y must be strictly ascending')
    959         if not x.size == z.shape[0]:
--> 960             raise TypeError('x dimension of z must have same number of '
    961                             'elements as x')
    962         if not y.size == z.shape[1]:

TypeError: x dimension of z must have same number of elements as x
```
If you assign self.xmax and self.ymax in reverse then it works well. Since halfccd.spline is already in the test data it seems this is worth adding as a testcase ?

**Comment by kif** [comment]
On Thu, 31 May 2018 09:32:54 -0700
Jon Wright <notifications@github.com> wrote:

> I was making a spline file for an ROI (frame transfer mode) and came across a glitch in spline.py (python2 on rnice at ESRF) :
> 
> ```
> In [1]: from pyFAI import spline 
> In [2]: s = spline.Spline("halfccd.spline")
> In [3]: s.spline2array()
> In [4]: s.array2spline()
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-4-24bc5d5a0bb9> in <module>()
> ----> 1 s.array2spline()  
> 
> /usr/lib/python2.7/dist-packages/pyFAI/spline.pyc in array2spline(self, smoothing, timing)
>     443             numpy.arange(self.ymax + 1),
>     444             self.xDispArray.transpose(),
> --> 445             s=smoothing)  
>     446 
>     447         if timing:
> 
> /usr/lib/python2.7/dist-packages/scipy/interpolate/fitpack2.pyc in __init__(self, x, y, z, bbox, kx, ky, s)
>     958             raise TypeError('y must be strictly ascending')
>     959         if not x.size == z.shape[0]:
> --> 960             raise TypeError('x dimension of z must have same number of '  
>     961                             'elements as x')
>     962         if not y.size == z.shape[1]:
> 
> TypeError: x dimension of z must have same number of elements as x
> ```
> If you assign self.xmax and self.ymax in reverse then it works well. Since halfccd.spline is already in the test data it seems this is worth adding as a testcase ?

Hi Jon,

Thanks for spotting it ... I'll have a look next week

**Comment by kif** [comment]
Hi Jon,

I hardly ever used this feature and I wouldn't be surprized if a bug
was laying around there. 

-- 
Jérôme Kieffer

**Comment by kif** [comment]
I wish to reopen this as the test takes a lot more time ... which I consider is a regression

**Comment by kif** [comment]
done.
