### ISSUE TITLE
check if mask is not C-contiguous

### ISSUE THREAD

**Issue by Miradin** [silx-kit/pyFAI#849]
Hello, 
just a quick suggestion, to check flags of mask and convert it into C-contiguous array if needed.
For example, mask obtained using MaskImageWidget() could be not C-contiguous, which causes error during crc32 calculation.

file azimuthalIntegrator.py

right before the line 2224:  
```python
if (mask.flags.c_contiguous is False):
    mask = numpy.ascontiguousarray(mask, numpy.int)
```
same changes right before the line 2880

Best regards,
Alexander

**Comment by kif** [comment]
indeed...
