### ISSUE TITLE
[calib2] Rework the way rings are displayed in fitting/integration

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#877]
When zooming in/out or panning displayed rings are not always the same.

Plus there is no information on the number of the rings.

As result it is difficult to know what it is displayed.

**Comment by picca** [comment]
It would be nice to have a popup or just the information when the mouse is on the ring which gives the ring number, theoretical tth, q, d, etc...

and maybe to compare,somewhere the pixel equivalent informations for the given mouse position.

**Comment by kif** [comment]
I do agree with fred's comment.
Maybe the calibrant object could expose the comment of the D-file (containing HKL indexes or weakness information)

**Comment by vallsv** [comment]
The coming application will allow you to load your own calibrant file. And the issue #901 should provide to you a way to annotate few things on this files (the basic idea is to display the comments).

With that you could do what you want without a specific GUI tool.
