### ISSUE TITLE
saxs, splitpixel mode: intensity estimates are correlated

### ISSUE THREAD

**Issue by dfranke76** [silx-kit/pyFAI#884]
pyFAI in splitpixel mode correlates the intensity estimates. The figure below was compiled from pair-wise comparisons of 1390 consecutive SAXS frames of water obtained at P12 at PETRA-III. The frames are similar up to noise as per cormap test as implemented in datcmp of ATSAS.

For the figure below, the original data as radially averaged by pyFAI in histogram mode (first row), pyFAI splitpixel mode unmodified (second row), pyFAI splitpixel mode with patch applied (third row, #883), and radaver for comparison (fourth row) was re-binned by joining two adjacent data points with datregrid of ATSAS. In the first column, the empirical chi^2 distributions of the original data are shown, in the second column the empirical chi^2 distributions after re-binning, together with the corresponding p-values (third column).

![chi2-pval](https://user-images.githubusercontent.com/15729164/43762674-df6e92b8-9a28-11e8-8555-a438054d9d1d.png)

In histogram mode, there is no correlation of intensities, panel (b) is essentially the same as panel (a). The previously described (#882) under-estimation of errors is evident again (c). In splitpixel mode without fix, the empiricial distribution shifts to the right (panel (e)), however, this does not mean that they get "better" in any way, they are only differently wrong. With the patch of #883 applied, this is more obvious as the distribution in (g) is almost acceptable, while (h) clearly shows the shift away from 1.0. Lastly, for reference, the radaver results in panels (j) to (l).

Here the absence of any shift in panel (b) and the presence of a shift in panel (h) are key. Due to the implementation of splitpixel mode, the intensities are correlated, but this correlation is not taken into account on error propagation as they are not estimated nor stored together with the data. 

While the correlation of the intensities has no direct effect on averaging or subtracting frames, it will always result in wrong error estimates on re-binning adjacent data points.

**Comment by kif** [comment]
We are about to release v0.18 which mitigates as much as possible this issue as demonstrated (if using the _integrate1d_ng function):
https://github.com/kif/pyFAI/blob/master/doc/source/usage/tutorial/Variance/Variance.ipynb

You can play with it here (modulo the amount of RAM available):
https://hub.mybinder.org/user/silx-kit-pyfai-vz4cc3gx/notebooks/doc/source/usage/tutorial/Variance/Variance.ipynb
