### ISSUE TITLE
Would it be possible to get a release?

### ISSUE THREAD

**Issue by CJ-Wright** [silx-kit/pyFAI#890]
Would it be possible to get a release? I'd really like to use the enhancements made to picking AzimuthalIntegrators. I don't need a full minor version, a bug fix bump would be fine.

**Comment by vallsv** [comment]
Hi.

Yet we don't have plan any release. Which fixes are you talking about?

Did you already tried to compile your own version of pyFAI, in this case it could be very easy.

We should have a cleared idea on September, cause i am alone here right now.

**Comment by CJ-Wright** [comment]
I don't mind compiling my own version for myself but I'd like to have binaries to distribute.
This is the fix I'm interested in, I think. https://github.com/silx-kit/pyFAI/commit/27df3c619ca916a3e29d30cd1b7b6c06a049d1dd

My current error (working with `0.15.0`) is:
```python
In [1]: import pickle

WARNING:pyFAI.opencl.common:Unable to import pyOpenCl. Please install it from: http://pypi.python.org/pypi/pyopencl
In [2]: from pyFAI.azimuthalIntegrator import AzimuthalIntegrator

In [3]: ai = AzimuthalIntegrator()

In [4]: b = pickle.dumps(ai)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-572665af1ba0> in <module>()
----> 1 b = pickle.dumps(ai)

TypeError: can't pickle _thread.lock objects
```
I'm hoping that the fix mentioned above will fix this.

**Comment by CJ-Wright** [comment]
Can I patch the existing 0.15.0 with the new pickle features?

**Comment by vallsv** [comment]
No idea. But why not.
I don't think we have change much on the core functions.

**Comment by kif** [comment]
we can try to settle down what is ongoing and release in September.

**Comment by vallsv** [comment]
Here is the release.

Sorry it have taken more time than expected. Mostly to clean up things on the GUI.

But you should also have a more stable core.
