### ISSUE TITLE
Warning reported by debian ...

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#927]
The whatis entry for this manual page (the brief description found in the NAME section) is of the form:

         program - manual page for program
        

    This conveys no information about what the program is for and is repetitive. The short description should contain brief information about what the program is for to aid in searching with apropos and similar programs.

    If this manpage was generated by help2man, use the -n option to provide a more meaningful description.

    Severity: normal, Certainty: certain

    Check: manpages, Type: binary

**Comment by vasole** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=908615

**Comment by vallsv** [comment]
`ModuleNotFoundError: No module named 'pyFAI.ext.histogram'` means the extensions was not compiled, or not loaded. It could be interesting to see if the `so` files was here or not, and if we can manually load it.

**Comment by picca** [comment]
This is just the python3.7 transition.
pyFAI was not yet rebuild with the python3.7 support.

This is why the unit test failed.

**Comment by picca** [comment]
In fatc pyFIA was affected by the pyopencl python3.7 transition which is now fixed.

so a new NMU shoudl fix the python3.7 issue.

Are you aware of other python3.7 problem with pyFAI 0.15 ?

**Comment by kif** [comment]
And for this debian wants to remove pyFAI by the 22nd of octobre ?

**Comment by picca** [comment]
remove from testing not from Debian :))
And if you gives some information to the bug report this automatic process is postpone for a future date.


I will discuss with release team in order to resquedule a binNMU.
do not worry, we will not release Debian without pyFAI :))

**Comment by picca** [comment]
Voila c'est fait

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=910572

**Comment by kif** [comment]
On Mon, 08 Oct 2018 00:49:03 -0700
picca <notifications@github.com> wrote:

> Are you aware of other python3.7 problem with pyFAI 0.15 ?

I tested the whole day on py37 with buster and sid.... 

Some tests (the 2 usual OpenCL tests on sort) are failing on POCL
platform but I am patching the tests to accept it even if results are
wrong (at least the code passes).

-- 
Jérôme Kieffer
tel +33 476 882 445

**Comment by picca** [comment]
Hello, here the laster CI from Debian now that it was rebuild  with the python3.7 support.

https://ci.debian.net/data/autopkgtest/unstable/amd64/p/pyfai/1111910/log.gz

```
python2              PASS
python2-dbg          PASS
python3              FAIL non-zero exit status 1
python3-dbg          PASS
```

So now the question is why this faillure only for the python3 version and not the python3-dbg version :)

**Comment by vallsv** [comment]
Jerome found that the behaviour relative to `app --version` status changes in Python 3.7. It is used by `help2man`. Yet we don't really know exactly why. The `ArgParse` library changes from Python 2.7 to Python 3, and we also locally provide our own `ArgParse`. There is things to investigate.

**Comment by vallsv** [comment]
Then we can close this issue non?
