### ISSUE TITLE
polarization specification

### ISSUE THREAD

**Issue by newville** [silx-kit/pyFAI#951]
Sorry if this has been covered somewhere else before or if this is just me not understanding.   I've looked through the tutorials and am still confused.

I think I do not understand the meaning of the polarization option for azimuthal integration. The docs say this is a polarization "factor", a single value, with 1 meaning horizontal and -1 meaning vertical.  

What does horizontal mean for the image?  Is it expected that either the rows or the columns are in the horizontal direction?   The geometry with 3 rotations allows images in any orientation with respect to the horizontal plane in the laboratory frame.  Shouldn't I have to specify a polarization direction with at least three numbers (more for elliptical polarization)?

Thanks!

**Comment by kif** [comment]
Hi Matt,

I am not a specialist of polarization and simply implemented the same
mechanism as FIT2D, using the same formula.

On Thu, 18 Oct 2018 19:10:38 -0700
Matt Newville <notifications@github.com> wrote:

> Sorry if this has been covered somewhere else before or if this is just me not understanding.   I've looked through the tutorials and am still confused.
> 
> I think I do not understand the meaning of the polarization option for azimuthal integration. The docs say this is a polarization "factor", a single value, with 1 meaning horizontal and -1 meaning vertical.  

The geometry in pyFAI, especially this part, is optimized for
synchrotrons.

Did you see this image:
http://www.silx.org/doc/pyFAI/dev/geometry.html#detector-position

The incoming beam defines X3. 
The synchrotron plan (or the plan orthogonal to the ondulator) defines
the horizontal.

As a consequence, the horizontal direction X2 (used in the polarization definition)
is defined by the intersection the the orthogonal plan to the incident
beam and the synchrotron plan. 
The vertical direction X3 is defined the same way.

This assumes the optics do not change "too much" the beam direction. 

> What does horizontal mean for the image?  Is it expected that either
> the rows or the columns are in the horizontal direction?

The detector is moved independently for all this and rotation around
the 3 directions.
you detector can be mounted at 90°, just set rot3 to pi/2

> The
> geometry with 3 rotations allows images in any orientation with
> respect to the horizontal plane in the laboratory frame.  Shouldn't I
> have to specify a polarization direction with at least three numbers
> (more for elliptical polarization)?

Some people (P. Boesecke) asked for this a while ago. But as long as
there is no precise bug report, or missing use-case, with preferably a
(numeric) regression test I will not invest time in this direction
(i.e. we have plenty of bugs with actual test regression). 

Cheers,

-- 
Jérôme Kieffer

**Comment by newville** [comment]
@kif Thanks for the reply!

>  Did you see this image: http://www.silx.org/doc/pyFAI/dev/geometry.html#detector-position

Yes, I did see this and the tutorial.

> The incoming beam defines X3. The synchrotron plan (or the plan orthogonal to the 
> ondulator) defines the horizontal.
> As a consequence, the horizontal direction X2 (used in the polarization definition) is 
> defined by the intersection the the orthogonal plan to the incident beam and the synchrotron plan.
> The vertical direction X3 is defined the same way.

Thanks, that helps.  I wasn't 100% sure X2 was horizontal in the lab frame and so the direction of polarization for most synchrotron beams, and X1 is vertical in the lab frame.  I'm not worried about a mirror adding a small angle.

But, d1 and d2 -- the orientation of the detector -- do not have to be vertical or horizontal in the lab frame.  For example, even if d3 is nominally along X3 so that PONI and beam center are very close, the detector could be rotated by 45 degrees, so that the polarization direction would be diagonal along (d1, d2).  That's different from 'unpolarized'.   It looks like I would then need to set `rot3`  = pi/4 (or -pi/4, depending on rotation direction),  and then set `polarization` ~= +1.  Do I have that right?

In practice, I'm using an 500x1000 pixel detector with the d2 (that is, the fast moving index in the ndarray) direction vertical. Without deliberately rotating the image, the image gets drawn as a wide rectangle, with detector "up" being shown as image "right" .   The calibration program I used (Dioptas) leaves `rot3` to be 0. That's probably sensible -- a powder calibrant is pretty insensitive to `rot3`, but happens to be wrong for this image. 

Using `polarization=+1` definitely gives too big a correction, amplifying high Q values when it should amplify low Q data. Setting `polarization=-1` looks much better, but I suspect now that I should really use `rot3=pi/2` and `polarization=+1` - those look to be identical, but makes much more sense to me. Fortunately (genius!) `rot3` is applied last, and it looks like making that change gives the same results.   Do I have that right?  Thanks!

**Comment by kif** [comment]
Hi Matt,

On Fri, 19 Oct 2018 08:19:20 -0700
Matt Newville <notifications@github.com> wrote:


> > The incoming beam defines X3. The synchrotron plan (or the plan orthogonal to the 
> > ondulator) defines the horizontal.
> > As a consequence, the horizontal direction X2 (used in the polarization definition) is 
> > defined by the intersection the the orthogonal plan to the incident beam and the synchrotron plan.
> > The vertical direction X3 is defined the same way.  
> 
> Thanks, that helps.  I wasn't 100% sure X2 was horizontal in the lab
> frame and so the direction of polarization for most synchrotron
> beams, and X1 is vertical in the lab frame.  I'm not worried about a
> mirror adding a small angle.

Indeed, I doubt a few millirad will change much on the polarization !

> But, d1 and d2 -- the orientation of the detector -- do not have to
> be vertical or horizontal in the lab frame.  For example, even if d3
> is nominally along X3 so that PONI and beam center are very close,
> the detector could be rotated by 45 degrees, so that the polarization
> direction would be diagonal along (d1, d2). 

The detector is totally decoupled from the geometry in the lab-space.
It is completely free.

>  That's different from
> 'unpolarized'. 

There is something subtle: 
if the polarization factor is `None`, no correction are applied (default). 
If you provide a value then there is a polarization correction. 
If this value is 0 there is a polarization correction for a circular polarization.

>  It looks like I would then need to set `rot3`  =
> pi/4 (or -pi/4, depending on rotation direction),  and then set
> `polarization` ~= +1.  Do I have that right?

Yes you are right.

> In practice, I'm using an 500x1000 pixel detector with the d2 (that
> is, the fast moving index in the ndarray) direction vertical. Without
> deliberately rotating the image, the image gets drawn as a wide
> rectangle, with detector "up" being shown as image "right" .   The
> calibration program I used (Dioptas) leaves `rot3` to be 0. That's
> probably sensible -- a powder calibrant is pretty insensitive to
> `rot3`, but happens to be wrong for this image. 

It is normal that the refinement algorithm does not affect rot3 as the
calibration is insensitive to rot3.

You should be able to set rot3 to + or - pi/2. Look at the beam stop
orientation to discriminate the two possibilities.

> Using `polarization=+1` definitely gives too big a correction,
> amplifying high Q values when it should amplify low Q data. Setting
> `polarization=-1` looks much better, but I suspect now that I should
> really use `rot3=pi/2` and `polarization=+1` - those look to be
> identical, but makes much more sense to me. Fortunately (genius!)
> `rot3` is applied last, and it looks like making that change gives
> the same results.   Do I have that right?  Thanks!

Yes, that's right. Your beam is polarized "as usual" on a synchrotron
with a polarization facto ~1 and the detector is rotated 90°. Perfect !


There is last option (hidden) which can be used if it is the undulator
which can be rotated (like on XMCD beamlines ...). It is unlikely to do
diffraction on such beamline but if needed, it exists:
The function calculating the actual polarization correction can have the angle
offseted. I never had to use it.
http://www.silx.org/doc/pyFAI/dev/api/pyFAI.html?highlight=polarization#pyFAI.geometry.Geometry.polarization

Cheers,

Jérôme

**Comment by newville** [comment]
@kif  Great! That clears up any confusion I had.  Fortunately, I'm only using a simply polarized undulator! Thanks very much!
