### ISSUE TITLE
[gui] keep the aspect ratio

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#981]
Hello, I use the Cirpad Detector and I need to use do not keep the aspect ratio.

but When I switch from an activity to another the aspect ratio is resetted :(

Cheers

**Comment by vallsv** [comment]
Ok, i will try to synchronize all of them.

BTW, does it mean the Cirpad uses a rectangular pixel? Instead of a free aspect ratio, don't you prefer a fixed aspect ratio consistant with the width/height pixel size?

**Comment by vallsv** [comment]
Y-axes orientation is also not synchronized.
