### ISSUE TITLE
[0.16] broken API since 0.15.2

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#989]
Hello, with the 0.16 version we lost the pyFAI.Detector class.

it is now located into pyFAI.detectors.

but it means that a bunch of scripts are broken.

Cheers

**Comment by vallsv** [comment]
Yes, in fact i think `pyFAI.Detector` was not an expected behaviour.

Also if you import `pyFAI`, previously `pyFAI.detectors` was also imported. Now you explicitly have to `import pyFAI.detectors` before using it.

**Comment by picca** [comment]
ok, I will change my code.

thanks

**Comment by vallsv** [comment]
Yes, i think it is better.
Really sorry for the inconveniences. Hope it is not too much work.
At least for sure it will be more stable there.
